package org.apache.batik.svggen;
public interface CachedImageHandler extends org.apache.batik.svggen.GenericImageHandler {
    org.apache.batik.svggen.ImageCacher getImageCacher();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028785000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVXe2wcRxmfu/M7fiexQxI7LyciTrhTBUUqDqGxa9cXzo5l" +
                                          "JxXYJJe53bm7jfd2N7Oz9tkFVCohwj9VFFJakOq/XFWgUipEBUi0CkKircpD" +
                                          "LRFQUAsS//CKaIQEf4TX983s3u6tfeIvTrq5uZlvvvf3/Waev0OaXU6GmSXS" +
                                          "Ys1hbnrSEnOUu0yfMKnrnoe1vPZUiv7t0h9mH0iSlkXSXabujEZdNmUwU3cX" +
                                          "yZBhuYJaGnNnGdPxxBxnLuMrVBi2tUh2G2624piGZogZW2dI8AjlOdJHheBG" +
                                          "wRMs6zMQZCgHmmSkJpkz8e2xHOnUbGctJN8TIZ+I7CBlJZTlCtKbu0JXaMYT" +
                                          "hpnJGa4Yq3JywrHNtZJpizSrivQV837fBWdz929xweEXe/5+73q5V7pgJ7Us" +
                                          "W0jz3Hnm2uYK03OkJ1ydNFnFvUo+S1I5siNCLMhILhCaAaEZEBpYG1KB9l3M" +
                                          "8ioTtjRHBJxaHA0VEuRQPROHclrx2cxJnYFDm/Btl4fB2oM1a5WVW0x88kTm" +
                                          "5lOXer+VIj2LpMewFlAdDZQQIGQRHMoqBcbdM7rO9EXSZ0GwFxg3qGms+5Hu" +
                                          "d42SRYUH4Q/cgouew7iUGfoK4gi2cU8TNq+ZV5QJ5f9rLpq0BLYOhLYqC6dw" +
                                          "HQzsMEAxXqSQd/6RpmXD0gU5ED9Rs3Hk40AAR1srTJTtmqgmi8IC6VcpYlKr" +
                                          "lFmA1LNKQNpsQwJyQfY2ZIq+dqi2TEssjxkZo5tTW0DVLh2BRwTZHSeTnCBK" +
                                          "e2NRisTnzuypJx61pq0kSYDOOtNM1H8HHBqOHZpnRcYZ1IE62Dma+zIdePla" +
                                          "khAg3h0jVjTf+fTdB08O33pN0ezbhuZc4QrTRF7bLHS/uX/i+AMpVKPNsV0D" +
                                          "g19nuayyOX9nrOpAhxmoccTNdLB5a/5Hn3zs6+zPSdKRJS2abXoVyKM+za44" +
                                          "hsn4w8xinAqmZ0k7s/QJuZ8lrTDPGRZTq+eKRZeJLGky5VKLLf+Di4rAAl3U" +
                                          "AXPDKtrB3KGiLOdVhxDSCl+SgO9Roj5DOAhyMVO2KyxDNWoZlp2Z4zba72ag" +
                                          "4xTAt+VMAbJ+OePaHocUzNi8lKGQB2UWbKyUSszKTOCSnq1ADkxTSwej0phm" +
                                          "zv9bQBUt3LmaSIDz98dL34SqmbZNnfG8dtMbn7z7Qv4NlVZYCr5vBBkFmWkl" +
                                          "My1lppXM9FaZJJGQonahbBVjiNAy1Do0287jCxfPXr52OAXJ5aw2oX+rsvj2" +
                                          "BX/gYExHWeYfXXCe+dVP//jBJEmGHaEn0soXmBiLZCHy7Jf51hfqcZ4zBnTv" +
                                          "PD33pSfvfGFJKgEUR7YTOILjBGQftFRoTZ9/7erbv31383aypnhKQBv2CoBm" +
                                          "grTRAvQwqglB2mvNSBm26z/wScD33/hFG3FBJVb/hJ/dB2vp7TgRdyTkfI8g" +
                                          "Jxq5X54ztKj/0YVDjXqH7Hubj9/c0M89e5+q8P76epwEuPnGL/714/TTv3t9" +
                                          "m0RoF7bzAZOtMLNOTxBZd3GYkW01AOG89k73jd9/b6Q0niRNOdIPjvKoiVeA" +
                                          "M7wE4KIt+/23swC3iRDUD0ZAHW8j3NaYDpjSCNx9Lm32CuO4LsiuCIfgyoHN" +
                                          "dbQx4MdVf/XxP+09f7p8WWZeFMJRWjOgD56cQ+CtAeyBmPvjLL828/zrDx/T" +
                                          "biQl5mD/3gar6g+NRQMBQjkDcLXQHFzpAqGH46Ud91ZeGz1IX8q//JkRGYV2" +
                                          "AF5BoVECpg3HhdfhxlhQcSiqDZxQtHmFmrgVuLxDlLm9Gq7IntOnCgASpBfz" +
                                          "fRi+R/zOKn9xd8DBcVD1KEk/LMdDOIzI7Eri9CgOxyTZ+yHbjoVFDVBgQrfE" +
                                          "iIxcsCDsRtGgBZNhu/lnz9H7XvrLE70qkU1YCUJ08n8zCNffN04ee+PSP4Yl" +
                                          "m4SGV5Gw8YRkCt92hpzPcE7XUI/q594a+sqr9BlASkAn11hnEnCI3/RQqQlp" +
                                          "9mk5jsf2JnH4iCDdJUA3LHXZdXnQHY406g5RWk5GGuR85L6Z167ffq/rkfde" +
                                          "uStNrb+wRrvtDHXGVIxxGMOeMxjv99PULQPdh27NfqrXvHUPOC4CRw0QzD3H" +
                                          "AXCqdb3Zp25u/fUPfjhw+c0USU6RDtOm+hTFqyEAPKQYc8uAVVXnYw+qNFpt" +
                                          "C5KrSrZ4bssCRufA9nGfrDhCRmr9u4PfPvXcxruyzztV7NFbEA757Nlyh1b3" +
                                          "Pu2FjZ62wY0Lv5Q1VrubdUJXKnqmGSnhaDm3OJwVDenQTuVWR/5cEGSwQXAB" +
                                          "fdREmnle0X8CnjdxekGa5W+UbkmQjpAOWKlJlOSSICkgwWkeHJGoR2n8k8Vh" +
                                          "t5rnGkYkAuxH6hJQvlWCBump10pe++bG2dlH7374WYXz8MpZX5d3W7iqq65T" +
                                          "a7KHGnILeLVMH7/X/WL70aRfRn1K4bDV7IvU2DzAmIOR3RurX3ekVsZvb556" +
                                          "5SfXWt6CVF4iCSrIzqXIS0Fdi6EJeICGS7kQDyNvXdlYxo5/de30yeJffyOT" +
                                          "zMfP/Y3p89rt5y7+/MaeTWhAO7KkGSCcVRfh2eM+tGbNM22FL5Iuw52sgorA" +
                                          "Bd5hWdLmWcZVj2XhhdWNSUjxFSP94ruzq7aKQCHI4S3PlW3QFgpylfFx27N0" +
                                          "CTvQIsKVukdUgFOe48QOhCu1UO7aantee+iLPd+/3p+agkKqMyfKvtX1CjUM" +
                                          "jL6rFCji2Csho6ouXKl8bsZxggtYx8/825ataHBdkMSov4qtI6HuN/iXS3ZX" +
                                          "5RQH8V9Rea7JMhEAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028785000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5e8zrVn2+331fSu9tgbYrtKXtLVob+JzYcZzoAsN2EjuO" +
                                          "E8d24jje4NbxI3biV/xInEAnVmmjGhJDW9mYBP0LtA2Vh6ahTZqYOk0bINAk" +
                                          "JrSXNoqmSXuwavSPPTS2sWPne93v9lLxxyL55OSc3/t1fH558RXofBxBpTBw" +
                                          "NzM3SPbNLNmfu9h+sgnNeJ/lsIEWxaZBuVocD8HaTf2xL1399x983L62B11Q" +
                                          "oTdpvh8kWuIEfiyaceCuTIODrh6vtlzTixPoGjfXVhqcJo4Lc06c3OCgN5xA" +
                                          "TaDr3KEIMBABBiLAhQgwcQwFkN5o+qlH5Rian8RL6GehMxx0IdRz8RLo0VuJ" +
                                          "hFqkeQdkBoUGgMKl/LcMlCqQswh6+5HuO51vU/gTJfj5X/vAtd8+C11VoauO" +
                                          "L+Xi6ECIBDBRobs805uaUUwYhmmo0D2+aRqSGTma62wLuVXo3tiZ+VqSRuaR" +
                                          "kfLFNDSjguex5e7Sc92iVE+C6Eg9yzFd4/DXecvVZkDX+4513WnYzteBglcc" +
                                          "IFhkabp5iHJu4fhGAj1yGuNIx+tdAABQL3pmYgdHrM75GliA7t35ztX8GSwl" +
                                          "kePPAOj5IAVcEujBOxLNbR1q+kKbmTcT6IHTcIPdFoC6XBgiR0mgt5wGKygB" +
                                          "Lz14yksn/PNK/90f+6DP+HuFzIapu7n8lwDSw6eQRNMyI9PXzR3iXU9xv6rd" +
                                          "95Xn9iAIAL/lFPAO5nc/9Or73vnwS1/bwbz1NWD46dzUk5v6Z6Z3f+tt1JON" +
                                          "s7kYl8IgdnLn36J5Ef6Dg50bWQgy774jivnm/uHmS+KfTD78OfN7e9CVDnRB" +
                                          "D9zUA3F0jx54oeOaEW36ZqQlptGBLpu+QRX7HegimHOOb+5WecuKzaQDnXOL" +
                                          "pQtB8RuYyAIkchNdBHPHt4LDeagldjHPQgiCLoIHOgOeJ6Dd56F8SKD3w3bg" +
                                          "mbCma77jB/AgCnL9Y9j0kymwrQ1PQdQv4DhIIxCCcBDNYA3EgW0ebqxmM9OH" +
                                          "qXzJ6HggBhjNN4BS+3mYhf/fDLJcw2vrM2eA8d92OvVdkDVM4BpmdFN/PiVb" +
                                          "r37h5jf2jlLhwDYJ9BTgub/juV/w3N/x3L+dJ3TmTMHqzTnvnY+BhxYg10EV" +
                                          "vOtJ6f3s0889dhYEV7g+l9s3K5LvgeLHWYD35J0rczsvC52iFOogUh/4L96d" +
                                          "Pvt3/1nIe7K45gT3XiMbTuGr8IufepB67/cK/MugDiUaiBuQ4g+fzslb0ihP" +
                                          "ztN2BOX1mC7yOe/f9h678Md70EUVuqYf1G5Zc1NTMkH9vOLEhwUd1Pdb9m+t" +
                                          "PbtEu3GQ4wn0ttNynWB747BQ5sqfP+k/MM+h8/mVIhbuLmDu+SH4nAHP/+ZP" +
                                          "7ol8YRfx91IHaff2o7wLw+zMmQQ6j+zj++Uc/9Hcx6cNnAvwHin89F/+6T+h" +
                                          "e9DecfG+euI4BEa4caJg5MSuFqXhnuOQGUZmbqy//eTgVz7xykd+uogXAPH4" +
                                          "azG8no+5xOD0A6fIz39t+Vcvf+cz3947irGzCTgx06nr6GASF4cZ0MRyfM0t" +
                                          "DPJYAt0/d/Xrh1rL4HADgl2fu3hhqreA47wQLffK/u5EKJIKSHT9DuF64hS/" +
                                          "qX/8299/o/z9P3j1tki91TA9Lbyx81AhVQbI3386ixgttgFc9aX+z1xzX/oB" +
                                          "oKgCijqoCzEfgTTObjHjAfT5i3/9h39039PfOgvttaErbqAZbS0/cEHZTGxw" +
                                          "RtugAmThT71vV/bWl8BwrchNqND/rTtxirS++9gQXAAOxo/+/ce/+UuPvwzk" +
                                          "YKHzqzyGgQQnrNVP83eFX3jxEw+94fnvfrTwCSiy8oef+Nei8tYLBk8U40/m" +
                                          "Q2nnsXz6znx4Vz7sH7rpwdxNUlEHOS1OeoHhgHcFo/DUjywdg8jxQLStDg5C" +
                                          "+Jl7X1586h8/vzvkTteJU8Dmc8//4g/3P/b83olXi8dvO91P4uxeLwqh33jk" +
                                          "ykd/FJcCo/0PX3zm93/zmY/spLr31oOyBd4DP//n//PN/U9+9+uvUaHPucFh" +
                                          "UOYjcsA2/8Je37HJlb9hqnGHOPxwsmIia13MPCuFeziwcSZkHZzb6M4wsofk" +
                                          "aLRsLulMa+jKNsBcNlMmLGti6NTD55aB9HF+20gWbZkK7PW8IbfbrLbgl7DS" +
                                          "Hs9GTtgiR06ZWnSdSA+bnNgWRkQswTDV1TpCy6oOlUYdjdG0llhmZzWMlliq" +
                                          "uqvVykLhsWauyrymjGq0JynSJK7YUz+SWj4/Sssbq9f1Iz8wK6uBOnJWeFK2" +
                                          "Gx5TdiR3oUiKNk3nLdXoe6P1CNWVjUra6YTVaL/v08Ygy8jM59JeJJMOkoxs" +
                                          "hEZqSDV0aDWYqWPE6NSJucsbLGObJL0We3Ft2xNUasZ4nrRgw8W2biIZw/uj" +
                                          "Ka0nbL8+7KilDk6RLqsOXSrpTtMyq2i9ydAOfZbWqpMlym7WEdNPVDZ0tlLk" +
                                          "rAS5juIWOTa2DaSRrc2WYsJYCUeXmIyHMxYfxePyfIsyvoekk24Z5RdsZWP0" +
                                          "2357NQpKUqWDxU6f4np2h7MpjdBaaosMJ3SlSzZctFd3gmEyFxmSzTSGKMut" +
                                          "VBQGIs/obpQhesb6k3bTg8nErVokEvQqGjaWx+WsXl8MPczlFTMqyZ05woU9" +
                                          "c912CaOpCkKHFkSmFyxJfWr08IhvtBRJLdPrdjZDl7QXlzAmNaqIJE5GTFWA" +
                                          "9VmQmmvcGdFW0K3OHEQf1Yf9ZUmVMYHFrEbEhcsyyU14m5ssqZqxZoRt3GsR" +
                                          "mbKUBAOuiaGnNMuzEdZqNsQYZRbVMkGIlTgassPEW848p96harIeTtxu5LY9" +
                                          "osL1u0I/jIU1uxGsCaJ2liVj6SDDVhzPs4UaYMlwXG7KnI2Q4nqoMpI59Cmy" +
                                          "ayJ90YmH/jbdhGxWqwCxFtKkyfNJv1dh6gxDLnlGDX1Rn6iVTquGND2ttO0Y" +
                                          "JnifWtjEDLXLc3k+tErW0CDLdR5Fw37Z3E7tVNWrQjQU2/iUYyQ4VWCnRPRC" +
                                          "uTvox3K5Oas0/FTbbHil4Ud8SNiZF+j6sG9wJKbBGOOj27hW2g4koyuyEqJN" +
                                          "lUDedHulrVat2rFfXdczxyeWnlpe4DEssKlad6Nhc0CL6nBZMruiarIcvdhg" +
                                          "cpfjrFLTqUYE4aIjQhk0u0lEol3a4XhDtrOmRLklacY3xGCONXnC3vRkHulu" +
                                          "smZ/HKhuiKjV7VTDEW1WzYZEUpJ7xJQt8eZAYwJ9tO07dbdLCyQyGk+7m5EU" +
                                          "b7tDnpL8ZYVoLrKhtDbn5dD2tqvGVCBHCcp5mtRpbht1g0Or0tKbqn3foutG" +
                                          "0pv6+BYXVtW+K6sTKsJWJLloe+OF29tU3DBUeo22prIsLQS+Zk9Jee70iU2l" +
                                          "GZSROj6nMmugRBjCEwqLaWskUEpRvJojpALPJq2MGZsTS1Eos2TIAxiek2zL" +
                                          "oxmt5ZfjQPFIh1MpZoOzFlaxraUONCb94WrQBN6UrJVFt9nurDUS8cmQ73Bz" +
                                          "khaspC0GQ7UB42Y0XaEVtI5qm9C3uwK5QqiA9GbA9cRKWC9nLol4q75Eekht" +
                                          "C68lHRCF7TaNtklWnsI2Cxsksgrx4Uw0NsOF1anP2GyJKVh1m3TncHkiN+fK" +
                                          "ksGZdDpvwHq5V2+YWGlZH+A1M1y30oFPczBeqcLD4QpNGl5ZDEDIbQmVT3pc" +
                                          "nx9mpGqg9GQxLlcInq43Fjg6NxrwtCaUfUfs80ZnMF91A0c2iR6+blW7naQE" +
                                          "I2i8plBHbI6aZZVgxvU52tcmzXAuUf2swXkoQqV8lYudlOpYs03A9I2pkFV7" +
                                          "hmzBSjYolRsWHtbHY9Vs91hxPOdnTaymCyUqIcwN6Q1Wc46rI3V4GzUzeDh1" +
                                          "BBfzmjA606LarNQXhR4pzBdNnVMEpr0NiSXNVGsjo1FRTXpb6Sj1JQyzC5Ge" +
                                          "yAjRxshAblHhDGVsw7Iz1xZ0yVk21UxIGK/tRTM55bKmy3kNeol3/IT3qRkh" +
                                          "haS1tUSnJMJbvus3MqPeJHW5Wem2FjDXM5p8Z9vBW5HToGZ8thmqpQ0znQdy" +
                                          "uymTMyGyWk4n02OqGYsJPSPVvp3Crr9tMLiyirgWXl4uRpUJNWLLdb++pfqW" +
                                          "1S9XTbM0kAbVietVJVrG6HV9Ii6opIHY4Xagt3Bl1IGXWKOqleJl1CBdQloQ" +
                                          "fqVi+y2f6qCwKCwFN2x4C2weWwjrM1WHahrsiEA5RlENxReYSbVcm2HieIHR" +
                                          "dCrWMa6mVmq4ZS3haGEZZiol/WhaWovRKmkyCi13sozu8WYvm68ajcGIEwaG" +
                                          "jeB9axkpK2Y04KkqJa7LwraJMoRCLY0pqoYIlsLWaGDN7XVJL4+kUU1sJrxX" +
                                          "soft5aZFDLrCRK+nhCwr/mRdWvbbYUJh3UiK1Oo0jikxtYiGT1tR06ZEL2qk" +
                                          "1YE1WCl6FqWb7TaR8X572iJwDO+7G7syRQcp0p6rNWQ9KXMrTKjIUTo1RqzS" +
                                          "9ZceLfm21vRQnl3LTdMXhqk8FmFMb9HSWlAI0jLElue7ZlmpU/7cyMwFDY66" +
                                          "0mi68IR5SPDjrsu6vCR1qMVsPV6YDEsHIuLXF3XZTrDIpxeTBZFmTM1mhZU7" +
                                          "psjUCyvl0CyVpjRiuAyO4tXxRNnWe6GqYAY6xp3lsoYNNbzL0H6HMzm5x+Cw" +
                                          "Ao85vKyJluhXutVpU8Y7qxHS3BJehxdRMY0U1FzIsbqaYlgNkyxlnNQouQ3c" +
                                          "K0Wd7VLpSOW24dRarNmhaAlfCM1Nf6UY7iQLMNgw0fLGZC1rww+3PWsAT9Cw" +
                                          "3ogSbIOXwC3DHI5tgse7C1qidFm0bMTslRJ62u8hSJvDOukaQ+JZEBGkgdlj" +
                                          "g/PGuirPEcW2jXFfGs2ztjRoVKN0u8S1rkAxnaqEDtwxKrRn4ca12hkIlzI1" +
                                          "XAmduCunC2M0a/NmtS7wNpVWRjyugesuiHuHGxglGA1L2mzRXfY2VneVKBVq" +
                                          "PurNuVrUpuYOQoGrSS1Ila5bn8ZqNpslk6wO1xFMSzSGNBY9KVhVl0mnxqR9" +
                                          "2FEkFJhcFJi63BBNDWd7dgu8zL7nPflrbufHu2ncU1wIj/qF4IKRb5R/jDfs" +
                                          "7EcxTKBL2jROInANS6DLRw3MHfcTHZEzhxfQ0p06MMUN3dFPtmDy28ZDd2of" +
                                          "FjeNzzz7/AsG/9lKftPIGTSBEEkQvss1V6Z7C/sIeurOt6pe0T097nx89dl/" +
                                          "fnD4Xvvp4up/W0eGg67kmIO8SX3UjH7klJynSf5W78Wv0+/Qf3kPOnvUB7mt" +
                                          "r3sr0o1bux9XIjNJI3941AOJoMduu4oFummkkXnM96m3a1+++ZVnru9B5042" +
                                          "h3IKD51qtbzBCiJPc3MGh43kK+BaHayPV072XQ4j5GHwPH7QaSy+8903hfn4" +
                                          "5uw4zm4LoL2jiBUPwiWC3nF85acC1zX1wurXR75X3JC1qWvm7bf/vvpE5cv/" +
                                          "8rFru/ujC1YO3fDO1ydwvP4TJPThb3zgPx4uyJzR89b8cRPjGGzX733TMWUi" +
                                          "irRNLkf2c3/20K9/Vfv0WehMBzoXO1uzaMBCBx3BXCi7UFsvxtmpvXk+3Eyg" +
                                          "u2dmUsR90YWMDlPl8TulymnYIoWffr1L8knuWd4bu63lmav5wG1/quz+CNC/" +
                                          "8MLVS/e/MPqLIpCOmvWXOeiSlbruyS7difmFMDItp1D28i52wuIrTqD776Bd" +
                                          "3toqJoXQ0Q5+lUDXTsMn0Pni+yTcJoGuHMMBUrvJSZAPJdBZAJJPn8mbgSeq" +
                                          "xEGpK8x57+uZ8wjlZDcvryzFn1eHVSDd/X11U//iC2z/g6/WPrvrJuqutt0W" +
                                          "f3Zw0MVd2h1VkkfvSO2Q1gXmyR/c/aXLTxxWvbt3Ah/n2gnZHnnthGh5YVKE" +
                                          "8Pb37v+dd//GC98pOlr/B5WV42RVHAAA");
}
