package org.apache.batik.dom.svg;
public interface SVGContext {
    int PERCENTAGE_FONT_SIZE = 0;
    int PERCENTAGE_VIEWPORT_WIDTH = 1;
    int PERCENTAGE_VIEWPORT_HEIGHT = 2;
    int PERCENTAGE_VIEWPORT_SIZE = 3;
    float getPixelUnitToMillimeter();
    float getPixelToMM();
    java.awt.geom.Rectangle2D getBBox();
    java.awt.geom.AffineTransform getScreenTransform();
    void setScreenTransform(java.awt.geom.AffineTransform at);
    java.awt.geom.AffineTransform getCTM();
    java.awt.geom.AffineTransform getGlobalTransform();
    float getViewportWidth();
    float getViewportHeight();
    float getFontSize();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028785000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVaDXQU1RV+uwlJSID8AAGBRIFATxB3BfyPWJOwkMVNsiUh" +
                                          "1KAsk9mXzcBkZph5m2xQrHiOglX8QfytcuwpHpWiaFurPf6U/qhQ0R4Vf6j1" +
                                          "tz0VtVY5HmtPsdp738zuzM5uFiRszpmbt/Pue+/e791737tv3q5PyShDJ7VU" +
                                          "YT42pFHDF1BYWNANGm2WBcPohHcR8fYC4YtVh9rO9ZKibjKuTzBaRcGgiyUq" +
                                          "R41uUiMpBhMUkRptlEaxRVinBtUHBCapSjeZKBnBfk2WRIm1qlGKDF2CHiKV" +
                                          "AmO61BNnNGh1wEhNCCTxc0n8je7qhhAZI6rakM0+2cHe7KhBzn57LIORitAa" +
                                          "YUDwx5kk+0OSwRoSOjlVU+WhmKwyH00w3xr5TAuCpaEzMyCY8Uj5v4/c1FfB" +
                                          "IRgvKIrKuHrGMmqo8gCNhki5/TYg035jHbmCFIRImYOZkbpQclA/DOqHQZPa" +
                                          "2lwg/ViqxPubVa4OS/ZUpIkoECPT0zvRBF3ot7oJc5mhhxJm6c4bg7anpLQ1" +
                                          "tcxQ8dZT/dtuX1XxiwJS3k3KJaUDxRFBCAaDdAOgtL+H6kZjNEqj3aRSgcnu" +
                                          "oLokyNJ6a6arDCmmCCwO05+EBV/GNarzMW2sYB5BNz0uMlVPqdfLDcr6NapX" +
                                          "FmKga7Wtq6nhYnwPCpZKIJjeK4DdWU0K10pKlJGT3S1SOtZdBAzQtLifsj41" +
                                          "NVShIsALUmWaiCwoMX8HmJ4SA9ZRKhigzsiUYTtFrDVBXCvEaAQt0sUXNquA" +
                                          "azQHApswMtHNxnuCWZrimiXH/Hzadv4Nlyktipd4QOYoFWWUvwwa1boaLaO9" +
                                          "VKfgB2bDMXNCtwnVT2/2EgLME13MJs/jlx++cG7tnr0mz9QsPO09a6jIIuKO" +
                                          "nnEvT2uuP7cAxSjRVEPCyU/TnHtZ2KppSGgQYapTPWKlL1m5Z9lzF1+5k37i" +
                                          "JaVBUiSqcrwf7KhSVPs1Sab6EqpQXWA0GiSjqRJt5vVBUgzlkKRQ8217b69B" +
                                          "WZAUyvxVkcp/A0S90AVCVAplSelVk2VNYH28nNAIIcXwEA88AjH/apEw0uXv" +
                                          "U/upXxAFRVJUf1hXUX/DDxGnB7Dt8/eA1a/1G2pcBxP0q3rML4Ad9FGrIqr2" +
                                          "+40BMKWuJZYP+dC+tLz1nECdxg96PAD3NLezy+AnLaocpXpE3BZvChx+OPKC" +
                                          "aUho/BYajMyEwXzmYD4+mA8G88FgPnsw4vHwMSbgoOZ0wmSsBbeGuDqmvuPS" +
                                          "pas3zygAO9IGCxHKBPezqfxHIcqWttjwVSQZtyPizlfPfu3+m28bNO2wfvgI" +
                                          "7Wo3+b/tcs9VH/yH6+QMuTj2qCw+4mrf7d9195TmCz7h7UdDdGICWBM4fq3b" +
                                          "U9OcC13WjTUEXbvf+Tv7v/TOKHrWS4q7SYVoRfQuQY7TDgpRtVQykmEeon5a" +
                                          "fXpEMt2vwfJ8Rqa55XIM25AMn6h8iXOOoYzcWB7L7aWS80zAqcG5+h480y0/" +
                                          "4P+xtlpDOinBZ72SzzqK5AuCOcSoXvXBvTu+2rjpHIAuSEYNoOiASoXN1xbH" +
                                          "heOaXbfWlG177zqcWS3Z9Sy0I/fMoOQLO7R73nzpowVe4rXXgnLHIg7oNTji" +
                                          "D3ZWxSNNpW2WnTpFlN++I3zLrZ9uWsltEjhmZhuwDmkzxB1YTGFRunrvuoPv" +
                                          "vrPjgDdlxwUMFuB4D+xjoGDwtZGBZJIiyKaFT/gW/jzwfIMPaogvzGBS1WxF" +
                                          "tFNSIU0Dd5sQDixrDrR1Ni4JRBa3t3VGOoLdAZBwhu0iuGXqiPcYLKxL/aDq" +
                                          "gBXU54dXi5vrwn83HeWkLA1MvokP+Ld0vbFmPweypAf2bZ1JA3Bskhr1mLVR" +
                                          "QFqB5IyEkdMBXfL4N1S9u/buQw+Z8ri9zcVMN2/78be+G7aZEchctmdmrJzO" +
                                          "NubS7ZJueq5ReIvFH+7e8OQDGzaZUlWlL0IB2GM99Pr/9vvueG9fllhYABsM" +
                                          "GGS8bU+Nui4MYZRLbHyl5s7nhXsK0OQLDWk95Sbt4YbCY2P6fJhaL7q2/Kmb" +
                                          "qgoWe0lhkJTEFWldnAaj6e5ZbMR7HBNk7xlsl7X0R+OCWDxH08zAD6PWDTNb" +
                                          "jr1lRLzpwOdjuz5/5nBGpEz3r1ZBM+GuRDIb4Z7kDvgtgtEHfGfsabukQt5z" +
                                          "BHrshh5FWLSMdh2WmkSaN1rco4r/8rs/VK9+uYB4F5NSWRWiiwXcBsJizvpg" +
                                          "59gHq1RC+/6FZhAaLAFSwZcRwi20NjNgzbAC1owsAQsLyOPBQiv/OYfT05Cc" +
                                          "bno2FuchmY9kAVf7DEZOcnhnVzCwIty+rDOyIrioswUZzjVRR7oESZsZBZZ+" +
                                          "F8lnWpLPzCG5FwvLv5vkU7JJ3hIILmnpzCZ613GIXmeJXpdDdC7epd9N9MnZ" +
                                          "RMewmE3wVTkET+Qal5ESAUKkDpbHyOhUJmEK4divELT7muH25DzE7Lhq2/Zo" +
                                          "+33zMMRgw+9Dh0zVTpPpAJUdXaGD1qRtfVp5FmLvFd4et/Vvv6mLNUF8CJEq" +
                                          "EC0uyBg9IDhDLiautdKVMRjE7Rz4FEcOjMm7roo0CinYcLmw1UuJOkB1fA+r" +
                                          "kKOHZLTCjc2c4YO/W/Tnr/p4SucFfav5KpOx/YJkDVuGMU9N5aMnu1B1d/lg" +
                                          "6659S2aLW708RTM3PRmpXXqjhvRYWqpTyEUVO3rCwpqxYrjQiohzThEeizy9" +
                                          "oY7Pgr0TxB6mu/ZVZb2q3i/IOEAS1lKIYeqg/ca1ySpNxql6y33q3e5jW3iG" +
                                          "6XpTLhOzDFUns+34CtmRDFtERL1uuQJTK/VKQo9MccH6unzWvMf+eUOFuczJ" +
                                          "8CY5DXOP3oH9/qQmcuULq76q5d14RMzO7RXDZsOUD/tv4j5p+hH+3sDfDmWt" +
                                          "+xGSOPh/jLKwlKDyckVinWqrJMsSZOfUNNyzrbUf/53nKF+AWzFYS1iqb2st" +
                                          "xp+BhB0xBo4W6pxyZbzA3ePJ2QEL9GuM7w3WPzHpV+ffv/0dvnM0cVDS578a" +
                                          "ntOt+T99RPM/PJw356i7Bcn1jIxJQg0wt+K7jTZOW0aGE764zq08bz4JnnMs" +
                                          "5c/Jk/Lbc9Tdi+RORopB+aYm1ZR9Miz2fFqFQeaLUUh5l8G8Qu4i0/mLbFDu" +
                                          "ygMo+JDZ8Cy0QFmYJ1AeylG3G8kDkKYAKB0iZE1Kpy4oBoa3JD416fg09kLm" +
                                          "Q9O5OEYP5gEjXueHp8nCqOkEYuQIFI9yhqdyAPUMkscBKCM7UK6YVDigSlEb" +
                                          "myfyZT9T4Ala2ATzZD/7c9S9hOR5yIvBfpo7eSx51FZ7bz7dpt1Suz1Pah/M" +
                                          "UfcWkgOm2yyR1R7YCiStwQXBa3mAoDQ588stCJbnCYJ/5Kg7hOR9RioAgi6J" +
                                          "DmqqzlZIUfOA1bGefJAvAKbCs9ICYGWeAPgiR92XSP7FSKUDgBYqxfqYC4HP" +
                                          "8oXARHhWWwiszg8CHpKjjvdzhJEyQGAxbJc7pPXUpfvXJ1p3frKW/ait2n1m" +
                                          "6uNfzVLHJMeFRfJkB3/DYug43DTH4ECMywFSlSk9FkfzF+XZBeHr0DxTBmQb" +
                                          "iwSPYDzjIbzSdZASGtlWmuIeVZWpoKQwh2GOgnl2QWuGgx8rq5FMQjIFyTQk" +
                                          "tWnTk1LwRFjdzBx1s44RUHu8BTaqM5DUIZnNSAkuWmgiGQk6P0Z1fIF7v21a" +
                                          "qbo2XGmeJuZIj90Nt0jbX/zTl+Ubs33V4F9vrabudgffLJhfxupu5Gl1Ieb9" +
                                          "qEIZpKEGcmLyP+yXYN6XeYQ37qhOM9F2Gj58ymeSFl9uWzxnQOzmpR90JgGL" +
                                          "iImJnRPqx/zgPVPd6UfBKSIG+yMdjx3cdBZPK8sHJENi5kUC89t9ddq3++SX" +
                                          "poa0b9pZkYyIh3Zv2Tv9467x/GOlCRoq1GIlqBdZzuHhzuEl5uHt1DSdLDl4" +
                                          "JhwR98+Vzi7564EHTdVmDaNaepvL7/7mxY82vLOvgBSFSCmeZAg6jQYVRnzD" +
                                          "3QZwdlDXCaVF0KohRMaZrSUllpwFtIaq1NvUeQYjpw3XNz+7zzwkKpXVQao3" +
                                          "qXElit1Od52lxDXNWcvtqvz47eoKncw9BvBSulvrG6niuI+zrREP8Z2VGiPj" +
                                          "m0ONHR2RzovDgUhX47JgY1MowO0VP7l4OocP4sbwM7pCkqPNgh41/fK+b0fP" +
                                          "vHDSvvO4X2YCd6LB4rG3POH8kEoSI4707bkifT0SH5IQkjYk4fxF+uU56lYc" +
                                          "59KJR92eLiQ/hCDfJxh9zWqU2/PCEWMXyYXdSj4Gli5BsgrJ6u+GnX06HoNl" +
                                          "XxHwo9ZRQezNUdd3jCDaAy9ArqgNJyLniSGRUCSVSb1DWLlnxGBmHhY6wOSX" +
                                          "XPZgCXMqD17i8Kw7bjAdOuUQaCBHXWLEQMaRDCIZYmS0CWSjLJ8YLK/MheXl" +
                                          "KSw3IMEjV8/G/Dn1NTnqNh+nU1+NZBOSa8GpmWpe1MoS0h0VI8Fzay48r0ey" +
                                          "BcmNSG5GckuebfOO3JlJbfr1DF2Pa7CXCiREquE5Ne/irhGb8O1I7kRyDyOF" +
                                          "g4LEToz17siF9r0p6/0pkp8hue/EWq8TTPdRnqwqvJFnZ/ZGWPUTzrB7JKnJ" +
                                          "g0geRvKIrfSIgf31sQH7SySPIXk8D2bsTWnt+Tm+W8hFcx+3ZsD5zIjN9Ukk" +
                                          "TyP57QnE9Nljw/T3SP6I5DmrPsFIqX2dDr8pTc64m2veJxUf3l5eMmn78jf4" +
                                          "x8jUnc8xIVLSG5dl57UuR7lI02mvxNUfY35/5Gcfnn2MTB7ufh8jBUB5WrfX" +
                                          "5N7PyIRs3MAJ1Mn5Zwi8bk5GRvH/Tr5XQG+bDzYRZsHJ8hr0DixYfB02vp7s" +
                                          "O14y8Wgz5vh6P3PYHLE1bt6Wjoi7ty9tu+zwWfeZt81g271+PfYCqVWx+YmX" +
                                          "d1qQkcw6e0v2VdRSf2TcI6NnJe8DVJoC284z1bYhch1YuoYWMMV1y8ioS102" +
                                          "Orjj/Gde3Fz0CmTHK4lHgPxmZea9wIQW10nNylDmvaNkKtVQf9fQBXN7P3sr" +
                                          "eQHPk34X080fEQ/cf+mrWyfvqPWSsiAZJSlRmuAXFhcNKcuoOKB3k7GSEUiA" +
                                          "iNCLJMhpl5qyZ6pj0zJVRmZkXvo6amY6NkTK7DfmzORMVrGB/caaSqSLzBCP" +
                                          "swF2Fwm1aloyG/OcpXFvDWSJSyTAbfVDXsTSof8DBH9kOUcxAAA=");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028785000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALV7C7DrSHWg75v/h3kzb74MzDCfB6nB8GTZlmXvAEEfW5Yt" +
                                          "WbJkW7ZIeCPrY8nWz/ragqEYKiwkhE8lQzbZwFRSC5WEJZDNhiJVWVKwqWxg" +
                                          "IVubVGoDW7uQyqZqCVkqULVJtpZs2JZ8f+/Oe3eYefNulc5td58+fc7pc053" +
                                          "67Q+/d3SDWFQKvuevV3YXnRB30QXljZyIdr6enihxyC8EoS6RthKGI5A3UX1" +
                                          "sd86+/c/+Ih555nSjXLpbsV1vUiJLM8NBT307ETXmNLZo9q2rTthVLqTWSqJ" +
                                          "AsWRZUOMFUZPMqXbjnWNSueZAxYgwAIEWIAKFiDsCAt0eoXuxg6R91DcKFyX" +
                                          "3lXaY0o3+mrOXlR69FIivhIozj4ZvpAAULg5/z0BQhWdN0HpkUPZdzI/T+CP" +
                                          "lqFn/8Xb7/zt60pn5dJZyxVzdlTARAQGkUu3O7oz14MQ0zRdk0t3ubquiXpg" +
                                          "KbaVFXzLpXOhtXCVKA70QyXllbGvB8WYR5q7Xc1lC2I18oJD8QxLt7WDXzcY" +
                                          "trIAst53JOtOwk5eDwS81QKMBYai6gddrl9ZrhaVXnOyx6GM5/sAAXS9ydEj" +
                                          "0zsc6npXARWlc7u5sxV3AYlRYLkLgHqDF4NRotKDVySa69pX1JWy0C9GpQdO" +
                                          "4vG7JoB1S6GIvEtUuvckWkEJzNKDJ2bp2Px8d/CmD73D7bpnCp41XbVz/m8G" +
                                          "nR4+0UnQDT3QXVXfdbz99cwvKPd94f1nSiWAfO8J5B3O59/5/be+4eEvfnmH" +
                                          "86rL4HDzpa5GF9VPzO/4k1cTT7Suy9m42fdCK5/8SyQvzJ/fb3ly4wPPu++Q" +
                                          "Yt544aDxi8J/mL37U/rfnCndSpduVD07doAd3aV6jm/ZekDprh4oka7RpVt0" +
                                          "VyOKdrp0EygzlqvvajnDCPWILl1vF1U3esVvoCIDkMhVdBMoW67hHZR9JTKL" +
                                          "8sYvlUo3gae0Bx6ltPt7OAdRaQKZnqNDiqq4lutBfODl8oeQ7kZzoFsTmgOr" +
                                          "X0GhFwfABCEvWEAKsANT32/QPAcKE2BKE2rfhy7k9uVfM8qbXKY70709oO5X" +
                                          "n3R2G/hJ17M1PbioPhvj7e9/5uJXzxwa/742otLjYLALu8EuFINdAINdAINd" +
                                          "OBqstLdXjHFPPuhuOsFkrIBbg4B3+xPiT/aeev9j1wE78tPrc1VuCj97oPhx" +
                                          "E+j3xJWDcCePAHQR9VRglA/8X86ev+cv/0/B6PE4mhM8cxnDP9Ffhj79sQeJ" +
                                          "t/xN0f8WEHIiBZgI8OaHT7rfJR6T++FJBYJIekS3+inn7848duMfnindJJfu" +
                                          "VPfD9ESxY13UQai81QoPYjcI5Ze0Xxpmdj715L47R6VXn+Tr2LBPHsTEXPgb" +
                                          "jk8cKOfYefnWwgjuKHDuAvouJuDHwPPovnEX//PWu/0c3rMppvKuYipzli7Q" +
                                          "YI4XenDuL3/lE//wzPuaQHV06YYkZx1o5c4jvEGcrwb//NMffei2Z//iA3nY" +
                                          "8A9IP5obx8mZyTl/s+h//Ov/6a9rZ0pnjgL82WNLJtDek8eCSk7sbBE+7jqy" +
                                          "tVGg51r+77/I//xHv/u+txWGBjAev9yA53NIgGACVkiw0rz3y+tvfOubn/iz" +
                                          "M4fGeV0EVtV4blsqKITFghcBzixXsXdme9cPwd8eeP4pf3IJ84pdhDhH7Iep" +
                                          "Rw7jlA986B6+LRDtwQij2hc73GB0UaTl9ul2zweWAyRO9gM29PS5b60+9u3f" +
                                          "3AXjk0Z+All//7M/88MLH3r2zLEl8PHnrULH++yWwcJSXpGDygZw9+hpoxQ9" +
                                          "Ov/zs0//3q8//b4dV+cuDehtsF/5zf/y/7524Rf/4iuXiSvXgcW6CE9gpPNX" +
                                          "0MOxHdBF9SN/9r1XTL73+99/nutfajCs4u8EuSMHj+WC3H8yLHWV0AR49S8O" +
                                          "fuJO+4s/ABRlQFEFoTXkAhAQN5eY1z72DTf91y/9wX1P/cl1pTOd0q22p2gd" +
                                          "Jd+sgCUnMsH+xgSxdOP/+Ft3XpXeDMCdRbArFWbzqud74GP7HvjYZTwwLzye" +
                                          "L0N5ASt+vq6AT+TgDTtTzYtvzMGFHECF2JWo9Mpj5jah2xLPCaOLEk2OujlC" +
                                          "Y6f1HD6ZA3xn1m95MZw/vs/546dwfiYv0C+O8wcvx3m3TVPd0eVY770E1s/v" +
                                          "s37+FNYL9oYvjvUHLsd67ueXY1x4QcZ3Xri3B2JP9QJ6oZL/nr04ju5f2ur5" +
                                          "g4A0Aft04CznlzZa9L83Oh66d5vbE0xWfmQmgY/dcUSM8cA++QN/9ZGvffjx" +
                                          "bwHX6h0sFjk20Pre5N2v/dtitzV/kcaRyyMWWyBGCSPW0yxwPtAORaodYxqN" +
                                          "wObPuwqRonse6dZDGjv4YyYKOR2OYWFSjlO7J9JkE8MoXKA72GiD13Bjy0s9" +
                                          "Ll2xk0FojU24j4WrljPNVHwl+ybiVDfDoGtxC3vaHBrbSI1Tv+tLltKJA95o" +
                                          "jKG1OawI9YnRWMJRVplEkxnSdSI+1Hy01szijEXijiWEme/MI4iP9TKkoy0Y" +
                                          "raFRUlsj/FY0yR46Gc9G9arf6ZIdGJ9JA2xAOVUJV3nP7KpC05gR9Vk0MVsB" +
                                          "15L71nzZj0cZrggqtbC247VQh+Oxxfq4yY5Xgh/ZbWUjTCwXj8ZdnFB8canL" +
                                          "fdzFjVVVEmgHXttUn+xUia7Vn2AO14DxgTugTDhtmwOCGG3Uittc6ujaNDGZ" +
                                          "bgTKiq2Uq2pXR/smnrkIytCcYEWYMhuT6QZZrcoVTkwFT+SW9mRclkynn267" +
                                          "lUpa2wTICIsJX2ln7JaYNcdLJKlDKtwxcFpYJH066MfdgGKdtddcEANzZSHQ" +
                                          "aLao1JBld+4QHRpwO+Pk1dwfqjYGkdy6O5R5pWqnC2hirTd8PJ8odU6E5LFP" +
                                          "r7w2wY8qWSLgnZoXoV5PRRzT3PSchlqfL1DF9ZkhHKmbYVOTR5AWxVN4urHS" +
                                          "nlhb1fo9ZUxuhA5OYAqpYdwiYsrdxkpeDtrrZU0RxIXqxh7jrbaDXkNpKAFJ" +
                                          "OA5BpFwFKbfxCUQNlCBjpWo4wxF8kFVi1p7wa81gSDVoDBR/2nH6CwWVonXD" +
                                          "NWduyhO+3Kd7S71fJzVpXOnDFb9v96hRTYRFLpI1HMuGEWMZ4bIODyaiSYcY" +
                                          "M3YkxSJSj502u06vLmItWeib1iIDhjsbRZ2AnOBTImkr2DCqhOPpYB1jSjbs" +
                                          "Yn6YslF3sHFjQpLzzcC0C3UzRUvqA3u7iixfqw+5mdeRpHGSpgo89xRG4VqT" +
                                          "vrHAq3OSnQ6IKHUnoypUbS8Ytg3X2F4ILe1NuaxSaOQGFSdrDUOeq7SUxpKm" +
                                          "4z7nuu1kVI1jHlWxjbgUJm2e2I6hkduN5Grf90VqMZwp/oiX+jYDO4jcsrMO" +
                                          "XEZWNdTqKRN8bIlrNUgNYHPihA9hUZk32mt/OJWwCmWJy7XQi5AE4C0ye9UX" +
                                          "hs0qjM4bLVySsfE22UxWqg9hFbFVwSbEBPNtUbcnq+pkMOtWm+4Ao2l1mrax" +
                                          "ZhNbdsGJrJ1W4mkyhmJ/usE6wqQ3NmBzOp5CJLmhXBwloyakY7ACwVTVV/EN" +
                                          "X1nXApapY1qrQwX0OqiW6xWc7UtxT57xZY0oR0wGu21C2yxaDR4jawNGz7Zl" +
                                          "zGUUT/WnfruGywlhbsoc3yeUselB+ExZstt2Os2cGVkvO1iTajY7C94N03rS" +
                                          "TVlxvvA4uZI6YojPdSom104S86KvhLVsu8C4Fk0Rm24f5/VsbWy6tLqWomiZ" +
                                          "TsShHG15K7MN3ohrZafanA+4amokCxqVvFp5DkVq2Jp0oW23UR6y8WhZXRNp" +
                                          "ue4EBqq14BYycogMNdGxRmoUTUg4WzfWtfm4xakEXJOWo3F7Ok+M8ihBE2jE" +
                                          "9buBJNbXqDibeIIxjIczdEQufCGaDLcrp617LqIYQH42qiap0WsKawVBpjRb" +
                                          "RTDWbZhNa8px3ixTJRxlUEUSm5UMW6sUUjbrzcq2AtX58iayfZID4U1Gq2KW" +
                                          "rfsIiDGcKnrTZIono7hcDZZ+l8ZisT0beJyFgZYBvJl3TZ1TpnNDsikYRbO1" +
                                          "Kok1uSVuKzRksB43ZDhUQGtu5nvpRK8H0+nCZbr0AvUGo6VF1mRpIw4GvlSV" +
                                          "3JHfsQflMl3LmEBuxVJoR+2l6chmnJLOKtvg8GxEdYTYDZLY45Mk4JcLUrM3" +
                                          "6ZjtxHidLG+WHkWmkUzhco+2tn2lM4IWErTMUoNmecVbJBmFi7C06USdgUiP" +
                                          "K6SGhEPS2gRkIMADq94TcKUW1SYU5zEaJuOpGVesmJquLV6dMf0NAynkeoFP" +
                                          "x0hdm1pIEqRus9bVpRWDwWzirfgyo1WSecfhU33rY0Z1LsM9rIaHKzOAHWYi" +
                                          "DDtrHKG37ZXG4lODqQ9gsRVD83iYluVmYLUydcIOqhDanOtlClXktmqqkaM5" +
                                          "QS/jBvFcROVerK8RQaeTTreM6k1uSFKZIo9tyWYqNF6l2FaLD6BWksQ61TJs" +
                                          "25xheMhSlNicj8uD2KqzM1lg5t2tjYSoa07DfgXMESmtWog4j+qzOTGr8g2j" +
                                          "ZyoMuq5CfWe+XniSXrHNVW/U7ki25mLKsqEj8pwV0C4+WKEbO7TRaUUoc4RE" +
                                          "brqVZoaRDV4iR4P5MoBtgcn8lNOWcYZAiItTfjurBbCMs2UqFkh6XpfRFZks" +
                                          "okXU7hqUESrzeDWMkAzvBqFpIh2JEVnNrErOSlQGcKB69QBqBuDk32+V4xle" +
                                          "7yADURIky0qnKh72rCzxF0hr0V3DAlGGGh3ZxBQG64iprAqpVa0MloNFNscI" +
                                          "2EtDbBgyW47Hh1YCcTNjVEEIde561U6sms6stcImBkq2ZU51TXeSESkdbcsB" +
                                          "yW3pwPLCdCxny4kgoF5blEMZl+Vyp2m7ks/wGUEhnTRhEiRZjdFer2bSNOO4" +
                                          "fkbIDbhG0VNH70194PsEqvtaa9BiXVlg9dRp19LJaNUelYeKjbRFbNxfkT6Y" +
                                          "Lc4c95x2v65ZSZsZoU7crSJk1kYZE0yS7JVrtYxlhUVabpFmJZuMfN7HemNt" +
                                          "qlAkvBYiY+IjHYdJOlpdj6BJkjQcZjDuNIlee90mKvEWX7Ro0iQZS4kjrT9h" +
                                          "hWUbFbJ6p61yS9ZBA8+rEJY7Uxknhcdxj1vhsIGVg1Wf68rMiFiqVbU+4yAJ" +
                                          "LEUB5NfFWO0YSoL0fW4DzXorchJT7Lg1QBTWjWEc1iB70WggLbGqMBJaaQoj" +
                                          "tsYLjj+drpdmIsyktT/atscTrhYQqb/ezILl0PLMbGS2dSvbtrwZyi+CCthq" +
                                          "NpwYkifyvLquWRDNtTERtvv0TF8vIFWBt6I/2KztxrZWW9d0ZCnVLKox9UeM" +
                                          "yWVkZ+yG5VqdiByB7ERtgYHjeNgb9YFlDb0Wq6rdRuxmUsIaZX3MAZPIek1i" +
                                          "hpBTjq953Ra0HjpqPGbWaGONaHBdYDMQ6qakHHJjEoqS+hLxy2a3XAtJg3Sk" +
                                          "qLyhRI43oSXTT+0+uVVXYDMprYMeG4oyZ4wHg20WzMcGhNTcfqeMSVlnJsLW" +
                                          "el4No41fxk28ssG9utTwN1t5nmE1ne9Vh22mRcUsmtYkPuv6k7JhJFBFS1y2" +
                                          "ok5IEUGbihtxUXnUagk8C/G9tIY0LBRXXXhJb3rDRSWNyn10OZI5qaJQbbRR" +
                                          "z9aV5jyr91yXDREV6q0gZq62RppVFjjB8/GyMnNgWWixVlY1OuvOUFeY8dhE" +
                                          "bLC0DuO6VYEcZt4h4+2C9co9Um4S28qw48x6MKZvbapGNVfkqj/D+njFkttw" +
                                          "39/WPdxTaj2yDjeMRaW1Ypxhi0O49oxHFu3lNNa7ftMl1tyqPYuHdIdubc21" +
                                          "tsX4MbsKVbxPsOi435hNSGsh2u25szW28qg1qmO2UsVGmUxCqNoSWyYnIFs6" +
                                          "wQ3fQ3Vxg8AdGZ1nqOZHsBhnMK+YEDs2VGm14JzqdivAAjojLDFKh1OwKjiY" +
                                          "Rw6RZjOMiN7cJWY9COkvUECzJVgetrAaPdJZrzNbpscGh8FzSjd6WIL150TY" +
                                          "ookZJekYv7CEVnUq8mhH7I/JBT5bb4w1OIR0+aY3xYSuKUmpFWaLJtH1+8tl" +
                                          "omVmr70dUthm3lNRn5+OfSOZ9mC/ZgR9CVKsqOrCTiMeGNmE6fZYvSMYvRVe" +
                                          "g8hZvKjXyFG33ibYbdoRbXHV6qyMrFOeyrjeDSrkZoQ7w7mVivyMzJb0PBM1" +
                                          "GROpyJacmNYnsuR7/WFqVilu4drVoRRTi00zWCMddrikO9vRcBWBFXsFM6nQ" +
                                          "WWoZvoHDel0Yd+MmPlLWLEKOadkdiNgqlpyFRQ1XDb4iwwbdQZMqrKznXnVK" +
                                          "gSAYy/SyVRlEleV8CmUjuzyeh7XapN5pJQFYCLSFYTA909jEfoxQNkzr89a6" +
                                          "Tct+v02pDrPly9vpbNCY6rNhDZysOLbVqVJLpLl1dLFjgz1EtnGHXOb4QqvS" +
                                          "W1CMRTs9V+DXGyhb8BNea4wNvC/SVHnLastNTdVwme83w26vPbCQ1ZhotqKW" +
                                          "pq1r5bI49T2lMm/58mq2pc2anFRHSaveQDcQxdmE4K1hirbXuCZncdfM4raN" +
                                          "xN0IJkWNIe16z0yFVrM8ySwUadTb3ZE2cUhloOh+wqAQ6mxmzWrCcMkCFzsi" +
                                          "4egytmgsh7OJ4GZkbSinmk1OCWXSqfQ9U2AVORDHtu2nnYhW1vAgGevD2dJP" +
                                          "a9NBVkazLF31/elkqHi19bRtWxHMaUjV3pDTgaQm0TrJ6qju9V01beEJLsZ2" +
                                          "ElAN14rpchYIbb4pVyeUxS+dCjfoClUh8xJyMTandbS3mMGsB05nEx6165yn" +
                                          "8vVwnrKoT6zW/GBh1mHI6JfnFYNPuqSYJFx9Wp0RWoPB6wFV47luc9X2RLqO" +
                                          "VtD5ygKrrdhF6OFqOVvVjU2nHI+Rhj1TkVa/B/xEZ6whZBKk0duYrUxaj6sQ" +
                                          "T7QldrqdTTVxWadsC8HDRdBrxGXKnVYaXW9gTzfd1APnt6GeDcaaVlsSpIJt" +
                                          "W1iwXgx6W8a1REoYE+JEnMOkxNjuhsKdrjlrpJw4nfLygpiyaxJGrWY/RedL" +
                                          "TOPi8VAh8O5UYtpDVhFIgpZnjlghJHHJ9JpgTwixpj61+2Jao9n2ctKEKIh0" +
                                          "4cHIXQ/MsjuGywMZ50SlSfmO5OtAfWLFrEzoZidTtvVmUNG3uOoMRAqh1FWs" +
                                          "zw2Oq/Xs3twIYLJT5RWUmBKW0F7HbWSgQ1ZgUvMmB9PoStiSW66zqDPtkZfB" +
                                          "aGh1WkHFb0AVf+U3zViH2tK6ORrxmuCu03XS67gyJFMSPx5lAY72+m5vUVno" +
                                          "Qv62wBDphVGDw2EXFbciT09XTbI6D0eSC9YNpyw1zY66KdfkkEQyejlojVer" +
                                          "0ZZH0KHbbg3sZQqB4zXfoBHSCfiwQ6+nVY0Mmv5IbdSdaqL3NmOjZiM667ho" +
                                          "c2nUN83l2FWbG3rCALE1G0HHsYDadKXqJJvB2JjVwD6RUg3XrbIjHI0Ns7nE" +
                                          "xzgiBcYUGaD8lhbCGov1YNZF5NRqzlcIJSRdaBQg0yFVnpPZTJCBCzdNEOas" +
                                          "zczAK9XER0MOrm+b0iJDErPB1/hZl2nD86ghLT0LjbatKC5nqWToctSEF1UU" +
                                          "LvPGjFhPpE155kw1eD1cqWlDryTViSaIRnWk0o2B29Ob5KTnEdVmPYPnM1M1" +
                                          "4VnszSSWncDbpuWJcKXKBcslRGl6rZNVCGfU7dft7oLfOLKutFJ6KMEVd7C1" +
                                          "SSdRBqs+ONAZLWOIT4GgtTDQh11+VatPK82K0R5CqlF2AmlrJGteEkMLk3ui" +
                                          "LTgxNu2Y6qCvxh7Xx2srlBLbYwuzBgTTY03fRtZbueEvK1lvIjjyapp4DcWZ" +
                                          "NQarUR8lDSfjBHYSUDjYLyniWmQynODDtFPtpA6s2N6Wgjhwtu4kpCT2xO0I" +
                                          "mxsTchqORM9okni3teLG6gbDsDfnrwqdF/cK867ilezh5YOljeYNb38Rbyk3" +
                                          "pw0YlW5W5mEUKGoUlW45vA2xG/1YzrWUZ0UeutK9giK184n3PPucxn0SzlM7" +
                                          "eccmIBh5/httPdHtY6TuBpRef+U0FltcqzjKk/7Re77z4Ogt5lNFvu95+Vum" +
                                          "dGvek89vrxzeUnnNCT5PkvwN9tNfoV6n/tyZ0nWHWdPnXfi4tNOTl+ZKbw30" +
                                          "KA7c0WHGNCg99rzcl6fqWhzoR+O+/hHlcxe/8PT5M6Xrj6eScwoPnUjM3mZ4" +
                                          "gaPY+QAHN0xujczAS49qTmRpbz3ICz2xn6544mS64shmnmcMZw6tL9mf+qD0" +
                                          "uqN8FuHZtq4WWj8/dp3iNboyt/U8Wf+P");
    java.lang.String jlc$ClassType$jl5$1 =
      ("Z18Lf+5/fejOXcLOBjUH0/CGFyZwVP9KvPTur779Hx4uyOyp+Z2dowzdEdru" +
       "IsjdR5SxIFC2OR+bZ/70oV/6I+Xj1+XJ5utDK9N3yeR9882Z+plC7PcW8KdP" +
       "tP1sDp6JSg8s9Ii3Nro9dq1o5LGWbVuODtzicgkDMGWeEh254XteKFlwfNSi" +
       "4ulL5+8+8FT2569yVfN3ZUl/6ZS2X87Bs1Hp9gMtAA2wed2HjoT86FUIWaDd" +
       "D57mvpDNayTkJ09p+7Uc/EpUugkIiePe5iC79crCqpQ0urDQPeeCACxOcRe2" +
       "XiWPhP/VqxD+nrzydeB5877wb75Gwv/bU9o+l4PPRKVzQHhRDXTdHQWKG+bh" +
       "5kAPD12qB8wwQJS6FKvQxWevQhdFJQQefF8X+Muoi70Cq8iDf75A+NIpCvmD" +
       "HPw7oJDw8go5mSNMPEs70sEXrtYeHgQPva8D+hrZw38+pe1Pc/DVqHQjsAdi" +
       "VPj654/E+9rLYe7cvnjcNRLvv53S9s0c/PnO3Cnbm4Ml9WB2T4j69auN3flM" +
       "jvdFHV8jUb99Stt3cvA/otKdQNSJpae+F0SSpe2uKR6L3391tYK+Cjxv2xf0" +
       "bddI0P99Stvf5+Bvwdb4mKBd3VqY0QlJv3e1kt4Lnqf2JX3q2ki6VzqlraDz" +
       "g6h0G5C0A7aLItjVnJDxH1+qjMUVtMvfSbvv5OXCC8Wdcd9/GYLywSJz7CrJ" +
       "boxC4Fecooy7dtznxZuLijsuz0gR99+44yFHuz0Hd+bgHAhz+jpW7PBykf2m" +
       "uefZuuIe6hYM8wK6vTyjr87BvTm4LwevzMGrTjD/cljOo6e0Pf4jKutoPOhI" +
       "Y4/k4LEcnAfnw3xhyKf/9GObGINj5LGL5h+0nvvj//h3Z5/ZXfS79Npi8a3B" +
       "fteT/b7x9euqt0XnP1wc966fK2Fh8DeD41GYY0alR6783UJBa3eV77YXNPJ7" +
       "j4y8GP7Qxg8s9OyRhRYIuT4uXHLJ8fJKuKjSzkXxc994X6M4y5xNrNCKdG20" +
       "/ynFpSebo0vPT17yecVl1XRR/fZnP/jlR78zubu4N7/TSM7tm8CpKP//4/uW" +
       "uldY6pnC34LSa6/A8D5HxUHsovrOj/3TH//109/8ynWlG8FZMz8UK4EOzr9R" +
       "6cKVPjc5TuD8CJRI0AuclO/Y9bbcxYHi8gk8d1h7eDSOSm+8Eu3iQuuJE3T+" +
       "wYbtpXqAe7Gr5WQfOnEsj33/eGthCre/dFN4FzjE/gjKO5R9f6konSuM/tgF" +
       "t/xm6/FGPyrdTTCYKF4czfj2xQkm0BjOtAsTy6//7o0Kn92cMnuSZWuEEmg7" +
       "t/nkD295/K33f+WfFW7zfCW9RMVceSHwd/wdv5a/v7xcTeTMb5vu/VgOyjko" +
       "9EFdg8jJntLGvcRlhsnBIAc8CJqmEpqEpxWG2bhqvUg5EAtaeakwjsmPqJej" +
       "F4sJWP5cJb+O/YIK+slT2i7+iAo6GhjKsd52pKqfyEH+CnPvqZwlL7KMbd74" +
       "h1etqPz25p5a0MpLubHvGS9eUcf4PWUw+5Q296qVtMpBfkjZ86LSLTslYbb9" +
       "8uipkDA41FOxtsXXwNHecUrb0y/R0bIcvDMH7wKOFnlHN5HfftV6eW8Onilo" +
       "5aX35OCnrpX9nHwdeWKH/PCl39MEQeyDbUR7o+p+/ia0IPGzV21mP52DD+Tg" +
       "w1Hp+lSxopfHwn4hBz93aGE/n4OPvkwWduz9jlkM9stXRNj7YIHw8avZDv/L" +
       "HHwsB88dCXXVCvrEpQr61Rz8q5fT1M4cSVS8AmgUw/7GC6nqX1+1Sf16Dj6V" +
       "g0+/jPr67Uv19dkc/JtNVLr16KPCPDXwwPO+UN59Vat+5rmzN9//3PjPi+TL" +
       "4ZevtzClm43Yto9/B3esfKMf6IZViHbLLt9SnIH3PheVHrjSV45R6ToAi5D6" +
       "Ozvs341K91wOG2ACeBzz98DB+CRmVLqh+H8c7/eB3Ed4YBHdFY6jfAlQByh5" +
       "8d+DDdve5XdqpXMvNBvH8n+PX/F4wsa7b8Yvqp99rjd4x/cbn9x9nge2i1ke" +
       "r/P9/027lFZBNE8PPXpFage0buw+8YM7fuuW1x5kFO/YMXzkGMd4e83lk01t" +
       "x4+K9FD2u/f/zpt+7blvFp/t/X87AHZRyj8AAA==");
}
