package org.apache.batik.dom.svg;
public interface SVGSVGContext extends org.apache.batik.dom.svg.SVGContext {
    java.util.List getIntersectionList(org.w3c.dom.svg.SVGRect svgRect, org.w3c.dom.Element end);
    java.util.List getEnclosureList(org.w3c.dom.svg.SVGRect rect, org.w3c.dom.Element end);
    boolean checkIntersection(org.w3c.dom.Element element, org.w3c.dom.svg.SVGRect rect);
    boolean checkEnclosure(org.w3c.dom.Element element, org.w3c.dom.svg.SVGRect rect);
    void deselectAll();
    int suspendRedraw(int max_wait_milliseconds);
    boolean unsuspendRedraw(int suspend_handle_id);
    void unsuspendRedrawAll();
    void forceRedraw();
    void pauseAnimations();
    void unpauseAnimations();
    boolean animationsPaused();
    float getCurrentTime();
    void setCurrentTime(float t);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028785000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVZe2wcxRmfO8fP+BUncUIeJjhOaBK4K6FQwJDiOHZy9OJc" +
                                          "7RCB83Dm9ubuNt7b3ezO2hdDWopakVYlohDKQyWqqlAIBYKqopbyUNpKPAS0" +
                                          "CqVQoDxUkIC2CCJa+gdQ+n0ze7d7e/YhlVyUHe/NfPP4fvN9v++b2XvfI7W2" +
                                          "RbqYziN8n8nsyIDOE9SyWapfo7a9FerGlFtq6Ie73hm6MEzqRklrltqbFWqz" +
                                          "QZVpKXuULFV1m1NdYfYQYynskbCYzawJylVDHyXzVTuWMzVVUflmI8VQYBu1" +
                                          "4mQO5dxSkw5nMXcATpbGYSVRsZJoX7C5N06aFcPc54kv9In3+1pQMufNZXPS" +
                                          "Ht9DJ2jU4aoWjas2781bZI1paPsymsEjLM8je7TzXAgui59XBkH3A20ffXxD" +
                                          "tl1AMJfqusGFevYwsw1tgqXipM2rHdBYzt5Lvklq4mS2T5iTnnhh0ihMGoVJ" +
                                          "C9p6UrD6FqY7uX5DqMMLI9WZCi6IkzNKBzGpRXPuMAmxZhihgbu6i86g7bKi" +
                                          "tlLLMhVvXhM9dMuu9l/UkLZR0qbqI7gcBRbBYZJRAJTlksyy+1Iplholc3TY" +
                                          "7BFmqVRTp9yd7rDVjE65A9tfgAUrHZNZYk4PK9hH0M1yFG5YRfXSwqDcX7Vp" +
                                          "jWZA105PV6nhINaDgk0qLMxKU7A7t8uscVVPcXJ6sEdRx56vgwB0rc8xnjWK" +
                                          "U83SKVSQDmkiGtUz0REwPT0DorUGGKDFyaIZB0WsTaqM0wwbQ4sMyCVkE0g1" +
                                          "CiCwCyfzg2JiJNilRYFd8u3Pe0MXH7xK36SHSQjWnGKKhuufDZ26Ap2GWZpZ" +
                                          "DPxAdmxeHf8R7Xz0QJgQEJ4fEJYyv7r65KVndR1/UsosnkZmS3IPU/iYciTZ" +
                                          "emJJ/6oLa3AZDaZhq7j5JZoLL0u4Lb15EximszgiNkYKjceHH7/ymnvYP8Kk" +
                                          "KUbqFENzcmBHcxQjZ6oaszYynVmUs1SMNDI91S/aY6Qe3uOqzmTtlnTaZjxG" +
                                          "Zmmiqs4QvwGiNAyBEDXBu6qnjcK7SXlWvOdNQkg9PCQEj0Xkvx4sOLkymjVy" +
                                          "LEoVqqu6EU1YBupvR4FxkoBtNpoEqx+P2oZjgQlGDSsTpWAHWeY2pIxc1J4A" +
                                          "U9q2Ef67bhRBEzOrOXgeNZs7GQoB6EuCLq+Bt2wytBSzxpRDzvqBk/ePPS3N" +
                                          "CV3AxYSTlTBfRM4XEfNFYL4IzBcpmY+EQmKaeTiv3FfYlXHwbyDY5lUjOy/b" +
                                          "faC7BgzKnJyFmOaFwy0u/ICOgfUJ175kxLzjL39499wwCXss0Oaj7xHGe32W" +
                                          "h2N2CBub461jq8UYyL16a+Kmm9+7brtYBEgsn27CHiz7weKARoGOvvvk3pde" +
                                          "f+3I8+Hiwms4UK+ThAjGSQNNAm9RhXPSWCQgqdi8z+BfCJ7/4oM6YoU0po5+" +
                                          "16KXFU3aNH1whMT7Qk6WV4LexR2hWzoTTwiOO3LtocOpLXeeI725o9T3BiC0" +
                                          "3PfCp89Ebn3jqWk2v5Eb5tkam2Cab32tOGVJkrBZUGgh4I4pr7be+OZDPZn1" +
                                          "YTIrTjoAIIdqGO77rAwEEmXc5drmJGQOXgBf5gvgmHlYhsJSED9mCuTuKA3G" +
                                          "BLOwnpN5vhEK6QUS6eqZg3tw6U9c+/dFW9dldwuL84drnK0WIg32TGCQLQbT" +
                                          "0wPwB4c8uvnepzauVG4Mi/iCXD1NXCrt1OvfCJjUYhBIdVQHa1pg0u6gOwfR" +
                                          "GlNWL6MPjj26v0fsQiMEWU6BFCF+dQUnL4kRvQVPw6kaAIS0YeWohk0FyJt4" +
                                          "1jImvRrBM3Ok4YOBNKKdL4Fnjcui4i+2dppYLpC8JOS7RHkGFj3CusL4ugKL" +
                                          "lULsS2BtKz1nBtrXgB1xR3ou12Hb1bRKkxpDmvmkbcU5D/7zYLs0ZA1qClt0" +
                                          "1ucP4NWftp5c8/Su/3SJYUIKph0e4XhiMpbN9Ubusyy6D9eR//ZzS297gt4B" +
                                          "UREika1OMRFcwlK/gncvQO+ePFfxO/UwEr/bPtffjkkk2LZApF9IrBPlekTW" +
                                          "JVH8HcPiIuicgSiIlGTLxeKySt0W/WPEAQIbppOCMMaUHWe2d/Zc+GG3ZIqu" +
                                          "aWR9GcjBh38zOnpmuyKFu6cbuDTzuPuuBuWV3ONvyQ6nTdNBys2/O3r9thf3" +
                                          "PCM8sAEpomj3PgIAKvHZXnvR9loRig54jrq2d1SS7o4vGGShG6TVag4ywehW" +
                                          "NcdS7o4UgnhVx0eSX1DCuN6m/Xxc63v/gp9dImE9Ywam8+Qf+sYbJ+6YOnav" +
                                          "dBKEl5M1Mx1Eyk8/SKcrZqZTn4H8e+NFx999c9vOsGuarVgk8gXzbvUnCtJT" +
                                          "ryiadMgNhJAWlNqJHHrD99oeuaGjZhCYLUYaHF3d67BYqpQz620n6TMcL+GW" +
                                          "DCqsRvBLHiMz5C+rTRNx7plBOd+ZbEy54fkPWrZ98NhJAWLpoc6fnWymZq/k" +
                                          "Rix6xTYG86NN1M6C3FeOD+1o145/DCOOwogKGIm9xYLkLF+Sy7jStfUv//b3" +
                                          "nbtP1JDwIGnSDJoapHh8giQYqJnZWcjr8ubXLpUuMNkARbvgCFLGGmUVyGqn" +
                                          "T8+XAzmTC4ab+vWCX1581+HXRF4kc5e1pfR/GjxrXRdc+4Xov5Tswp7UBiwG" +
                                          "hVSuAiWKVD8Lp36gxAFd0QwbomTB5LaILruwUCUU9P9EDSsyQSiasW0pPBe4" +
                                          "UFxQHSgGBR5CaqoCFFdj4XA4U2WZMu6PD/b0FJ6wgJG4OuH63drEbuVAT+Kt" +
                                          "gksPSQeCzqsqXJ+UjhHd3/H6+I/fuc8NMmVpTIkwO3Do+59FDh6SZCWP9MvL" +
                                          "TtX+PvJY73dv28+K08wiegy+fWz/w3fvv66gWYST+qRhaIzqQVLCnzvynt1M" +
                                          "VMtuFsGzzrWbdVW3mx9WsJubsPgBcLawm6ITYe23PCCurwIQoq0Tng0uEBtO" +
                                          "IRB+FQ9XaPsJFrdxMjvFbIZk2KfJ89A1roXhn+9wMmvCUFMeHrdXAQ8cgsyH" +
                                          "J+biETuFeIR8x89v+lQLqFmjuteQZU4hRr2/ApIPYnGUkxbbsU2mp4ZZyqKT" +
                                          "WHnMw+2eajnUYniGXNyGTj1uQg0hcLwCBL/D4mHIExy9DASfMz1SLWfCaDTi" +
                                          "gjBSJWd6tkLbH7F4kpOOgP7gU9jyUw+Cp6rJJ1e4EFxRJQhertD2Vyz+zMXJ" +
                                          "WmHe9vt0f6FaumNQ2enqvrNKur9doe1dLP4G5m9Sx2Z9cOrxrld8+r9ZLf3x" +
                                          "WiLp6p+skv7/qtD2ERbvQwrm6JUR+KBaLIgIZFwEMtVBIBSq0FaDlZ9APk6L" +
                                          "qicQiVSAAT+tAgBN2LYQHs0FQKsSAK0V2jAvDTVCNgUHkn7HsiDvxhP/54Xd" +
                                          "2jSc82YIvEXUQk3VcpxlAij5b+8pRM3TI9Qh4FlWAbpuLBYDdHYJdKWuE1py" +
                                          "KjDIQ5ZS8oUDz8ULy76bym99yv2H2xoWHL78RXHXWvwe1xwnDWlH03zXEv4r" +
                                          "ijrTYmlVoNIsrwlMoeVqThbOdPUP6ReUuOjQKil9NifzppMGSSj9kl8GpwtK" +
                                          "gl2Jv365czlp8uQ4qZMvfpHzYXQQwdevmmZe+vtiP6TCh+d/3k74PgAtLzlC" +
                                          "iu/YheOok3Avr44dvmzoqpPn3ym/BykanZrCUWbHSb28pRaD1pRdhPlHK4xV" +
                                          "t2nVx60PNK4oHPnmyAV7przYR9tAlCETLWBR4L7X7ile+7505OLHnj1Q9xwc" +
                                          "VreTEOVk7nbfV2T5ybQ3bzoWWbo9Xn6ttY1a4iK6d9Xt+9adlX7/FXG5QuQ1" +
                                          "2JKZ5ceU5+/a+acbFx7pCpPZMVILp1mWHyVNqr1hnz7MlAlrlLSo9kAelgij" +
                                          "qFQruTNrRWOl+IVb4OLC2VKsxQ8LnHSXH7rLv840acYks9Ybji64vCVOZns1" +
                                          "cmcC3zUc0wx08GrcrcRyu2RC3A2wu7H4ZtMsfE6rPWEKh90xPTGigW4Sr/gW" +
                                          "+x8wjmjX4yIAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028785000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALV6e6zk1nkf792VtLuStSvZlmTZ8kNeGZXp7Lw4nGEVOxly" +
                                          "XpzhzJDDITnDxFnzNRwO32/OuG4dA22UBHXcRG5cwNY/cZDUUOIgbZAEaQql" +
                                          "RRIHeQAOjLQJUNtom7R5GI0KJA3qJukh5z7m3tVew1jtxfIs55zvnPP9vtc5" +
                                          "5zt85RvQA2EAwZ5rbXTLjW5pWXRrbdVvRRtPC28NqDotBaGmEpYUhjNQd1t5" +
                                          "9ueu//U3P7W6cQg9KEJvlhzHjaTIcJ1wqoWulWgqBV0/re1Ymh1G0A1qLSVS" +
                                          "KY4Mq0QZYfQCBT281zWCblLHLJQACyXAQqlgodQ6pQKd3qQ5sU3kPSQnCn3o" +
                                          "H0MHFPSgp+TsRdB7zg7iSYFkHw1DFwjACFfy3zwAVXTOAujdJ9h3mO8A/Gm4" +
                                          "9NKPf9+Nn78EXReh64bD5uwogIkITCJCj9iaLWtB2FJVTRWhxxxNU1ktMCTL" +
                                          "2BZ8i9DjoaE7UhQH2omQ8srY04JizlPJPaLk2IJYidzgBN7S0Cz1+NcDS0vS" +
                                          "AdYnTrHuEHbzegDwmgEYC5aSoh13uWwajhpB7zrf4wTjzSEgAF0fsrVo5Z5M" +
                                          "ddmRQAX0+E53luToJTYKDEcHpA+4MZglgp6+66C5rD1JMSVdux1BT52no3dN" +
                                          "gOpqIYi8SwS99TxZMRLQ0tPntLSnn2+Mv/OTH3X6zmHBs6opVs7/FdDpnec6" +
                                          "TbWlFmiOou06PvJ+6l9KT/zqi4cQBIjfeo54R/OL/+i17/7AO1/90o7m7a9D" +
                                          "M5HXmhLdVj4vP/rldxDPY5dyNq54bmjkyj+DvDB/+qjlhcwDnvfEyYh5463j" +
                                          "xlenv7H4+Be0Pz+ErpHQg4prxTawo8cU1/YMSwt6mqMFUqSpJHRVc1SiaCeh" +
                                          "h8A7ZTjarnayXIZaREKXraLqQbf4DUS0BEPkInoIvBvO0j1+96RoVbxnHgRB" +
                                          "D4EHOgBPAO3+buZFBC1KK9fWSpIiOYbjlujAzfGHJc2JZCDbVUkGVm+WQjcO" +
                                          "gAmW3EAvScAOVtpRg+rapTABpsT3wL8jN7qVm5h3PwfPcmQ30oMDIPR3nHd5" +
                                          "C3hL37VULbitvBTjndd+9vZvH564wJFMIuh9YL5bu/luFfPdAvPdAvPdOjMf" +
                                          "dHBQTPOWfN6dXoFWTODfIPI98jz74cFHXnz2EjAoL72cyzQrHO6p4scl0O/5" +
                                          "u0fjbh4KyCL8KcA6n/q/E0v+xH/9m4LX/YCaD3j4Oh5wrr9YeuWzTxMf+vOi" +
                                          "/1UQeyIJ2Apw63ee98MzrpM75HkZgpB6Om71C/ZfHT774K8fQg+J0A3lKF7z" +
                                          "khVrrAZi5jUjPA7iIKafaT8bb3bO9cKRX0fQO87ztTftC8fBMQf/wL7uwHtO" +
                                          "nb9fK+zg0YLmsb8Hfwfg+bv8yTWRV+ys/HHiyNXefeJrnpcdHETQA9VbjVvl" +
                                          "vP97ch2fF3DOwAdZ73P/+ff+tHYIHZ4G7Ot7SyAQwgt7QSIf7HoRDh47NZlZ" +
                                          "oOXC+i+foX/s09/4ge8p7AVQvPf1JryZlznHYMUDK8c//ZL/h1/76ue/cnhi" +
                                          "Y5cisErGsmUo4CUsFjCAZGk4klUI5NkIenJtKTePUfNgQQOM3VxbjUJUbwVL" +
                                          "eMFarpVbu1WgcCjA0c27mOveyn1b+dRX/vJN/F/++9fusNSzghlJ3gs7DRVc" +
                                          "ZWD4J897UV8KV4AOeXX8vTesV78JRhTBiAqIB+EkAC6cnRHjEfUDD/3Rr/3H" +
                                          "Jz7y5UvQYRe6ZrmS2pXyRRaEymgF1uUV8P7M+67v3oW69AoobhS+CRX4375j" +
                                          "p3DrR08FQblgMfzh//6p3/mR934N8DGAHkhyGwYc7ElrHOf7g3/2yqefefil" +
                                          "r/9woRMQWPmPP/e/imjbLCZ4rij/QV7AO43lrx/Ii+/Ii1vHano6VxNbxD9K" +
                                          "CqORqxpgf6AWmrowdNCBYQNrS44Wv9LHHv+a+dn/+TO7he18nDhHrL340g/9" +
                                          "/a1PvnS4t5147x0r+n6f3ZaiYPpNJ6p8z0WzFD26/+OLH/uVn/7YD+y4evzs" +
                                          "4tgBe7+f+YO//Z1bn/n6b71OdL5sucdGmZfVo2nz/+rfWrHR9Rf7SEi2jv8o" +
                                          "XtSqqZJN7eWkuaRhnHMUjtQG69VEwofIEO0y6aBtTPriBpsMlMaUwJu1to3F" +
                                          "cjyOGnJN206qK7UtuJ5k8gvLXbWHzEbwfatF4ouh73ryhht7Q7rFlgmfZ9x2" +
                                          "xpkkUSWIgQTrKgM75a3WUBtaabGy+A3X10rjJU0jy2SMJTAsV+fJkmwI1ans" +
                                          "L7bGuOk0nXBDticdjN0Ikrd0GxLWBRsFqxv5KKk1aisbHXW2/tS0Aivy5a7g" +
                                          "bxmR94bzmKO6fMWujNXFcsEsNk5oysRiK6WDjcW3+5v5lp/FwmjL89zSsskm" +
                                          "zyzwuILYzKSuZqyZ1p3RXGnNPLm3YPlpKA7ceYOoj8uo1FVopY6YCUY6Nbji" +
                                          "MaN4ORbnNNuPsPaguuYQyRXWUlhtNCuySFY8iQ43dthZU6PmWmvMtvOWHht1" +
                                          "bI6b/VqrWl4u51k7siqt0WDpx2GvqyWLNEwrke7PDW9UDfoqvthGdSoxLR+x" +
                                          "2eqsbswcZ7UqG6tRz+UHBOahXNBGu/6iEc/rbX80okhMEAkDJc3teIhve950" +
                                          "Tsejlp2JK2OlyzFqNFG9IQ+NyKKo0YpP5qsRpo7iGLNKnEmJ07Iv+2RDV/Cp" +
                                          "jC/EwbQ1mFlmuNnAFdKzQFBRarNFA+/aPj+dedhGbQRtft1B6y0sWuotLuiL" +
                                          "Y3FhIvQQW/XLo8qm26svpss5m/ptZd7gvbUgtirlOs2jzoocS23dLPvUKBty" +
                                          "jVYjasahwvO0Mh+gYUedZnU00VO8HCjNzFkLQ65ZY4c8y7Rt0+hF3LY87aT0" +
                                          "rNx2A67XG7a7G4kU8bIQziR/VE5TmUHC0YbgzU5ZrxAGkRKb5VavDozB2LCm" +
                                          "i67ajGu0Vh7N+41sWEPZPsusBac3HK7ieNkWq2jLq/YE0RPbdNZS7UzrL5vT" +
                                          "xnxbZgY60xkgy85gsUkaAVof8o46rZS40A0dU7TZGklzJWOhGDNRsweDEupS" +
                                          "Uq0ltiVx5TfW9YHoUlQ5Rii5Uu9khh1udWNsLoZrsGnrN0ob20kWdHNoDjnZ" +
                                          "73bGW8XG+0rGrEXUlcItsGje5sIKOxq3SazClqQFymi1eOJv7VlkOTNJXGc9" +
                                          "0bYNP0SYJO0Z49YG77TneIz6zloZNti5JSQTdcyYOkYTTGddnptJhoQTytzY" +
                                          "a35DdVze92O0w1WAa3jJFOlmpotHY8/t+BlMV11xrTNWr82GM09o9QVtUfXI" +
                                          "TKkMkBaH+dXOEm3Iqyne2U6CyVzXxmLY6DEujnZigvJhPKqmmwhnt5k3bW8T" +
                                          "HzdLGk2ztTHB11rZgp1ZM3w5HSHzznLcXVAIucUVz17AHcYeStrMSGrd5cKa" +
                                          "91N5017ULW492ZTkpUQ0cH07dAabrj2RuummHJdIYqIvuUGlUTczarumahiC" +
                                          "YWlKzMOwPJHWjazf02pVYVUdVwk8lhG0svab3GJDVVAJHto2BjfkIFrgHT10" +
                                          "qg2ib2wbqTZsTd3eJEkSs+ap2hKukU24b6R2iHBDeLZqrXssMx63bGy6ArFB" +
                                          "IBjdV43mFsaXxKBRQtwRunC5sufW4Qo6nHe5mjTuV9LVaNZgTFTgEUrLptWV" +
                                          "sHVns9SYTGpU5CoTj5prGtmo1l1sVsMNolyjl4TXxDqyU1v7gllN6h25HpmS" +
                                          "XSUkuVaNJj1+YAa4yPX0FUIiXtCQNXgCTFl0KosZGczWboskVb83aTSCVtrp" +
                                          "2HOlrgb2oMcAleHLup7odt9arMIB22ljNhHP4mGr1sOpSep443qy6gxRhmNR" +
                                          "zRf1WpSiHKbAJbUrYKqlpjHVRNTAGZYFUq9VZz2CoRh5Vk7pFEeUZpw4mreV" +
                                          "Yr6HjIySQczblfGcCKLKJAEyWnOLFU6qPNOXKp5ejlF9ki6nPWssUOiIXq+r" +
                                          "aFJehowx6ggcineJLqwynEMh5jRheDpFTalFsuWFJrgrs9zdDCKksibtZBrg" +
                                          "o9rERBYTfDwcqhTSBb4QG4gBV8FOeEF5RHMwYRvTvtnrrmtEHFJIrA8pi6NC" +
                                          "topHw23FwaMAiKaSTWtuXKn25Yo8HZqZ17YT25QVrt4uNbYLKiyDCOcTVlSu" +
                                          "xAqNjIVl5NWVZomNSzV2sODIobcqa8h8ZYw8eYxxcgzCK9rGtGmpJG7ZKtbQ" +
                                          "IwTnph3DlCqT0bSrpNawpDtKwkxgje4us0mJSztBSaaj5XJtmmaVElteFyMD" +
                                          "nLY0cyYM+H6zr9AGGRuKzhqk1ZtRmTbcsFFZKAl0p8WQsudNiNFI4oDzVtWS" +
                                          "qMC9Xk0k/VgSplhPWeOrWnM7cTw73gy7MarIcXu2jek4xmOBr03GyYZBnZk6" +
                                          "xjdhtTSpBVi0WtZoYtQMWx3Ptdc1Widbw6Qvzp1kilnu1NDryDrwq2qFZRsu" +
                                          "kvR67KqHznhJRzapthLGiprXc7qz4rOyxs4rbSIeo3ZpniloLSnpHqaSdgdb" +
                                          "pJLdhJklHC7kAYwuJo6UqPiwY9VHlVFW6WxMIOmhEoi+OHOQflODx90MwzAF" +
                                          "SyZhL5YCXjeb+nwrJ5xDRINZsDEkdaSPV4OWYI39Qb8ftDHM1WKptxZXxILi" +
                                          "FlK/W1PRBr7wPWaLVssOOhspFNwT2oQfThOc6hujbZ2Ag9l0nDU8C5+osCh3" +
                                          "NnVkadJCIGLNYnSwvVTQpSNsbNEvmVMjQ7PZotdEx+PKCCVqXW3ShituBamX" +
                                          "2sRkkrr6sEfaWLagTKoLs5vGmo2WXFIqyTVHjujKoJ2SPYdtD1zJ66+ausEs" +
                                          "/IEjCso6aMbynPK4eDQ2W1M50Yku1evZHL/p+c6sCc9bYKEgEEmGE4GYV+rN" +
                                          "CtyfT7uIqdS1ireclnrrLJhPVQVG5m5Sn4Wp1+BwI+2teDZuGcKQbzcpr4bq" +
                                          "WaurlplUdu0ZXqckkgrilCM4DqOxDlgbNgxrSKFQ9mhcQ7huxvRZvYdP64Tk" +
                                          "u0S3q66ReQvhqoI4ilG6XZLL3QGa6oMeMon7aE0NOnLMt2bwMNLNkGYZjdj6" +
                                          "oT8fwNx61VdrpT4Kk6VlrDTHI5v3ZqSZTmptF65j3fYKZUVCoLFRQs2iOUwn" +
                                          "g0WjpibVJjwsN1ND0zfwUtiW0toySVBUF8CaA/vTlURufYanCGebbJyoMuJH" +
                                          "UdwNe9ttIMgqL9TsDBPCQSyHtI4rlJTaKDlbaFVg90QcpCTj+uWZAyJWB48m" +
                                          "5BSHuww2B3vAQTdQs9E66cqkaFaHy0ETa1UCd75yYCwd2QnBdUdaP1DnLaap" +
                                          "6OGmP4BlozOLuxo5bWZNsD22GMrv2us40hiRQ1bToFpqeSS9cHqcmclyyFVt" +
                                          "DxHFjT+cCX1nlMJVTVo73MIxevPxpjdbV2JGL68UKiVwqtRG7D7ZyTZYu8Uu" +
                                          "R9sKSwlLQmrPDH2NswNBRSOTkvsNYBDeZKLTDZ3D1hsuhQkPDQaDioZ0utl0" +
                                          "wKy0IGpX+c0W3o7mA8Hua1gSlZdoV4rtMVPVHD8JxsM4wFRXq6gUjfTqNsZm" +
                                          "VRFTJuBMa6lNOMBEalnLBIPyUA8OzaRR8sGYHWC0TBrY6ICbwkNcokidFLtp" +
                                          "ZxTxOImzfrkrtS0Ra9EmSvmGwhg82wKGErV0fFylFkw/LHeZYci2hmW+um4l" +
                                          "7RlPjHWubzqNfmi0k2xFl+rIXK2uWaVZXZBJZ84xZo1XvMxqGeu6DDe96ag2" +
                                          "IzFmhXQtoSV7MYUv2mp/MVCHQtypeJvhuk0ydZFtulx72+SoTQOVNzaGbZJq" +
                                          "v5q5Qp9qNKfz/lxIUq2SpU5bsPrl2nbeSZDAWAezhW3x7pgMg9QauRrvz1by" +
                                          "RKU5Gp1qXDxZM0PDwsbGcut5ox7LrjHTava8NBrqVnWQ1NC6srW8ZswgvjhK" +
                                          "ll5/u5gzTKpqiW2LGpxEBo3OiBWslmpmA6H1VkRtLcKIweFLm7hmrZUECKIm" +
                                          "9tb1PdqpbewSvjElRwwITpD7rFwFApDaFW+qrmirP0QyPqo6fIaW6fEQcfu0" +
                                          "Y29afMMLtospFrUsojOjBHyKUI15w7A0uFEv1ydU31lXGCxLFT7QZp0JbzYc" +
                                          "ecmDU8xGZmry1hUE2cXmDhpFi4qEGENUxeYRjEmqNW+UuvNenYmZSnUwFOuK" +
                                          "xtXhkgRLitwFEZbwaHHEk5RXsYX+hh/7QWXlbBsjqwXOghTrYmZLs3Rj7XeZ" +
                                          "IJ6Ng6kwsWCSl5EJRVT5YZgxTcrps2DfH1BJEylLysIMsYW8NlAkIfiJ6IQV" +
                                          "xVaI2pZTymlWbvYCJVCmm7g6JcDBLY0bfUSMRuGygwa00BmusHJGz3qGLiBs" +
                                          "UNIFOGuma3s9Rzb58fuDH8yP5OS3lxV5rEhendxnrK1G3lD+NrIB2UUTRtAV" +
                                          "SQ6jQFKiCLp6csGym30ve3twnCx770WZ4qM0cZ4ReeZu1xpFNuTzn3jpZXXy" +
                                          "k5U8G5IP3AaTR673HZaWaNbetI+Ckd5/98zPqLjVOc3O/uYn/uzp2YdWHynS" +
                                          "k3dkjSnoWt6Tzi/PTi7J3nWOz/ND/uvRK7/Ve5/yo4fQpZNc7R33TWc7vXA2" +
                                          "Q3st0KI4cGYnedoAevaOdJGraGocaKfzvv/d0i/c/tWP3TyELu8nsPMRnjmX" +
                                          "Dn546Qa2ZOUTHF9wXYtWgZue1uznhoFYr+aW8Q7wwEc3IMX/eeubvbx8S3Zq" +
                                          "X3cYzuGJpU6PzCSA3nealiRcy9KUQuo3OccusniSbGn5FcH/u/5c5Rf+4pM3" +
                                          "djkuC9Qcq+ED33qA0/q34dDHf/v7/s87i2EOlPzK8DTRekq2u4d68+nIrSCQ" +
                                          "Njkf2ff//jP/6jelz12CDkjocmhsteJi6HCH79jUn8xNPa0p+xY+zS9tjtrf" +
                                          "vN+eXwdrTlRIZFVQKEWpF+64uw3Jfxcp8dugs65FZO5u4Y7ZnK0zicSzxj6V" +
                                          "0sKDbiu/zHz9y5/bfvGVnQxlKdQiCL7bHfOd19z5Dcdzd/eovdvHv+r9w1f/" +
                                          "9L/xHz720YdPzKdAc+Ui8zkW0aP7Ke6dtuPTqPWRb5XD3BdeUfE9Z034beCp" +
                                          "HvFQvScTPquww1MqIy/MguqfXKDW78+LbQTdAGrtOIrlhsCbC53mDd6doruQ" +
                                          "7ficoD56D4J6JK98BjzNoxmb90dQZiGtguqfXyCoH8mLF8G6BhYQxdz3gIL8" +
                                          "u/ZWMyKCHpJd19Ik51QUP3ivongaPB86EsWH7rsoPnuBKF7Oix8HTlKI4sRq" +
                                          "8tp/cQr4M/cAuKh8AjztI8DtNxDwPpSfvqDtC3nxExH0sKqFWh6aW5b1erq+" +
                                          "nLiGeor78/eAOyeF3goe8gg3+QbiPtjbEJ2DcMk4WgF+8QJ5/Lu8+PkIelMY" +
                                          "h57mqFNNDaQ0r/ylU/T/5l7N/O3gGR+hH7/x6At2C4LfuADql/Li1yLoeuzc" +
                                          "AXbPxP/DvZp4Ht7YI7DsfTLx37+g7St58bsR9Pg5nMDS85ZXTqH+3hvhzfMj" +
                                          "qPP7BPWrF7R9PS/+MCo2nYp2qs49jH90rxjzEP3hI4wfvk8Y/+yCtr/Iiz8G" +
                                          "ZutJcai1HMM+PUXs4fyTe8WZ78DlI5zyfcL51xe0/U1evAbW4ti5GOn/vtdo" +
                                          "lCPVj5Dq9wfpweEFbZfzyr8F2zPpBCKdI1bPRaK/uweg1/LKp8BjHQG17hPQ" +
                                          "Ry9ou5EXV8GeAuxDiTgIwJFkZtja6y1W4AzpStEJ9oNr92rO7y7g7v78NxD7" +
                                          "6ZJz8HgB8pkLBPCuvHgKCCA8I4CzBn3wtm8HawbW6jOfweXHyqfu+Lh290Go" +
                                          "8rMvX7/y5MvcfyoO7icfbV6loCvL2LL2v9zae3/QC7Tlbsd4dXdW9wo074ug" +
                                          "p+6WcAHbDVDm3B48t6N+PoLe8nrUgBKU+5QfAK5wnhJYRPH/Pl0pgq6d0kXQ" +
                                          "g7uXfZIqGB2Q5K+1/EOyQnxP7ZtJ4VmPfyuJn3TZ/xIsP58WHzsfZ2di+ugY" +
                                          "/MWXB+OPvob+5O5LNMWSttt8lCsU9NAuHVIMmqcW3nPX0Y7HerD//Dcf/bmr" +
                                          "zx2fdB/dMXxqsnu8vev1ExUd24uK1ML2l578t9/5Uy9/tfga6v8D/VF1+oUu" +
                                          "AAA=");
}
