package org.apache.batik.parser;
public interface TimingSpecifierListHandler extends org.apache.batik.parser.TimingSpecifierHandler {
    void startTimingSpecifierList();
    void endTimingSpecifierList();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028785000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL0Ya2wcR3nuzu/4ncQOSePYiR3hNNyphSIVh9DYtWuH86Nx" +
                                          "2lKH5DK3O3e38d7uZnbOPrsEtaXQwI8oCi4tiPqXqz7UlxAVIGgVhERbFZBa" +
                                          "IqCgtkj8oDwiGiHBjwDl+2b2bvfWvhSBhKWd2/3mm+/9Gj99mdS6nPQwS8TF" +
                                          "ksPc+KglZih3mT5iUtc9CrCU9nCM/vXEu1M3R0ndHGnNUXdSoy4bM5ipu3Nk" +
                                          "p2G5gloac6cY0/HEDGcu4wtUGLY1R7Ya7kTeMQ3NEJO2zhDhTsqTpIMKwY10" +
                                          "QbAJj4AgO5MgSUJKkjgU3h5KkmbNdpZ89G0B9JHADmLmfV6uIO3JU3SBJgrC" +
                                          "MBNJwxVDRU6ud2xzKWvaIs6KIn7KvMkzweHkTetMsPv5tr9dPZ9rlybYTC3L" +
                                          "FlI99whzbXOB6UnS5kNHTZZ3T5PPk1iSbAogC9KfLDFNANMEMC1p62OB9C3M" +
                                          "KuRHbKmOKFGqczQUSJC+SiIO5TTvkZmRMgOFBuHpLg+Dtr1lbZWW61R86PrE" +
                                          "ysMn2r8VI21zpM2wZlEcDYQQwGQODMryacbdQ7rO9DnSYYGzZxk3qGkse57u" +
                                          "dI2sRUUB3F8yCwILDuOSp28r8CPoxguasHlZvYwMKO+rNmPSLOja5euqNBxD" +
                                          "OCjYZIBgPEMh7rwjNfOGpQuyK3yirGP/pwEBjtbnmcjZZVY1FgUA6VQhYlIr" +
                                          "m5iF0LOygFprQwByQbZXJYq2dqg2T7MshREZwptRW4DVKA2BRwTZGkaTlMBL" +
                                          "20NeCvjn8tSBc/dY41aUREBmnWkmyr8JDvWEDh1hGcYZ5IE62Lwv+TXa9eLZ" +
                                          "KCGAvDWErHC+87krt+zvufiKwtmxAc50+hTTREpbS7e+ft3I4M0xFKPBsV0D" +
                                          "nV+hucyyGW9nqOhAhekqU8TNeGnz4pEf333vU+xPUdI0Qeo02yzkIY46NDvv" +
                                          "GCbjtzGLcSqYPkEamaWPyP0JUg/vScNiCjqdybhMTJAaU4LqbPkNJsoACTRR" +
                                          "E7wbVsYuvTtU5OR70SGE1MNDIvDsJepvBy6CsETOzrME1ahlWHZihtuov5uA" +
                                          "ipMG2+YSaYj6+YRrFziEYMLm2QSFOMgxb8PB/OKJo0YeImnWYZoB8c2x9oxT" +
                                          "Swfl4hhuzv+LURE13rwYiYAzrguXAhOyaNw2dcZT2kphePTKs6nXVJhhani2" +
                                          "EuRG4B1XvOOSd1zxjlfnTSIRyXILyqB8D56bhxoAOM2Ds8cPnzy7OwZB5yzW" +
                                          "oN2LMil3lD7gYEhWmf6fnHUe/dXP/vDRKIn6laItUOJnmRgKRCfS7JRx2OHL" +
                                          "cZQzBnhvPTLz1YcuP3hMCgEYezZi2I/rCEQllFooWV985fSb77y9dilaFjwm" +
                                          "oDwX0tDlBGmgaahtVBOCNJaLlFJsy/vwF4HnX/igjghQAdc54kV9bznsHSdg" +
                                          "joh83yZI/D90g+cCtOLOamVFlsS1+1dW9enHblDJ31mZqqPQiZ75xT9/En/k" +
                                          "t69uEBONwnY+YrIFZgZEjSLLipliUlbcUn9OaW+1Xvjd9/qzw1FSkySdYKsC" +
                                          "NXE6OMSz0He0ea80N6dh0PD7fW+g3+Ogwm2N6dBuqvV9j0qDvcA4wgXZEqBQ" +
                                          "mkaw7u6rPguERX/5/j9uP3owd1IGX7C7I7daaEx4cgZ7crn37gqZP0zyycmn" +
                                          "X71tr3YhKtsRlvYN2ljloaGgI4ApZ9B3LVQHIS3AdHc4y8PWSmn7eukLqRfP" +
                                          "9EsvNEJPFhRqKLS7njDzipYyVEo6ZNUARsjYPE9N3CqZvEnkuL3oQ2T56VA5" +
                                          "AAEi03sPPL1e0ZW/uNvl4NqtypXE75FrHy79KrrwdQCXvRLtwxBte/28hi5h" +
                                          "QgFFj/TfYYHbIRlo2mRYcf7RNnDDC38+164C2QRIyUX7P5iAD//QMLn3tRN/" +
                                          "75FkIhpOKX7t8dFU69vsUz7EOV1COYr3vbHz6y/TR6GJQuNyjWUmexHx6h4K" +
                                          "NSLVPijX4dDeKC6fgJ4LjuRig+oLbAevMd1yOCGMBW8+SJzpfGf+m+8+o9I/" +
                                          "PEyEkNnZla+8Hz+3oiyoJq4964ae4Bk1dUm526W7sCD1XYuLPDH2++fOfP+J" +
                                          "Mw9GPZ3jgtQs2IYOh/urqBaYoVPa+Uvvtdz53ktXpKCVQ3iwU0xSR8nWgcsQ" +
                                          "ytYd7lXj1M0B3scuTn223bx4FSjOAUUNurE7zaFpFiv6ioddW//rH/6o6+Tr" +
                                          "MRIdI02mTfUxiuMuDC2QG8zNQb8tOp+6RcX/YgMs7dLBZJ3L1wEwrHZtHLCj" +
                                          "eUfIEFv+bve3Dzy++rbsUaqP3FiZf33wDHj5N/A/5V/1SD1+jb0ULp+B5IEh" +
                                          "boMYxt3D8uAULncrM9z+X1oMAXc5RZjkqw8raNZt665JarTXnl1ta+heveOX" +
                                          "slaWx+9m6C6ZgmkGSnGwLNc5nGUMqW2zijJH/mQF6a7SxXGQkC9Sh4zCPwU3" +
                                          "2DC+ILXyN4iXF6TJxwNS6iWIAj07Bij4etpxipHKgats7q0fZO7AjLanIh/l" +
                                          "dbTU6ArqQprSnls9PHXPlY8/pkY2uMguL8vrC9zGVPcoN8u+qtRKtOrGB6+2" +
                                          "Pt84UCoNHUpgP2R3BKLsLpicHPTs9lAddvvL5fjNtQMv/fRs3RuQ2cdIhAqy" +
                                          "+VjgMqhuPlDMCzDVHEv6c03g3xmyQQwNfmPp4P7MX34jc06ObDBsV8dPaZce" +
                                          "P/7zC9vWoJFsmiC1UPVYcQ5utu6tS9YRpi3wOdJiuKNFEBGowFV7gjQULON0" +
                                          "gU3AJboVg5DiRVXaxTNnSxmKDV+Q3euL8/qpCerTIuPDdsHS5fgAFdOHVNyT" +
                                          "S/NGwXFCB3xI2ZVb1uue0m79ctsPznfGxiCRKtQJkq93C+nyLBO8OqvhJtBL" +
                                          "1OwcSyUnHac0S5Npr+Ddp3AQLkhknwfFuhBRIzV+PiDJfUG+4vKlfwMlFt/6" +
                                          "FRMAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028785000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05eczjWH2eb46dnV12ZhfY3S7ssscs6mL4nNg5NVyJ7SRO" +
                                          "fMWOk9i0zDq2YzvxFZ9J6LYLbYGCRFG7tFSC/QvUFi2HqqJWqqi2qlpAoEpU" +
                                          "qJdUQFWlHhSV/aOHSlv67HzXfDOzW1SpkfLy8t7vvp7fzy98DzofhRAc+M7G" +
                                          "dPx431jH+wunuh9vAiPa79NVXg0jQ8cdNYpGYO269vgXLv/rDz5qXdmDLijQ" +
                                          "q1XP82M1tn0vEozId1JDp6HLx6ukY7hRDF2hF2qqIklsOwhtR/E1GrrrBGoM" +
                                          "XaUPRUCACAgQASlEQFrHUADpVYaXuHiOoXpxtIJ+GjpDQxcCLRcvhh67kUig" +
                                          "hqp7QIYvNAAULub/x0CpAnkdQo8e6b7T+SaFPwYjz/3qu6/81lnosgJdtj0x" +
                                          "F0cDQsSAiQLd7RruzAijlq4bugLd6xmGLhqhrTr2tpBbge6LbNNT4yQ0joyU" +
                                          "LyaBERY8jy13t5brFiZa7IdH6s1tw9EP/52fO6oJdL3/WNedhp18HSh4yQaC" +
                                          "hXNVMw5Rzi1tT4+hN5zGONLx6gAAANQ7XCO2/CNW5zwVLED37XznqJ6JiHFo" +
                                          "eyYAPe8ngEsMPXRbormtA1VbqqZxPYYePA3H77YA1J2FIXKUGHrtabCCEvDS" +
                                          "Q6e8dMI/32Pf+pH3eD1vr5BZNzQnl/8iQHrkFJJgzI3Q8DRjh3j3m+hfUe//" +
                                          "0gf3IAgAv/YU8A7md37qpXe++ZEXv7KDed0tYLjZwtDi69qnZvd84/X4U82z" +
                                          "uRgXAz+yc+ffoHkR/vzBzrV1ADLv/iOK+eb+4eaLwh/Lz37G+O4edImCLmi+" +
                                          "k7ggju7VfDewHSPsGp4RqrGhU9CdhqfjxT4F3QHmtO0Zu1VuPo+MmILOOcXS" +
                                          "Bb/4D0w0ByRyE90B5rY39w/ngRpbxXwdQBB0B/hCZ8D3jdDu87p8iCEDsXzX" +
                                          "QFRN9WzPR/jQz/WPEMOLZ8C2FjIDUb9EIj8JQQgifmgiKogDyzjYCPL8CpGR" +
                                          "7YJIEgNDs0F8h3lR6KmeDpTbz8Mt+P9itM41vpKdOQOc8frTpcABWdTzHd0I" +
                                          "r2vPJW3ypc9d/9reUWoc2CqGUMB7f8d7v+C9v+O9f3ve0JkzBcvX5DLsfA88" +
                                          "twQ1AMDc/ZT4k/2nP/j4WRB0QXYut/u6SMoHiz9nAd5Tt6/YnbxcUEWJ1EAE" +
                                          "P/gfnDN739/8eyH3yaKbE9y7RZacwleQFz7xEP727xb4d4L6FKsgnkDqP3I6" +
                                          "V29IrzxpT9sTlN1juuhn3H/Ze/zCH+1BdyjQFe2gpo9VJzFEA9TVS3Z0WOhB" +
                                          "3b9h/8aatEvAawe5H0OvPy3XCbbXDgtorvz5k34E8xw6n18qYuKeAubeH4LP" +
                                          "GfD97/ybeyJf2GXCffhBOj56lI9BsD5zJobOo/v1/VKO/1ju49MGzgV4mxh8" +
                                          "8i/+5B+wPWjvuKhfPnFMAiNcO1FIcmKXi5Jx73HIjEIjN9Zff5z/5Y997wPv" +
                                          "KuIFQDxxK4ZX8zGXGJyK4HT5+a+s/vLb3/rUN/eOYuxsDE7SZObYGphExSEH" +
                                          "NJnbnuoUBnk8hh5YONrVQ63H4NADgl1dOPXCVK8Fx3whWu6V/d1JUSQXkOjq" +
                                          "bcL1xOl+XfvoN7//qvH3f/+lmyL1RsMwanBt56FCqjUg/8DpLOqpkQXgKi+y" +
                                          "P3HFefEHgKICKGqgTkRcCNJ5fYMZD6DP3/FXf/CH9z/9jbPQXge65Piq3lHz" +
                                          "gxiU09gCZ7cFKsE6eMc7d+UwuwiGK0VuQoX+r9uJU6T1PceGoH1wYH74bz/6" +
                                          "9V984ttAjj50Ps1jGEhwwlpskj9DvP+Fjz1813Pf+XDhE1B8x88++c9FRW4U" +
                                          "DJ4sxh/PB3jnsXz65nx4Sz7sH7rpodxNYlEXaTWKGV/Py49eeOplSwcfgoIV" +
                                          "2+nBAYk8c9+3l5/4+8/uDr/TdeIUsPHB5z70w/2PPLd34pHjiZtO/ZM4u8eO" +
                                          "QuhXHbnysZfjUmB0/u7zz/zebzzzgZ1U9914gJLg+fCzf/ZfX9//+He+eotK" +
                                          "fc7xD4MyH9EDtvlP9ZUdG9/1c71KRLUOP3RJVtFMEzAv2SZIxdOGnGjwsi1g" +
                                          "FstuAkukxlaTkONJ0mvU2DXqDHpVYoBxmIE19HqieDOODyMyVqfDjGr4uF2J" +
                                          "bX41XW3rkrNujamuObZIYdZR2iq1ws14uWj4RGZ37V57kREOjM7QWTqfpJbY" +
                                          "tgYTHUUw14WRZnfRbLq6WPP4YSY2Rp1lxGvwwHQU28LcUdWWYq2Jh7jU9HAG" +
                                          "SadkUmYwoeTpva7HSlNd9DeVGVO1gwRjlwHarQLrqlpNk0tIjyS6WlLJYqlL" +
                                          "y2WhLqv15chghhhL9jl0axHWKFqNAooZZHK5NJy1+otKy+SqjClK/cFyYUqY" +
                                          "VR0s3RmrB0qj2S21m/1ei3Bpdz6uJRSH9SVMbPfNEGfabD9bjwlBqiU6ut4O" +
                                          "JqlKRbUB5dUHKbPcZkYPcI6ZiE+rcdjUeaUZOpuZPMIxuuNQzWZmbWdTrl2T" +
                                          "PLG6ZHsjRcFGVZ5flm1x1vJNvDmY00SHbbEMyeDloIZy7SaOMYNE6M0GLjfo" +
                                          "dFfadiiJfRwWbYqrjkbpUnEFxuQ67aQX0CZMxGHZmSmTSa0sNGp8SG4ixkPD" +
                                          "xphCy9uAQTPFITVCHg6z7pAjmHCjajN9WA+5JuGJstzdKusltuouI6NaT3QK" +
                                          "jQRJamOdxgbPKJpIODFAG2ED5/21mahRz1FSOWMGHByyLi/S3EKtGsmKba8J" +
                                          "Dl/ICtU2eZKx6mG2YOdcNxgmmwG2scMujwQZ2V7EM8/VFooylssdU2rVxkNL" +
                                          "dqjQrdqdEs1tzE4QDrP2ZjhTpn15heorEx3VmcgSSCULYmFSIcaDFtoWspHS" +
                                          "Xaojh2nTaIk18HThNWKxrSG6XCmrkkC2XW+ydDdho0+kE5KwylZXk5UqRdZQ" +
                                          "Okvh0VRtGrQywLutlJiQYQ+HG/VlGMPbNJnbgyx21y2tWoKt0Uggg5lYN+B5" +
                                          "jFEVprTuDPh2NC4R3hi2Em2z6U6a3oqzWpaxXEmNEWt0vW0lIOcYhqUSvOYl" +
                                          "nSoNDb+EbrZLSq7UWCJNu/hsEW+7tCauZH5Jqq464Td8qS+ZSCpqrI0vVvpm" +
                                          "ZjGjfkuVKvRqxi/ZfuS38JEgkPVsNo7kJB3FUpUT6iWxS5YZlqBSIuobQdre" +
                                          "1PCIHHHbkCHLquVMeiDj4sRPq0nLDpguCsuiKi9qsCyEna1NygztokOxwzHm" +
                                          "etbg2wg36Psl2aCABWXFbzc0dN301yMxmzsVy0q2KUwDA5exMJNtubUNzWTa" +
                                          "sriNymaorikjdBlYBj8aRDVvOu5bFnhuRslE6Fba5WnKcaJe3q4XztwbiZSw" +
                                          "mVL0ZtVuENXazFr7LY5Biaih8d52U+cypV3dbCc+i9KM7WAOUTdl0pq489rc" +
                                          "60kGok95JCUEkIw1R6Viiet7rmAOBHwu1vvCGuV6tKYMt23PSvkRvS3LWsJj" +
                                          "FoObpGxsFRulkBAnh47T8f3JuNmozsVZvb5p6rajdhaZC2rctBQTTrvrmqpq" +
                                          "xeM2h7N9lXY6/WiDpFmn0vOmiG0uTGvY0rVqZTluzrZe1BN1c+FbDWyjUAjR" +
                                          "LJmwhscczanuuONEYhku65Om4fVmDtHHyq6yWvFDW6lX16MmQnrIMq41E7LN" +
                                          "sZknw3JIdRRTIRciTduBY0vOTJO8JqdOYGDMhd5EVtus3BGXG1GXBxHOTska" +
                                          "x4jbUs8oGWqjxNZ0q8QT9fkENjGYMzMXBUvtZJWOm4vSiki1ViUzpwq5ag/d" +
                                          "pZrVk1rImwkpTJEqsmgCe/mZXqa60zpep+q6qpLrimYqdS30sLq5UvjSdrPR" +
                                          "XG9aL8chJluDOBKcVGZRZwGqddekKq1AabYxejzsUSLW0ntaZdPgJ6Lr1Y1k" +
                                          "Sa+EOd8koxQUbr5jCasBLda9BbG1A3kzJv2awkotIVrIPNlkMXylpKS3TGjM" +
                                          "H6Kjam3cqrZapF3CIp6ny0ZJmSAJmzoVdgXO7ClZr3bC3qbeHIRhpg/xaSrQ" +
                                          "cbZuxwaCNiy7ag3NTmeBjOay3JtRguOjriBr87rAegSBYw24XKvg6FCgNtK0" +
                                          "zlftFoEgQ4b2sFhgEUB7SVkBN5jW44bekWrNNJK2dZIbl3FODrF01tvWNshI" +
                                          "qHX7w4TdLCaSa6x765pVGbAiPebtxbSiE8YAr83NfoVeJIJtwj49axkpo5c3" +
                                          "HN5l2pMGLPa3wbw7h124AftNCuHJDblkPcVR4UZvC2O+vfH7q0qzVlGNSntZ" +
                                          "1iW3itYm9QgnylM5oXmih8LwnJvzcJ/Jml1ewRZmPIxQSuYsJAlXbVX2x7wK" +
                                          "S2ka69sqtoynwQAfDzE7k0prUWh4E1OLhptY1uvOdFFmSm0s0pKRh6LYbF3p" +
                                          "iAuuJUlsEpL1rdoJOnZas31dnyBI2ENqfg0ehYxAgQqIuqO5tLYTJiGAVbuN" +
                                          "LTucNWIugGuCNkVkk4nqOt1W+hhdzsgs7Clxj8YXhjSnyE4Kz1IDI7YbGA5n" +
                                          "kaSueKxjK6DAZkRvUWWRFlIdI2WRKMOLWUmiA7gN6rw18xl5HWNEI2lJtKeF" +
                                          "THMLT8s+05pqVUFZLFdZI1RZJa7Vqn01HE09pxyrsGWkBjeNHHWyhptuDa8p" +
                                          "prvsil43o1mt6nUlZjVBt/ai30PcYaem1sX1tDtc4k3RqmxxPpMwlMBhip5u" +
                                          "2Io97dRG/XXGijV7QrUWpXrbXlSMOFjbQW9gqnFUX5XmCldvLWjVoyzE0Wcj" +
                                          "qdYKV8MgFD0navK9Ke/IDSRYymjCmAndSEO8ue2Oec1nGwm8ioVBzIXddg1G" +
                                          "+bhRkXCf7UmByaMC1h7QER3YWo8fRU2npetpSlfnCzYeMikyFyJMSIaoplNW" +
                                          "a7WBxwuTWVkJ7xAMviXGPTKtaSXMxNbuBjw5sHOXDyp8nZlilYVWqnEzAhyB" +
                                          "DZ1XFc3gkfoWb6YTv9+JXBsvS/xY1obVJE5qsdiUhcDGMk7v28mA7ZDtrp91" +
                                          "xnVzMZRoji2BJ7FWf+aPzSphC+Opuh6xnrh2B8QYHmIGUBdZBbgRjqiEJ3RQ" +
                                          "Watzs9XRud6Y3YxEhO1m0w7extYUqoxn5SQxSm69qcURv/Xm3bWNA+MM+8tV" +
                                          "E8Nhb0O3uQa3Sq1+3KbLXKaJG8nrqVpJrLJBCBN6gLWG9NJaetm8k1htgdqO" +
                                          "Yd4m+nOpC1fSgTPPGKcTI7WOwICH7re9LX8cp360G9G9xcX1qN8JLkL5RulH" +
                                          "uAmsX45hDF1UZ1EcgutiDN151IDdcT/RuTlzeFHe/192jA66RfnF6OHbdUCL" +
                                          "S9Gn3vfc8zr36XJ+Kcp5EECO2A/e4oCsck5IsAcoven2F0CmaAAfN2m+/L5/" +
                                          "fGj0duvpoktxU/OIhi7lmHzeZz/qp7/hlJynSf4m88JXu2/UfmkPOnvUsrmp" +
                                          "NX0j0rUbGzWXQiNOQm901K4JocdvujX6mqEnoXHM902Pql+8/qVnru5B5072" +
                                          "sXIKD5/qCt0190NXdXIGh73wS7EV+tnxyskWETBr0aN7AnwfPWiWFr/57quD" +
                                          "fHzN+jjUboqhvaOgFQ4iJoTeeNydwH3HMbTC6lclzy0u8+rMMfJO4X9efrL8" +
                                          "xX/6yJXdVdcBK4duePMrEzhe/7E29OzX3v1vjxRkzmj524Xjfssx2K5l/epj" +
                                          "yq0wVDe5HOv3/unDv/Zl9ZNnoTMUdC6yt0bRQ4YOmpe5UFahtlaM5qm9RT7k" +
                                          "bwmAs8L4Fl3TAusdJ3IUB3f51Lf14+R9+pWu8SeZFgvvutF9j4Hvkwfue/L/" +
                                          "5L7bK5q9zN4mH0Jge8PTb2GCfNc5Vjf6UdRdx9BDt+9F50598Ka3YLs3N9rn" +
                                          "nr988YHnpT8v0ubo7cqdNHRxnjjOyfbpifmFIDTmdqHVnbtMCYqfZ2PogdtU" +
                                          "vrz5WEwK4X9mB/+zMXTlNHwMnS9+T8K9P4YuHcMBUrvJSZBfiKGzACSffijv" +
                                          "0p6oiQfhUJj1vlcy6xHKyTZrXkeLt42HNS/ZvW+8rn3++T77npdqn961eTVH" +
                                          "3W5zKhdp6I5dkTmqm4/dltohrQu9p35wzxfufPKwxt+zE/g4NE/I9oZbpz/p" +
                                          "BnGRsNvffeC33/rrz3+raDX+D3zG4JIGHgAA");
}
