package org.apache.batik.gvt.event;
public interface GraphicsNodeKeyListener extends java.util.EventListener {
    void keyPressed(org.apache.batik.gvt.event.GraphicsNodeKeyEvent evt);
    void keyReleased(org.apache.batik.gvt.event.GraphicsNodeKeyEvent evt);
    void keyTyped(org.apache.batik.gvt.event.GraphicsNodeKeyEvent evt);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028784000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Ya2wcVxW+u+t3/E5ih6R2Xk6Ek3RHKRSpOITGjp04XTuW" +
                                          "nVbKhmZzd/bu7sSzM5OZO+u120AJQk35EUWp0wZE/ctVAfUlRAUIWgUh0VYF" +
                                          "REsEFNQWiR+UR0QjJPgRoJxz7+zO7NibIl6W9u7snXPP+5zvXD99ndQ7Nuln" +
                                          "Bo/zeYs58VGDT1HbYZkRnTrOMdhLqY/H6J9Pvjt5V5Q0JEl7njoTKnXYmMb0" +
                                          "jJMkfZrhcGqozJlkLIMnpmzmMLtIuWYaSbJec8YLlq6pGp8wMwwJ7qN2gnRR" +
                                          "zm0t7XI27jHgpC8BmihCE+VA+PVQgrSqpjXvk28IkI8E3iBlwZflcNKZOE2L" +
                                          "VHG5pisJzeFDJZvstkx9PqebPM5KPH5av9NzwZHEnStcsO35jr/cvJjvFC5Y" +
                                          "Sw3D5MI8Z5o5pl5kmQTp8HdHdVZwzpBPk1iCrAkQczKQKAtVQKgCQsvW+lSg" +
                                          "fRsz3MKIKczhZU4NlooKcbK1molFbVrw2EwJnYFDE/dsF4fB2i0Va6WVK0y8" +
                                          "vFtZfPxk59djpCNJOjRjBtVRQQkOQpLgUFZIM9s5kMmwTJJ0GRDsGWZrVNcW" +
                                          "vEh3O1rOoNyF8JfdgpuuxWwh0/cVxBFss12Vm3bFvKxIKO9XfVanObC1x7dV" +
                                          "WjiG+2BgiwaK2VkKeecdqZvVjAwnm8MnKjYO3AMEcLSxwHjerIiqMyhskG6Z" +
                                          "Ijo1csoMpJ6RA9J6ExLQ5mRjTaboa4uqszTHUpiRIbop+QqomoUj8Agn68Nk" +
                                          "ghNEaWMoSoH4XJ/cd+EB47ARJRHQOcNUHfVfA4f6Q4emWZbZDOpAHmzdlXiM" +
                                          "9rx4PkoIEK8PEUuabz544+49/VdfkTSbVqE5mj7NVJ5Sl9Ptr982MnhXDNVo" +
                                          "skxHw+BXWS6qbMp7M1SyoMP0VDjiy3j55dXpHxx/6GvsD1HSMk4aVFN3C5BH" +
                                          "XapZsDSd2YeYwWzKWWacNDMjMyLej5NGeE5oBpO7R7NZh/FxUqeLrQZT/AYX" +
                                          "ZYEFuqgFnjUja5afLcrz4rlkEUIa4UMi8NlL5F8fLpwwJW8WmEJVamiGqUzZ" +
                                          "JtrvKNBx0uDbvJKGrJ9VHNO1IQUV084pFPIgz7wXuSJUZxH70yGbWnlNdSah" +
                                          "I93D5rH9oF1xTDfr/yWohBavnYtEIBi3hVuBDlV02NQzzE6pi+7w6I1nU6/J" +
                                          "NMPS8HzFyR0gOy5lx4XsOMiOC9nxGrJJJCJErkMdZOwhcrPQA4CgdXDm/iOn" +
                                          "zm+LQdJZc3Xo95Ioyk3lH3AwpKso/0/MWE/84se/+0iURP1O0RFo8TOMDwWy" +
                                          "E3l2izzs8vU4ZjMGdG9dmXr08vWHTwglgGL7agIHcB2BrIRWCy3r86+cefOd" +
                                          "t5evRSuKxzi0ZzcNKMdJE01Db6Mq56S50qSkYeveh78IfP6BH7QRN2TCdY94" +
                                          "Wb+lkvaWFXBHRDxv4KTXt2EUfV/2Nbqrr1b/EL1v+dziUubok3tllXdX1+Qo" +
                                          "QM4zP/v7D+NXfv3qKsFv5qZ1uw7B1gM6xVBk1fAwIVprGYhT6lvtl37z7YHc" +
                                          "cJTUJUg3OMWlOo4BB+wcAIw66/Xg1jRMFD6wbwkAO04ktqmyDOBKLYD3uDSZ" +
                                          "RWbjPifrAhzKYwc22F21QT+s+svnfr/x2P78KZFlQRhHafWAQHhyCsG3ArKb" +
                                          "Q+4Ps/zqxNOvHtqpXooK3MEevgpeVR8aCgYChNoMANZAc3CnDYRuC5dz2Fsp" +
                                          "ddcW+kLqxbMDIgrNAL6cQrMEXOsPC6/CjqFydaGoJnBC1rQLVMdXZZe38Lxt" +
                                          "zvk7os90yWSHBBF1fDt8tnvdVXzj2x4L117ZlwR9v1i34jIgsiuKjztw2SnI" +
                                          "PgzZttNPfoADHTolRmTgXgPCrmU1mtYZ1sPfOnbsfeGPFzplIuuwUw7Rng9m" +
                                          "4O9/aJg89NrJv/YLNhEVxxG/yfhkEuPW+pwP2DYVPbD02Tf6vvgyfQLQEhDK" +
                                          "0RaYAJ1IdUUr/3pjFRUvvDEiTu8X6zB61Wua+PsQLh/npGWWzeM0DpMeKDh4" +
                                          "i4HX1grQKoveyKCc7X5n9svvPiMbRXi+CBGz84tfeD9+YVH6Wg5h21fMQcEz" +
                                          "chATmnaKwGLr2norKeLE2G+fO/udr5x9OOpZGeekrmhqaNpADdMCY3VKvXjt" +
                                          "vbb73nvphlC0ei4PgscEtaRuXbgMoW69Yfg6TJ080H306uSnOvWrN4FjEjiq" +
                                          "ANDOURtwtFQFNR51feMvv/f9nlOvx0h0jLToJs2MUZyAYY6BKmJOHiC4ZH3y" +
                                          "blkpc02wdIqQkhVBXrGBCbh59dQeLVhcJOPCt3q/se+ppbcFbElouaO6UuPw" +
                                          "GfQqdfA/qtTq3PTyHX8eFASpWyQvxSXJyRpI3mmmM0CGDG4lBPUULiekA2b+" +
                                          "TV/hxvFVHbAbPornAOV/6QD9Fg4Q80oOBglwACZ/2Pr8f8P6EgwSNYY2zKUN" +
                                          "K66L8oqjPrvU0dS7dO/PBZRUriGtAL5ZV9cDSBVErQbLZllNGNcqS8sSX0W4" +
                                          "WdXufZzUi29hgitPzAO0r3aCkxisQcoH4dYfpgSO4jtI9xlokz4dzHHyIUhy" +
                                          "DrgDCT5+zrJKkeohtRKX9R8Ul8Bcu72qYYkrfHlmcOUlPqU+t3Rk8oEbH3tS" +
                                          "jrlw+V9YEFc+uMFKIK7MHVtrcivzajg8eLP9+eYd5d7ZJRX2U3pTIAGPQ6pa" +
                                          "mAUbQ5DmDFSQ7c3lfS/96HzDG9D6TpAI5WTticAFWt4WARddGBBPJPwRMfAv" +
                                          "IIG1Q4Nfmt+/J/unX4mmJEARLii16VPqtafu/+mlDcuAyWvGST3AAislSYvm" +
                                          "HJw3pplatJOkTXNGSyKXuUb1cdLkGtoZl41nEqQdE5bi5V74xXNnW2UXZydO" +
                                          "tq1Er5UDKDTwOWYPm64h6rMNIMXfqfrfQnl0cy0rdMDfqYRy3UrbU+rBRzq+" +
                                          "e7E7NgZFV2VOkH2j46YrY2Hw3w1yTgyArbxvxFKJCcsq3z/qfuIhwqOSBvc5" +
                                          "iezydkM97DHB7rJ4xOXKPwGSUIhKSRQAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028784000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05eczk1l3+vr03aXaTtElIm7RJNhXptJ/nPrS9PDOe8XjG" +
                                          "Y49n7JlxoRvf9vgc3+MSlEYqragIBba0QJu/UgFVeghRgYSKghC0VSukoopL" +
                                          "0FYIiaNUav7gEAXKs+e7N5tQVTCS39jPv/e7j/d+fuG70DnfgwquY25U0wn2" +
                                          "5CTYW5m1vWDjyv4ePqpRvOfLUsfkfX8G5m6Ij37+yr9+/yPa1V3oPAfdy9u2" +
                                          "E/CB7tg+LfuOGcnSCLpyNIuasuUH0NXRio94OAx0Ex7pfnB9BN1xbGkAXRsd" +
                                          "sAADFmDAApyzACNHUGDRa2Q7tDrZCt4O/DX009DOCDrvihl7AfTISSQu7/HW" +
                                          "PhoqlwBguJg9s0CofHHiQW86lH0r8y0Cf7QA3/zYe6/+1hnoCgdd0e1pxo4I" +
                                          "mAgAEQ6605ItQfZ8RJJkiYPutmVZmsqezpt6mvPNQff4umrzQejJh0rKJkNX" +
                                          "9nKaR5q7U8xk80IxcLxD8RRdNqWDp3OKyatA1vuOZN1K2MvmgYCXdcCYp/Ci" +
                                          "fLDkrKHbUgC98fSKQxmvDQEAWHrBkgPNOSR11ubBBHTP1nYmb6vwNPB0WwWg" +
                                          "55wQUAmgB2+LNNO1y4sGr8o3AuiB03DU9hWAupQrIlsSQK87DZZjAlZ68JSV" +
                                          "jtnnu+O3P/s+G7N3c54lWTQz/i+CRQ+fWkTLiuzJtihvF975ltEv8/d98UO7" +
                                          "EASAX3cKeAvzOz/10rvf+vCLX97CvP5lYEhhJYvBDfF54a6vv6HzROtMxsZF" +
                                          "1/H1zPgnJM/dn9p/cz1xQeTdd4gxe7l38PJF+o+XT39a/s4udHkAnRcdM7SA" +
                                          "H90tOparm7LXl23Z4wNZGkCXZFvq5O8H0AVwP9JteTtLKoovBwPorJlPnXfy" +
                                          "Z6AiBaDIVHQB3Ou24hzcu3yg5feJC0HQBXBBO+AqQdvfQ9kQQDKsOZYM8yJv" +
                                          "67YDU56Tye/Dsh0IQLcaLACvN2DfCT3ggrDjqTAP/ECT91+oEYjOCEDDfY93" +
                                          "NV30x44kD+VNlhcyufYyd3P/vwglmcRX450dYIw3nE4FJogizDEl2bsh3gzb" +
                                          "6EufvfHV3cPQ2NdVAJUB7b0t7b2c9h6gvZfT3rsNbWhnJyf52oyHre2B5QyQ" +
                                          "AwDAnU9MfxJ/8kOPngFO58ZnM70neVA+kD+cAeueuH3G7mXpYpCnSBF48AP/" +
                                          "QZrCM3/77znfx5NuhnD3ZaLk1HoOfuETD3be+Z18/SWQnwIe+BMI/YdPx+qJ" +
                                          "8MqC9rQ+Qdo9wlv+tPUvu4+e/6Nd6AIHXRX3czrLm6E8lUFevaz7B4ke5P0T" +
                                          "70/mpG0AXt+P/QB6w2m+jpG9fpBAM+HPHbcjuM+gs/vLuU/clcPc/QPw2wHX" +
                                          "f2dXZolsYhsJ93T2w/FNh/HousnOTgCdK+819orZ+kcyG59WcMbAO6buJ//i" +
                                          "T/6xsgvtHiX1K8fKJFDC9WOJJEN2JU8Zdx+5zMyTM2X9zcepX/rodz/4ntxf" +
                                          "AMRjL0fwWjZmHIOqCKrLB768/stvffP5b+we+tiZAFTSUDB1Edz4eZEDkii6" +
                                          "zZu5Qh4NoPtXpnjtQGoWFD3A2LWV2chV9TpQ5nPWMqvsbStFHlyAo2u3cddj" +
                                          "1f2G+JFvfO817Pd+/6VbPPWkYgjevb61UM5VAtDffzqKMN7XAFz1xfFPXDVf" +
                                          "/D7AyAGMIsgTPumBcE5OqHEf+tyFv/qDP7zvya+fgXZ70GXT4aUenxVikE4D" +
                                          "DdRuDWSCxH3Xu7fpML4Ihqt5bEK5/K/fspOH9V1Hihg5oGB++O8+8rWff+xb" +
                                          "gA8cOhdlPgw4OKatcZjtIX7mhY8+dMfNb384twlIvuzTj3/n6QxrMyfweD7+" +
                                          "eDYUthbLbt+aDW/Lhr0DMz2YmWma58UR7weEI+lgDyHllnrF1EF5ugW8Ldov" +
                                          "kPBT93zL+MQ/fGZb/E7niVPA8odu/uwP9p69uXtsy/HYLVX/+JrttiNn+jWH" +
                                          "pnzklajkK3p//7mnfu83nvrglqt7ThZQFOwPP/Nn//W1vY9/+ysvk6nPms6B" +
                                          "U2ZjeZ9s9ld7dcMGd/w1VvUHyMFvVFry5Vhkk3khLAQVGK3pWp0uL4w6alRo" +
                                          "bEhPXXIw66/cYnUxC+c2Kww1i0slWAgb/jQlaiRHFsJSuYjgE6NSQ5m5W4w5" +
                                          "FBYDFlEYk0aYwVxltCK77NGoj/bGk7lOFxi6OFnhlEo7eJI2CinZGOvCwKzP" +
                                          "WwCrvaCoQi2NFt1Wy5YmjXFo2m0HTuWlX2uy/e6shAlLzqDtmUcSkjZaL2Gs" +
                                          "jreoaBXU2NqkiKNmw145s6G9WFqEUFzhhKFwnib2106Km8ZoQNiulVrEKBiE" +
                                          "8yU/FXBZbC5H5rru9t1mTMQx3liPy6pN06lVDBqLQbmxwlS302xbutZBCyxS" +
                                          "oNiJ6k3X7moRGeXmwBg00YreNmNOMcXxkCPR8ojF+jVX9/FU7nVxLvIDI2lR" +
                                          "a1mgiNqQwmp81BqnMYehYDcu+mSltvJgMcJXUa9TW07jSrdGDJpczam5Zs2w" +
                                          "JjO3iUmYxHJx6rYpo6R3PMSYiOlwMkQCdjJUOxM/mhfMqarQflohhoOhmGoc" +
                                          "Ux2bjjMUhWHJcsyewHpxGY1xe9nrorDk96pKu6wXWb4+Z4fFTTPqBZxCJUat" +
                                          "Ja3czhgnV/SqHbD0ZGKQE3ekMj1uQLT8mkFY8QzHi3266/fnnMeOxXmEahWy" +
                                          "5JHOeNNr4oqkumGYzGOtCAP3avd8v1RmrYrQi4bJYEi2FgrL26TQKSUNiZ2v" +
                                          "9H6h3Fb1mB+WWWMoy6K05iJ2hcS21STs4WpJVhACFUfTJMZWsjfQ18RG841+" +
                                          "nRusnJLoO4SL12mkhdfRZDSpWfRqxgsOXw3XfjrDGFenB4LjFiZrx3KYVRNR" +
                                          "7XpzbKjaGOXnhDN1sOoCh0WpgLarDYTGaWxCimMGU1gFqSr1SVW25pzAdUkX" +
                                          "waxUMhc60fKSKmU4A3TYpFAm5IW0Vq0Wqi2YlRRjNhXYNVqzVo0xi9emZosK" +
                                          "vFazTNjaojtmHd9IsLjQXsyn9bVAuA2iNN04BFVkuyt9U1nVatLCxZIErvcj" +
                                          "v1vCpoRR5dneuNKptbEF73J+dyqVl/IynqfD+ZwXx11iRWxG8qo27stozWm7" +
                                          "ZINujDkN7iXMWh55E24GI8sFt0R74Vrt2Stmxdd4ZSR6adUzDZQZ8FWG0Jtj" +
                                          "E+y+msrIBUEwb84tFGd5S++vmZTDAy8ajttJMewKET7se3iLxcZkaTBh2GKz" +
                                          "6vaogZo24kU4xRkuwRrFTV+Y2+ZYmvLaoAX82cNaTq+UzLqKB2/mjtbmI3sZ" +
                                          "oIO2XtHYsN012WJ5PElTtO7qhUZcH5Rspg7jY4KaNrG0t6GLKrmpmUl14ZOE" +
                                          "TnZadgKYwPEOjnoGIXFkrIkeNUGqHVVadC1YJ+3UKowmEs6JlYXTqg2cjVEx" +
                                          "sQoSu0PfgYswMUfhZtWX4UJRZ2iqRBbpntOckUQ3nm/QilnW09RvRkyVWxF9" +
                                          "qd+SrIVXbEZzbBarptofNXh1gIntctsb0PPOpuI16wVRVkgpqMkRPQ2HSaoX" +
                                          "uRRkBELC0WKpK9SJda0+rRXXU2MJdtdaozlQqHoba0zocXnWkZat6lwomEbE" +
                                          "z3uLNkZ3k6g6nC2CMsooLFweC2vPKwkwOipFBSnVmVBwjEpgmgtpUSpMnAlR" +
                                          "TSk4anQL44USVdZDvxfV1lwpjBvtkkrUE7ZtlBQkHrCu119qs7oZBWalkTaW" +
                                          "mCjiMwZn1ApJzE3SqbbbhVhEBnG9Di/U0oomet16LMQGQharRrC2Nl2yPRwt" +
                                          "u5WwO+XoubCidMVDtHS4jMVyuVcuTWYFv+BHNrB2UqYazSHXMye0hvHKHJlg" +
                                          "2qbj9yuINxQmhSrlw+k6GZMRFqzdBchXFQKVI9WVWbrJd9RlRxs7BDLmELHS" +
                                          "sbtLOuzUpLTc811JEucFY7ROBKI7UL0xMqqLE49AF6RPdepwZ7XubSS+7+B2" +
                                          "u1PyJiOWkBYcJ1eaoyRII6Ph+K3iZj7F2u1eSekGzcCOJHaRrspJdVQqNTgz" +
                                          "pltRSa9UVwPV18PhKg3i8tQeUGrKBcGYUhyki80ck7Zm6kKlOp7FlKxgyZV8" +
                                          "SiFtwVfkPtVLXXMQhjETN2hbbVlVsgXzuNpsjT08gpejsYaySdKHN4pmoCE1" +
                                          "L7gxVe4uWUroFsszpR5F6kaZjCao1h0WaX6J4KWBxDAeXHFXPZqJoi6qz8Lm" +
                                          "op6266V5yBcofzLSYNvtz+epTBS7LiEPu1pVr2KLkupNhk4kb4YdsbGo2S0/" +
                                          "iiidEOiFXui0+2mzGihyt1VYslh9rta0ckkhJiKaihoys2x+GPdHXtl2vKE8" +
                                          "Qsv9gkLCoeTVkhZJulxflg3P0tb82EW6EtFZVthhtFgFkSA0KnbkamanKOtV" +
                                          "SvVFNODpcCGohDOvt5aKWp/hxWYRqxTr4dQmo7k3rvZW6EpfI+MuydBBHPQm" +
                                          "vTFdKykyEUWw0rJNMkqKWnE1mjm4XyYYboMsl/X20MJJTO9UOayyEUzDFYvl" +
                                          "WBqsJ4bGthdev90RNFDaJvKI1UScpDpBZQ37csF1BbEnoKYT8mSdCam4r0zW" +
                                          "koLA62C2rlCzDbZoyj1k6s43kyiZLvAN7Q4qlmURxU6/26+abYphRrpsIGWh" +
                                          "MGNhLYl6LCYgAuV4NkKycH3SbfXU6qRZdMi2asZIh4PLlNdUmlQdVePpeLks" +
                                          "p0NmPKzXR01nvaK8iClK04ZEwlSboxlP7wfIqMaxLbE7bbOoNxFGnGmO+2Nx" +
                                          "PW3600VxXp1Li1DhUkYvtzRVD6gURKpX4TtGovsTERQ4aam46pSsroJBKzEd" +
                                          "I61KKYZtBoy26XpqtzOrFVIPHxqyowX0cNGim4zZbItho7xeLg1PwUxLJBmT" +
                                          "WjNgp0gbTQcVsEowXXlmXGBboLKIhZDogY1Hg8DYwBP1KOVXalMeUa2CvJRq" +
                                          "UoPD6UWZqbizAdKnJnWXtxBGmNS6Vrc3nTTEiqlM4VYdS7v9Vrc+c5FBbT4D" +
                                          "ZzikNw+qc4SWpH67TeFUTBMKEg0G/dKkOlasoADjcGgvqpaFowg90vVSnaXW" +
                                          "Aa+EcMEyu2KIbOZRfzqrIIjum9NlZGF4XHFdkw9w0pgtxv3pZrgIGaEkSiOj" +
                                          "HzicWS3Z6HoioTVBr7GNarIY2/Mys+A2EhmsS6hXY7rD7iwm50vKqle1ukeM" +
                                          "B8RCWSueMrHNorgpehLRVdZLelNhPIEpeG06XRfkBtoYq1yPLbOkgZVX1frS" +
                                          "W5axuBKXNjN1g3hCEiW9Id4R/XUlhddKONDiNTltR2JNl9ONZBCtRhdrNzy8" +
                                          "mpCLIfDUKTPQhlN6Ajbz73hHts0f/HAnrbvzA/FhHxUcsLIXxR/ihJG8EsEA" +
                                          "usgLfuCBY2gAXTps7G6pH+sI7RwcwI8dhNGs/XTQbspOVg/droWan6qef+bm" +
                                          "cxL5qVJ2qsqQdQHBwHHfZoJCa55qPr3l9idIIu8gH3V5vvTMPz04e6f2ZN7m" +
                                          "uKX7NIIuZyuprFF/2JB/4yk+T6P8TeKFr/TfLP7iLnTmsOdzS2/75KLrJzs9" +
                                          "lz05CD17dtjv8aBHbzl2OqIshZ58RPctb+K/cOOLT13bhc4eb4RlGB461Va6" +
                                          "Q3E8izczAgfN9MuB5jnx0czxHhNQa97kexu4Htvvtub/2dt73Wx8bXLkU7c4" +
                                          "y+6hd9L7ruFBbz7yhI5jmrKYa/0aY1t5N4AXTDlzjv+88njpC//87NXtWdkE" +
                                          "MwdmeOurIzia/7E29PRX3/tvD+dodsTs88RRw+YIbNvzvvcIM+J5fN4TTd7/" +
                                          "pw/9ypf4T56BdgbQWV9P5bwJvXPSveH/faM1d/9cG1q+WsxHNQ+/bUc1e84/" +
                                          "FdwIoMuGvKE82ffl7dePdx0L204AnY0cXTqK5ydfrWNwnEw+8Z6Tht4D1xP7" +
                                          "hn7iRzL0SdH21ZU96jnA5hVkf182gLxyB5Cdlk2ZB8JnU/aRoOGPKmgBXPC+" +
                                          "oPD/paAfeAVBP5gNT4NcCgTNAvC0lO//YaRMQJK9TU8/8+0HbvmauP0CJn72" +
                                          "uSsX73+O+fM8exx+pbo0gi4qoWkeb0Mfuz/verKyFfDSNmG4+d+zAfTg7UMh" +
                                          "gM7l/znvP7dd8QsB9NqXWxFAZ8B4HPJmAF09DQkw5v/H4T4GouYILoDOb2+O" +
                                          "g/wqwA5Asttfyzrjx8rIvrvk+r/n1fR/uOR4azsrPfkX3oMyEW6/8d4QP/cc" +
                                          "Pn7fS/VPbVvrosmnaYbl4gi6sM3Lh6XmkdtiO8B1Hnvi+3d9/tLjB2Xxri3D" +
                                          "R657jLc3vnzGRC03yH0k/d37f/vtv/7cN/P27v8AanxLInofAAA=");
}
