package org.apache.batik.bridge;
public interface ClipBridge extends org.apache.batik.bridge.Bridge {
    org.apache.batik.ext.awt.image.renderable.ClipRable createClip(org.apache.batik.bridge.BridgeContext ctx,
                                                                   org.w3c.dom.Element clipElement,
                                                                   org.w3c.dom.Element clipedElement,
                                                                   org.apache.batik.gvt.GraphicsNode clipedNode);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVXa2xcRxWe3fU7fjuxTR5OnDoRebCrKhSpOITGrp1sun7I" +
                                          "TipY02xm787u3vjuvTdz59prF1CphAh/qiiktCDVv1xVrUqpEBUg0SoIibYq" +
                                          "ILVEQEEtSPzhFdEICX6E1zkz9+69e+2FX1ja8dyZM+c155zvzIu3SbPDyQgz" +
                                          "RVKs2cxJTplinnKHFSYN6jjnYS2nPZWgf734+9n746QlS7rL1JnRqMOmdWYU" +
                                          "nCzZp5uOoKbGnFnGCnhinjOH8RUqdMvMkl26k67Yhq7pYsYqMCR4mPIM6aNC" +
                                          "cD3vCpb2GAiyLwOapKQmqdPR7fEM6dQsey0gHw6RT4Z2kLISyHIE6c1cpis0" +
                                          "5QrdSGV0R4xXOTlmW8ZaybBEklVF8rJxn+eCc5n7trjg4Ms9f7t7rdwrXTBA" +
                                          "TdMS0jxngTmWscIKGdITrE4ZrOJcIZ8niQzZESIWZCzjC02B0BQI9a0NqED7" +
                                          "Lma6lUlLmiN8Ti22hgoJMlrPxKacVjw281Jn4NAmPNvlYbD2QM1aZeUWE588" +
                                          "lrrx1MXebyVIT5b06OYiqqOBEgKEZMGhrJJn3DldKLBClvSZcNmLjOvU0Ne9" +
                                          "m+539JJJhQvX77sFF12bcSkz8BXcI9jGXU1YvGZeUQaU99VcNGgJbB0MbFUW" +
                                          "TuM6GNihg2K8SCHuvCNNy7pZEGR/9ETNxrGHgACOtlaYKFs1UU0mhQXSr0LE" +
                                          "oGYptQihZ5aAtNmCAOSC7G7IFH1tU22ZllgOIzJCN6+2gKpdOgKPCLIrSiY5" +
                                          "wS3tjtxS6H5uz5584lHzrBknMdC5wDQD9d8Bh0YihxZYkXEGeaAOdh7NfJUO" +
                                          "vno1TggQ74oQK5rvfPbOA8dHbr6haPZsQzOXv8w0kdM2891v7508cn8C1Wiz" +
                                          "LUfHy6+zXGbZvLczXrWhwgzWOOJm0t+8ufCjTz/2AvtTnHSkSYtmGW4F4qhP" +
                                          "syq2bjB+hpmMU8EKadLOzMKk3E+TVphndJOp1bli0WEiTZoMudRiyW9wURFY" +
                                          "oIs6YK6bRcuf21SU5bxqE0Ja4Udi8EsR9TeKgyAXUmWrwlJUo6ZuWql5bqH9" +
                                          "TgoqTh58W07lIeqXU47lcgjBlMVLKQpxUGbeRp7rhRKDONHtCTlNYnjZ/y/G" +
                                          "VbRoYDUWA2fvjaa6AVly1jIKjOe0G+7E1J2Xcm+pMMLQ93whyEGQlVSyklJW" +
                                          "UslKBrJILCZF7ESZ6i7hJpYhp6Godh5ZfOTcpasHExBE9moT+rEqk2yP/wEH" +
                                          "I7rJdP7Eov3ML3/6hxNxEg8yvydUsheZGA9FG/Lsl3HVF+hxnjMGdO89Pf+V" +
                                          "J29/aUkqART3bCdwDMdJiDIonVCCvvjGlXd/8/7mrXhN8YSAcuvmAbUEaaN5" +
                                          "qFVUE4K014qOMmznv+EvBr9/4Q9txAUVQP2TXhQfqIWxbYfcEZPzYUFGGrld" +
                                          "uRy9tq9RWZAlbfPxGxuFuWfvVcnbX59qU4Ak3/j5P3+cfPq3b25z5+3Csj9i" +
                                          "sBVm1KkGIut6ghlZMX18zWnvdV//3ffGShNx0pQh/eAblxqI7qd5CXBDW/ZK" +
                                          "a2ceGoUArw+E8BobDW5prABw0Qi3PS5t1grjuC7IzhAHv5vAunm0MZZHVX/9" +
                                          "8T/uPn+qfEkGWxidUVozAAuenEdMrWHn/oj7oyyfn3nxzTOHtetxCSdYmreB" +
                                          "ofpD4+GLAKGcAW6aaA6udIHQg9Esjnorpx09QF/Jvfq5MXkL7YCpgkINBLga" +
                                          "iQqvg4RxP8lQVBs4oWjxCjVwy3d5hyhzazVYkeWlT8U8BEg3hvgw/I55RVP+" +
                                          "x91BG8chVY4k/YgcR3EYk9EVx+khHA5Lsg9DtB0O8hiqvAEFEW9k7IIJ164X" +
                                          "dZo3GFaYf/QcuveVPz/RqwLZgBX/io7/bwbB+ocmyGNvXfz7iGQT07DLCGpN" +
                                          "QKagayDgfJpzuoZ6VL/wzr6vvU6fARAE4HH0dSaxpEna1+Qn9qH/nthea+VT" +
                                          "DyD16gktWbAqSewgIdJxa9onGN3CrrQikmc4tcu65sxCNkh3Tkr6U3KcwGvx" +
                                          "ii9+P4TDxwXp0DiDgoR13ed+Ygt3zCS6KpJ6BRqYJEQP4Af6UcLBAs7AO2MN" +
                                          "Ei/Uz+a0a7c+6Hr4g9fuSH/XN8ThKj9D7XEVaDiMY+EbiuLMWeqUge6jN2c/" +
                                          "02vcvAscs8BRA6R05jgoWK3DBI+6ufVXP/jh4KW3EyQ+TToMixamKbae0EBA" +
                                          "nDOnDNhYtT/5gIrl1TYYeqXPyBYvblnAENm/ffBNVWwhw2X9u0PfPvncxvsS" +
                                          "X+wq+D9AVDw/vKU3V/2k9tJGT9vQxoVfyASv9XydUBKLrmGE6ke4lrTYnBV1" +
                                          "6chO5U5b/lsSZKhBRALaqYk0L6voL8KzKUovSLP8H6ajYE9AB6zUJEwCbXkC" +
                                          "SHDKwAGx+q4AP+Zw2KXmCw1vItRI3FMXePIN5FdnV72Ccto3N87NPnrnY8+q" +
                                          "vgJeT+vrsmeGJ4AqebUKP9qQm8+r5eyRu90vtx+Ke6nUpxQO6tyeUJ59CjDU" +
                                          "xpvdHSkezlithry7efK1n1xteQdCeInEwIkDS6EXiGq3oQK5AMVLmQCMQ29o" +
                                          "WdXGj3x97dTx4l9+LYPLA++9jelz2q3nHvnZ9eFNqH470qQZ+gdWzcJzynlw" +
                                          "zVxg2grPki7dmaqCisAF3ndp0uaa+hWXpeHl1o1BSPF1JP3iubOrtoooBZ3k" +
                                          "lmfQNlAPibjK+ITlmgWJeVAagpW6x5kPkq5tRw4EK7Wr3LnV9pz24Jd7vn+t" +
                                          "PzENiVRnTph9q+PmawAcfq8pRMaxV+JVVTV4iVxmxrb9hq/pltfduYoG1wWJ" +
                                          "HfVWsWTEVHOFn1XJblVOcVj/D3oQ4BSKEQAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5aczkZnneb+9NyG4SSNJAAgkbRDB8ntMeaynF4/F4POOZ" +
                                          "8czYnqMtG9/2jG97PB5DWpoeoCLRqE1aKkF+gdqicKgqaqWKKlXVAgJVokK9" +
                                          "pAKqKvWgSORHDzVt6WvPd+232UT86Ej2vH79vM99vO/jF78PnY9CCPY9e2vY" +
                                          "XryvpfH+0q7vx1tfi/a7bJ2TwkhTSVuKIh7M3VQe/+LVf3/lWfPaHnRhAd0v" +
                                          "ua4XS7HludFYizw70VQWuno8S9maE8XQNXYpJRKyji0bYa0ovsFCd51YGkPX" +
                                          "2UMWEMACAlhAChYQ4hgKLHqD5q4dMl8huXEUQD8DnWGhC76SsxdDj92KxJdC" +
                                          "yTlAwxUSAAyX8mcRCFUsTkPobUey72S+TeDnYeS53/jAtd89C11dQFctd5Kz" +
                                          "owAmYkBkAd3taI6shRGhqpq6gO51NU2daKEl2VZW8L2A7ossw5XidagdKSmf" +
                                          "XPtaWNA81tzdSi5buFZiLzwST7c0Wz18Oq/bkgFkfeBY1p2E7XweCHjFAoyF" +
                                          "uqRoh0vOrSxXjaG3nl5xJOP1HgAASy86Wmx6R6TOuRKYgO7b2c6WXAOZxKHl" +
                                          "GgD0vLcGVGLo4TsizXXtS8pKMrSbMfTQaThu9wpAXS4UkS+JoTedBiswASs9" +
                                          "fMpKJ+zz/cF7P/5Bt+PuFTyrmmLn/F8Cix49tWis6VqouYq2W3j3u9hflx74" +
                                          "8kf3IAgAv+kU8A7m9z/08vvf/ehLX93BvPlVYIbyUlPim8qn5Xu++RbySfxs" +
                                          "zsYl34us3Pi3SF64P3fw5kbqg8h74Ahj/nL/8OVL4z+bf/iz2vf2oCsMdEHx" +
                                          "7LUD/OhexXN8y9ZCWnO1UIo1lYEua65KFu8Z6CIYs5ar7WaHuh5pMQOds4up" +
                                          "C17xDFSkAxS5ii6CseXq3uHYl2KzGKc+BEEXwQWdARcC7X6P5bcYEhDTczRE" +
                                          "UiTXcj2EC71c/gjR3FgGujURGXj9Com8dQhcEPFCA5GAH5jawQs5tFRDA35i" +
                                          "+c1iuJ+7l///hTjNJbq2OXMGKPstp0PdBlHS8WxVC28qz62b1Mufv/n1vSPX" +
                                          "P9BFDD0OaO3vaO0XtPZ3tPaPaUFnzhQk3pjT3NkSWGIFYhpku7ufnPx096mP" +
                                          "Pn4WOJG/OZfrMS2C7KHi4SxY9+SdM3A7D3+mSHkK8MiH/mtoy8/8/X8WfJ5M" +
                                          "ojnCvVfx+lPrF8iLn3yYfN/3ivWXQb6JJeAfIJQfPR17t4RLHoSn9QfS6DHe" +
                                          "ymedf9t7/MKf7kEXF9A15SBHi5K91iYayJNXrOgwcYM8fsv7W3PMLqBuHMRy" +
                                          "DL3lNF8nyN44TIi58OdP2g2Mc+h8fKXwgXsKmHt/CH5nwPW/+ZVbIp/YefZ9" +
                                          "5EF4ve0ovnw/PXMmhs5X9rH9Ur7+sdzGpxWcM/DjE/9Tf/3n/1zdg/aOk/TV" +
                                          "E2UPKOHGicSQI7tapIB7j12GD7VcWX/3Ce7Xnv/+R36y8BcA8fZXI3g9v+cc" +
                                          "gyoHqsUvfjX4m+98+9Pf2jvysbMxqIxr2bYUMIiKogUk0S1XsguFPB5DDy5t" +
                                          "5fqh1CIoYoCx60sbK1T1JlC2C9Zyq+zvMn8RTICj63dw1xPV+qby7Ld+8Abx" +
                                          "B3/08m2eeqti+pJ/Y2ehgqsUoH/wdBR1pMgEcLWXBj91zX7pFYBxATAqIA9E" +
                                          "wxCEb3qLGg+gz1/82z/+kwee+uZZaK8NXbE9SW1LeWEF6TE2QS02QeSn/k+8" +
                                          "f5feNpfA7VoRm1Ah/5t37BRhfc+xIlgPFMCP/cOz3/iVt38H8NGFzie5DwMO" +
                                          "TmhrsM73BL/04vOP3PXcdz9W2AQkU/EXXnn4/TnWRkHgieL+zvwG7yyWD9+d" +
                                          "396T3/YPzfRwbqZJkfdYKYr7nmqBPYFaWOo1UwcXWg7wtuSg4CFP3/ed1Sf/" +
                                          "6XO7YnY6T5wC1j763C//cP/jz+2d2EK8/bYqfnLNbhtRMP2GI1M+9lpUihXt" +
                                          "f/zC03/4209/ZMfVfbcWRArs9z73l//zjf1PfPdrr5KZz9neoVPm98oB2fyv" +
                                          "/vqGje96Z6cWMcThjxVnUiVVxulUq+oCpi/XKT+uD92WN9ZkMuyZE3/I8HTo" +
                                          "l6O1izG85c9LldTBGti6mizXCa9mddwP22XSNwkTCSxrFZMtMSmnYigEPtUU" +
                                          "jNLEYyx5HjCsSI0oKp5wmdlWKYacoVQ5W2U4jOIaXGnPykupoW4XfVgp1+tZ" +
                                          "kjHr6kTmWtuRkY3FXlRR0i7vg8ru9jrtyXyALpfufFJxucXU0LFqDcZdrIaO" +
                                          "7AkWsuWuOw76Q0edzgWXzBZ+fT30ejLttl2adE3LXQ47jbEQqP2kv7Ir6ArF" +
                                          "5maA+fNoHvTJcc3hmD4qDUilVU1IX67QhLVlN0PJ742cQOXGmE71UXUUaduS" +
                                          "0dmgY762qKxYZrLtMBSqlBXfikr1UahOaLE0rqWzIW8708ZC2spNamWL7UbY" +
                                          "TV1YI5W6i8Xh0qj1I1zHYixUN+GMbxK82p+Ulqlr8M40UpgerTJ8SNUW4bCr" +
                                          "MIuGa42yBTVhpgsyW5KlSrPUHDG4VBoEVAtjHQm1BZt1rEGDtyoV0/C6fTvk" +
                                          "0p6kiMtNpQGUUxsQDjdI7Lncqoz6ZWmhCVOq3mjYYZiW+zNN3ooMX5dL6HBu" +
                                          "BcGwSRk9atGnzbDbdastW+2xTdJOJgtl4LDLYSKUBhruwPUq3u12zVEyw7Co" +
                                          "3S5XZGWyyhrNmcLgS3omlOcJDSiNJAHHRWVAG125WerLbWHKr/soPbBMo9Jr" +
                                          "TMjOOiEHgy3mLyh6jOAUP0hDumMQ5DC2pXmvHZUFoeSYo9kkLLGUR8/9eGSZ" +
                                          "i7pExAOHJIYTEqMxpt0px0KlsrBtY8hkXXKAwhWj56tDo8eRLBNOrHl9M6nG" +
                                          "yzidoJ36OqvXGzW7k4XNldtXyfqmNWrhaqNpluaWmS7mqxlFaxIxVE1soHeF" +
                                          "YeJ6Zd4wRljNG/XqYaJz8pBoqB05RE2JW0SjbDhLGpvSSu1XGng5weqlhuI2" +
                                          "yPLUylhB72xROJvR8iJhlWwWTs2NkU2Hw65TiuHGWieXfIZUiCTm3c5kNZnH" +
                                          "Dj2ttWuByUXboCIvm7DpO32hQfUklR1m/d6qSsG86Juu2h36ZVADS1PK4hde" +
                                          "f62Ore0U3wjj9txjInTeQ+WxstYr5YlQl9OAKnWlmqBaDSoa47zWM7bETHCm" +
                                          "4cbuCh66WE8Duy4HHZw3vIA3641pCbMZLZgJNcxWjGXT7otsb+SnAi1rYx8L" +
                                          "zXGvNRx0YpK3B3N3uUC2CC3KY2/eEqZERU+WkoQSor0tL5necqiVaBijyt3K" +
                                          "THFgv99nR3h1Y24pemSLk+3K7k6FyO41wy7Dkos2Rk0WqIWZXX9u+ijtqWZ9" +
                                          "oQ95xZeiDpU2KdzxeDikglVlyyEbqsNgYVflMMpLqn22iqBmOkgpo7FNtqoQ" +
                                          "mdqCJvA2jbCRXe2IbdhM3WWfVocNnNNhsVvBEUlYBcSYr8qkumn11a7VYjxX" +
                                          "JMkkWdL2TEUaCOaEM3PQmE8IZZ04hCxQkjSoB21RoGq9UrkWDPtO5iYwlTRD" +
                                          "HKmN8DglBHHEVfiZOdIDZprKc12hFlw2F9o0HdrqerzF4wAfTxeELetcSqfr" +
                                          "9nqqJ6LiyrM6Hgg1YlVFlnWuCis6F1TlSj2rw1UyWuJW1BSdcm9FM+sYNUx7" +
                                          "0Z+VG9nUTVQRQaq6Tk/MQVryRyaiETLYEjFYoNbJWbM1RRY9qaJotCcQ4Qam" +
                                          "Gk1Pbk3rfkg0N6WRVeUm9bhshMs1iTGZSXSSekKsXafUXyw64gzBGzyy5lw4" +
                                          "0KkVPU0tVRC9jCDWmkup/XDacRFviXnbre5W3TTjh51Yi1Nyos6dUGt6ut+q" +
                                          "wTRL9GiFmKKSRKBrlemMDJyKlq4X+mkJH7WRbqIH9f5sxWJz0jdWzKDJGpI1" +
                                          "ChKjNk65hj0Sm1HNmy5TcilutlW1bm7NTMrE+Uqb2nxDaIAkVjUTY4Mw9fpY" +
                                          "5OAULzfphmKK89oKmRvKuErNVzglpvDK7BB1NjLwVtwsDRumFSQE1aam+Apj" +
                                          "mG4Zrc3UhVel29JcR0bA7JrIZcg42LALozlDLA9D5I3chD3F2dKDZKZnmEWP" +
                                          "+BLWYknaH4x6kiFtW4be9bO1t0BFFtlkIZokAqoTY4KqdToldSKlPuVKZXjk" +
                                          "4kEHcWNTk2CRb21bZdRYxVOZCCbaxmDUbirhnksPqmQYjqyVo9RiZY3Wo5Qc" +
                                          "rMwqvwpRodpTNnSSWhYOczW+lW5mfqlltQxvXK5qKjw34mpGTtCe30Wb42De" +
                                          "pUZcjdBRQWGbRIQRw0p/QFmIkMFSScIUGO2ENQPX15MOMgMVxuwt8RY2o0Sp" +
                                          "ZfXnMCVba7Y/1QLB0NDloKIgpUqiJESkRI3mmEDHpfrS8Ka9aqvJwOhaF2cc" +
                                          "sjRrvWmV2o5gnvf6Vio5PVnSSlSTcFtgKzIw5zGP1A0mtMv8fA5SD7dtzhPZ" +
                                          "dglq4CC63hyI0425qczwdYnTucRV0iSazOBNALdwQmxtkKQnVEWkssLjLs3j" +
                                          "ySj1RH1LTBJ8BhJBs8eGDk2hK61mh/zcbYplVDGHdZAdETuaLHomYJyVgvmq" +
                                          "xKKJxzZ6WU/wkgnLNTqotJxTONFEM6FLbUh5tiInnVZvQ9ApHNQIDl5sKr2Z" +
                                          "Q27KCROPmWobFFeOGdTbqitiFRLszauDBjbg3NCdN2DgzF2Nh5MwcjS6WyMC" +
                                          "TRZ6HB6MnAYc1rXteI2XkjiFexrqCn46GqLxVhO6dZxctoTUT1RQKrTMtsBe" +
                                          "f4tpeq/sltNYG6mkxrjUhlm1Jig1s+igmlcsAuRtZ0T2RxXcm6ozellNcUzl" +
                                          "05qNw+ycYwkYxpeanVWCqttJ3AWutQdBp4aVgtECNtRppnSzrWtvMjE1KkbI" +
                                          "rSxMdaSAtCKiXXVVv7SWJNicznytY5e9cnPCtctdrmqt5WEYe57XXFRXtqOP" +
                                          "BjbBWfKyBzNgk2RMu5pISIY/RdP6ilsF9Xi8qVE9bBpWWVfE/axS66pY4sIx" +
                                          "l1EDSxy7vG/iAcw50oZQ9KDhj/tSKsJdUeTFmiWmThrKuBkgvh3r6nru0eXN" +
                                          "tNvRxWk05SmxM2y75VlXtsUh2BwhLaCZWnPSo0YEkW+ZmR/t1HJvcbg86jGC" +
                                          "w0r+ovQj7NbT1yIYQ5ckOYpDcKSLoctHTc8d9RPdlTOHh9lH79TF2XVw8sPK" +
                                          "I3fqMhYHlU8/89wL6vAz5fygkuNsAbqx57/H1hLNvoViCL3rzoeyftFkPW6c" +
                                          "fOWZf3mYf5/5VNE5uK2hw0JX8pVc3ss+6lm/9RSfp1H+Tv/Fr9HvUH51Dzp7" +
                                          "1Ea5rf1766IbtzZProRavA5d/qiFEkKP33aS8xRNXYfaMd13vU360s0vP319" +
                                          "Dzp3sreUY3jkVKfmLt0LHcnOCRz2m6+ASPU2xzMn2zZArffkTvEQuOCDhmTx" +
                                          "n7+938/vb0yPXes2n9k7ctLxgYeE0DuOOwakZ9uaUmj9uuA6xQFbkm0t7979" +
                                          "99Unyl/6149f2x0/bTBzaIZ3vz6C4/kfa0If/voH/uPRAs0ZJe/gH/dAjsF2" +
                                          "beH7jzETYShtcz7Sn/uLR37zK9KnzkJnGOhcZGVa0ac9V8h37tDLn3htLz/4" +
                                          "bHEIfX8Ovakq+6rn7OffajS3kG51CPDYbeiMJN6nQ8k3LSUaeOou4MwCXinu" +
                                          "RhHGuy5n/lwY52YMXVFCTYq1vGd6iL16G/Y8WqRNvG85EuA51FxVC3M9Fq3W" +
                                          "cT46Th1Pvd5B/yQnKWDguF2b6/ih2z787D5WKJ9/4eqlB18Q/qrw4qMPCpdZ" +
                                          "6JK+tu2THcYT4wt+qOlWIfDlneP6xd82hh68g0li6MJuUDCb7uA/FEPXTsPH" +
                                          "0Pni/yTczwJ5juEAqt3gJMgzMXQWgOTDn88bmSdS1EFqLdR43+up8WjJyU5k" +
                                          "bqjiA9thClrvPrHdVL7wQnfwwZfRz+w6oYotZVnxQYaFLu5i/iiNPXZHbIe4" +
                                          "LnSefOWeL15+4jDl3rNj+DjQT/D21lePRsrx4yJ+sj948Pfe+1svfLvoxv0f" +
                                          "5Pi6TfkcAAA=");
}
