package org.apache.batik.bridge;
public interface FilterPrimitiveBridge extends org.apache.batik.bridge.Bridge {
    org.apache.batik.ext.awt.image.renderable.Filter createFilter(org.apache.batik.bridge.BridgeContext ctx,
                                                                  org.w3c.dom.Element filterElement,
                                                                  org.w3c.dom.Element filteredElement,
                                                                  org.apache.batik.gvt.GraphicsNode filteredNode,
                                                                  org.apache.batik.ext.awt.image.renderable.Filter in,
                                                                  java.awt.geom.Rectangle2D filterRegion,
                                                                  java.util.Map filterMap);
    java.lang.String jlc$CompilerVersion$jl7 =
      "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Ya2wcVxW+u36/H0nsPJ3YsVPy6C6lFEidprUdO3FYOyZO" +
                                          "I7FOsrk7c3d34tmZycxde+0CKpUqgoAoCiktSPGvlBQIbYWooEArI6Q+1IKU" +
                                          "ElFK1RKp/KBA1EYV8CO8zrl3Zmd2vQs/EKw0d2fvPffc8/zOuXvlBqlxbNLD" +
                                          "DB7hCxZzIqMGn6K2w9QRnTrOEZhLKI9W0Q9O/H5yd5jUxklrhjoTCnXYmMZ0" +
                                          "1YmTTZrhcGoozJlkTMUdUzZzmD1HuWYacbJGc8azlq4pGp8wVYYER6kdIx2U" +
                                          "c1tL5jgbdxlwsikGkkSFJNGh0uXBGGlWTGvBJ18bIB8JrCBl1j/L4aQ9dorO" +
                                          "0WiOa3o0pjl8MG+TnZapL6R1k0dYnkdO6Xe5JjgYu2uFCfqebvvLrXOZdmGC" +
                                          "VdQwTC7Ucw4zx9TnmBojbf7sqM6yzmnyOVIVI00BYk76Y96hUTg0Cod62vpU" +
                                          "IH0LM3LZEVOowz1OtZaCAnHSW8zEojbNumymhMzAoZ67uovNoO2WgrZSyxUq" +
                                          "PrIzeuHRE+3fqyJtcdKmGdMojgJCcDgkDgZl2SSznSFVZWqcdBjg7Glma1TX" +
                                          "Fl1Pdzpa2qA8B+73zIKTOYvZ4kzfVuBH0M3OKdy0C+qlREC5v2pSOk2Drl2+" +
                                          "rlLDMZwHBRs1EMxOUYg7d0v1rGaonGwu3VHQsf+TQABb67KMZ8zCUdUGhQnS" +
                                          "KUNEp0Y6Og2hZ6SBtMaEALQ5WV+RKdraososTbMERmQJ3ZRcAqoGYQjcwsma" +
                                          "UjLBCby0vsRLAf/cmNxz9gHjgBEmIZBZZYqO8jfBpp6STYdZitkM8kBubN4R" +
                                          "+xrteu5MmBAgXlNCLGl+8Jmb9+3qWX5J0mwoQ3MoeYopPKFcSrZe3TiyfXcV" +
                                          "ilFvmY6Gzi/SXGTZlLsymLcAYboKHHEx4i0uH37h0w9+m/0xTBrHSa1i6rks" +
                                          "xFGHYmYtTWf2fmYwm3KmjpMGZqgjYn2c1MF7TDOYnD2USjmMj5NqXUzVmuI3" +
                                          "mCgFLNBEjfCuGSnTe7coz4j3vEUIqYOHhOC5l8jPVhw4ORnNmFkWpQo1NMOM" +
                                          "Ttkm6u9EAXGSYNtMNAlRPxt1zJwNIRg17XSUQhxkmLuQtDU1zaJjmg4BNGVr" +
                                          "WVB4jg2L2QhGmvV/OCOPeq6aD4XABRtLAUCH3Dlg6iqzE8qF3PDozScTr8jg" +
                                          "woRwLcTJ7XBsRB4bEcdG5LGRsseSUEicthqPl84GV81C0gPqNm+fPn7w5Jm+" +
                                          "Kogya74aDZ0XWbjB+wEbS8QU+X7PtHXx1794984wCfvQ0BbA9GnGBwPhiDw7" +
                                          "ReB1+HIcsRkDurcem/rqIze+MCOEAIqt5Q7sx3EEwhCwFTDq4ZdOv/Hbty9d" +
                                          "CxcEr+KAx7kklDVO6mkSwIwqnJOGAipJxVb/Ez4heP6BD+qIEzLCOkfcMN9S" +
                                          "iHPLCpgjJN7XctJTyQPS5Gi1TZVwQ2DepYcuLKmHHr9DZndncS6OQqn57q/+" +
                                          "/mrksesvl3F/Azet23U2x/Qi0eDIoqZhQkCqV4ATylut5995tj89HCbVMdIJ" +
                                          "tslRHcv/kJ2GwqLMutjbnIROwi/oWwIFHTsR21SYCvWkUmF3udSbc8zGeU5W" +
                                          "Bzh47QYC647Kxb5U9Bcf+sP6I3szJ0WwBcs3nlYDlQd3TmHRLRTXzSXmL2X5" +
                                          "rYkrL+/fppwPi3qD2F2mThVvGgw6Ag61GRRWA9XBmRY4tK80oUutlVB2bKHP" +
                                          "JJ77bL/wQgMUXU4BJKGe9ZQeXlQzBr0kw6PqwQgp085SHZc8kzfyjG3O+zMC" +
                                          "aTpkzEOANGGId8PzcRdVxTeudlk4dktkEvQ9YuzFoV9EVxhfB3DYJsg+BNG2" +
                                          "zc9jKAM6wCR6pP9+A9yupTSa1BkizN/aBu545k9n22Ug6zDjuWjXf2bgz68b" +
                                          "Jg++cuKvPYJNSME2xMcan0zWtlU+5yHbpgsoR/7zr236+ov0IlRJqEyOtshk" +
                                          "sRH61XmJPfDvE9vtvTzqVUg9f6cSUc1sBFtMiHRcGvMIelewS8/xyH6bWhlN" +
                                          "cSYhGzzKD6+gxKyg8zyiZaFbiUAkQFlAm7go721cJ3RFwjQDKQ6DHaBf0tlH" +
                                          "9hUjAqbedA5g8TCdF1iUUI7d1t7Vv/uDPglCPWVoA83O2R//KB6/rV2RxH3l" +
                                          "GBc3OU9crlfezL7wO7lhXZkNkm7NE9GvHH391KsiuesRfQopFcAWQKlAWLcX" +
                                          "wroVo7gDnutuWF+XUH7svyzksA06eCik0Hse0bJMdd3rNQr/U/5YP7qLwNx3" +
                                          "2ndm9aH3PvHNe6RZeyuAqE//7KeuX724+NQVmX9oXk52VrrzrLxoIVIPVEbq" +
                                          "QID8ef/dy+++c/Q4CobeacVhOu/FaYufkxNUIM6MWBrG4lUoYauLw0Ry3vfF" +
                                          "tp+c66waA8wcJ/U5QzudY+NqMRrXOblkIG781l5iswgagVx5LPechHZYVl5M" +
                                          "jwgx9haEIW7ng7+TONzN4XZkM+gGZObh3EGQtb+CWQIXx4Ry7tr7LUfff/6m" +
                                          "MH/xzTPYLYFJBiVg4zAoAqC0XztAnQzQfXR58li7vnwLOMaBowLh5RyyARzy" +
                                          "Rb2VS11T95uf/qzr5NUqEh4jjbpJ1TGKdzzo1KFeMCcD7Wbeuvc+mTzz9TC0" +
                                          "C/XJCoOsmECo3VwexEezFhewu/jD7u/vubz0tujTrDxctMo2qchq7Yr7sLzD" +
                                          "KU8utdV3L93/uqiZhXtWM6BFKqfrgSAIBkStZbOUJmzaLC1riS/I3e4KIA8N" +
                                          "pHwRmpqSHv+qKKXnpEZ8B+nmOGn06YCVfAmSLHBSBST4ugi2CBU32vhDxWGN" +
                                          "fE9XdEqgN99aFIPifwcvfXJTLgI8tXRw8oGbH3tctuqKThcXxT0VkkZ2EYWm" +
                                          "qbciN49X7YHtt1qfbhjwkrxDCuy3DhsC2ZOFnLbQs+tL6rHTXyjLb1za8/zP" +
                                          "z9S+BtE8Q0IUaupM4NYvr7hQ1HNQy2ZiK8EBWk7RKAxu/8bC3l2p994UceaC" +
                                          "ycbK9Anl2uXjvzy/9hI0FE3jpAZacpaPk0bN2bdgQA2ds+OkRXNG8yAicNGo" +
                                          "XoQ8rRiEFP+REHZxzdlSmMXGj5O+FX89lOmeISfnmT1s5gzVxa4mf6boDxGv" +
                                          "78xZVskGfyZQI09IuJPlsCoRm7As76ZTfdASCJwoRWAxKXZ/Sbzi8OV/AddU" +
                                          "DAqTFAAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05aczk5lneb7O72c2xm6Q5mjZpk2wq0mk/z3gOz5Betsdj" +
                                          "z4xnPOPxXIZ243s8vq+xxyWojSiNKCoVpFCkNr9aAVV6CFEBQkVBCNqqFVJR" +
                                          "xSXRVoAEpVRqfhQQAcprz3ftt9lE/cNI9rx+/bzPffh93hd+AJ0LA6jkudZW" +
                                          "t9xoX02j/bVV34+2nhru95j6SAxCVSEsMQx5MHdNfvSLl//95Y+truxB5wXo" +
                                          "HtFx3EiMDNcJOTV0rY2qMNDl41nSUu0wgq4wa3EjwnFkWDBjhNGTDHTbiaUR" +
                                          "dJU5ZAEGLMCABbhgAcaOocCiO1Qntol8hehEoQ/9PHSGgc57cs5eBD1yPRJP" +
                                          "DET7AM2okABguDV/ngGhisVpAL35SPadzDcI/PES/NxvvO/K756FLgvQZcOZ" +
                                          "5OzIgIkIEBGg223VltQgxBRFVQToLkdVlYkaGKJlZAXfAnR3aOiOGMWBeqSk" +
                                          "fDL21KCgeay52+VctiCWIzc4Ek8zVEs5fDqnWaIOZL3vWNadhJ18Hgh4yQCM" +
                                          "BZooq4dLbjENR4mgN51ecSTj1T4AAEsv2Gq0co9I3eKIYAK6e2c7S3R0eBIF" +
                                          "hqMD0HNuDKhE0IM3RZrr2hNlU9TVaxH0wGm40e4VgLpYKCJfEkH3ngYrMAEr" +
                                          "PXjKSifs84PhOz76fod29gqeFVW2cv5vBYsePrWIUzU1UB1Z3S28/a3Mr4v3" +
                                          "ffnZPQgCwPeeAt7B/P7PvfSetz384ld3MG94BRhWWqtydE3+tHTnN99IPNE6" +
                                          "m7Nxq+eGRm786yQv3H908ObJ1AORd98Rxvzl/uHLF7k/X37gs+r396BLXei8" +
                                          "7FqxDfzoLtm1PcNSA0p11ECMVKULXVQdhSjed6ELYMwYjrqbZTUtVKMudItV" +
                                          "TJ13i2egIg2gyFV0AYwNR3MPx54YrYpx6kEQdAFc0BlwvRva/R7LbxH0FLxy" +
                                          "bRUWZdExHBceBW4ufwirTiQB3a5gCXi9CYduHAAXhN1Ah0XgByv14IUUGIqu" +
                                          "wh3DAg40CgwbCLxR8WJ2P/c07/+BRprLeSU5cwaY4I2nE4AFYod2LUUNrsnP" +
                                          "xTj50uevfX3vKCAONBRBbwdk93dk9wuy+zuy+69IFjpzpqD2upz8ztjAVCYI" +
                                          "epAOb39i8t7eU88+ehZ4mZfckis6LaLwgeLhLFj3xM1TdCfPD90iJ8rAZR/4" +
                                          "L9aSnvmH/yxYPpllc4R7rxAWp9YL8AuffJB41/eL9RdBQopE4EAg1h8+HZzX" +
                                          "xVMepadVCfLsMV7ks/aP9h49/2d70AUBuiIfJPGZaMXqRAWJ9JIRHmZ2kOiv" +
                                          "e399EtpF3JMHwR5BbzzN1wmyTx5mzFz4cydNCMY5dD6+VLjDnQXMXT8GvzPg" +
                                          "+t/8yi2RT+xc/27iIP7efBSAnpeeORNB55B9dL+cr38kt/FpBecMvHPifepv" +
                                          "/uJ71T1o7ziLXz5RF4ESnjyROXJkl4sccdexy/CBmivr7z8x+rWP/+DDP1P4" +
                                          "C4B47JUIXs3vOcegDIJy8qGv+n/7nW9/+lt7Rz52NgKlM5YsQwaDsKhqQBLN" +
                                          "cESrUMijEXT/2pKvHko9A1UOMHZ1baGFqu4Fdb1gLbfK/q40FHEFOLp6E3c9" +
                                          "Uc6vyR/71g/vmP3wj1+6wVOvV8xA9J7cWajgKgXo7z8dRbQYrgBc7cXhz16x" +
                                          "XnwZYBQARhlkh5ANQCSn16nxAPrchb/7kz+976lvnoX2OtAlyxWVjphXXpA/" +
                                          "oxUo1iuQBFLv3e/Z5b/kVnC7UsQmVMj/hh07RVjfeawIxgUV8iP/9LFv/Mpj" +
                                          "3wF89KBzm9yHAQcntDWM84+GX3zh4w/d9tx3P1LYBGTb2S+8/OB7cqzNgsDj" +
                                          "xf2n8ltpZ7F8+Lb89vb8tn9opgdzM02KbMiIYTRwFQN8NCiFpV41dRwlqV21" +
                                          "g5+++zvmJ//lc7tqdzpPnAJWn33ul368/9Hn9k58Yzx2Q5k/uWb3nVEwfceR" +
                                          "KR95NSrFis4/f+HpP/rtpz+84+ru6ysmCT4IP/dX//ON/U9892uvkKRvsdxD" +
                                          "p8zvyAHZ/K/+2oaNbo/oWtjFDn9MZSkiiTxL56W42oDpshOOetVlOBttG0TD" +
                                          "6pCG4gVTha12luxWYLtohw0DE5WrSrUW2cJWThW1VCb63tTXXcwlDDOajKiN" +
                                          "hY+70nLuuiQWdBvjUqXbn5JWp1/h+h7cx7EKuZw1CbaZBVZVsBVkMw5hsp+U" +
                                          "FUTbjDRNbsIZGy8AGt9KpSHTbuPoikiFrOsPKKfRR5LWmHP4gCWFFdPvtubl" +
                                          "cYuF6fpWqa+nqWkFq7XLE85iaQ+EcmVp87wQrGTKdbOeZfKDqTLNhMxuV+h4" +
                                          "vhRlqUfJTTGz/JpHec1ktlySXMNUuikylSsRU1/rkpJaSWiYlGlOOr0htSrH" +
                                          "C5yirDlPbfBepSl18WYvIHCrsoaZmjhuKW7AlucGK1bdsre2mgOqxDuC6DEN" +
                                          "rmKWlaVjKmxjodZ7a30ZI3GH0HxV2myYYMEKik0RM2Wc8AQ6lZNalrZ4x8bd" +
                                          "taSBJDVobDPb2bKz7qxbLuNLE20sW43VlNfLhKs0kI037dJlZlBlBHLGuklW" +
                                          "YSNBJDCHnsybGQmwgDjd2qtBhrlCA43dzdBlkbkeCJNtOvVHQTdTY5ojS1XN" +
                                          "3/YiWenblDJw13qPkNu62dYFC5lMMmfSmQlzX1bwtY5Sli1W+EXHqoyUzBMR" +
                                          "H2viJbSadfs8u9wINTPTZjFOlwdVtq9sy0TJtziSqG8Qb8KaSDuwkFJgMe2B" +
                                          "kNA4F1bIQcpOlzqqlDeVgBJdh0ri6oweh1qJH2O41ED7A6GZEcCK1GrsTPrT" +
                                          "IemVlw1WR1ZCY4JHA5HEmHF9PitxfSUQ3dANeWlAcva4VxU4GfNdajley0lo" +
                                          "i9M1gxPStrwJOQbTYNkepllLp9c6TtpdAReEpc821xrueY0Jv1QEIzIHTROP" +
                                          "pWGNK6VBpMb1gY1j+sIaEgxllZo9W2qVqv58Ue+V7cQdVweuunS9Ub8jTwJB" +
                                          "rfLGVlvIM8PqbOxlg8oMeLKgeMFiwq3NyNhScvs0TaY1oxzTVXRVTlolGy6n" +
                                          "PB7QE7FiNAIzTDsUvbSXET/XEM1eJna1b6+9ASX4+nrpIHJl0EH5Nrt02sh0" +
                                          "srYH6/rQX0yzmR13qzahd5ghTq41IqYmDq+ispvV1tUNOe36S5ZesUTdaq5H" +
                                          "s1VSYzlnaHfMuTd2K8MBO+Aj027ELRJbUJPlMBoMMYsbpVEl6yXDLqdX0MVk" +
                                          "Ol6lps3E46g9rWRib23rNXxIzYL5DK+tdYRBxivK3sxglmBHqt8Q27UFhnMR" +
                                          "g00Jutq29IbhZ2TT71RHbTebyHzQXOuJyyWMzPfQBR5yeE0iZYWqMxQXhupk" +
                                          "SoIKv/JHVrNGzZoVoqyP/KFd0kYOmtR7dqnv6lsRrYltobyYS2u8lJDSpDme" +
                                          "lhboKKIXaQVt1VrNWkJom3EZl7AW5VB4MloZ7QTlVLxSortyyJntvA7ZcOCD" +
                                          "6CgNCJbEun5UH6NhWiXJZEUkHb7t1wSF3cC0FG1bCpHKZFDqYylqmlZ7xjZs" +
                                          "c5J0E9/psRRmeL10JsFkVlupowbeLvldMmMI1tTkwbA1MegRQ3j6ujdEF3LU" +
                                          "47fj0aROGRVemCVjpK16Szlm+jZNB6224CiOPGmwY9+poz5cgm3gIGq4saod" +
                                          "GMvUCKlOkRQeG2W13XV9YTU2CX9Ww/itFUf1VqserZstmpBmA6Xbi0KLo+UN" +
                                          "bPYQKvGZQRytJafLsYkBu/Ok26H5kEMqkyWxmZtTu1ONlYkkNzNKndbneLaq" +
                                          "oeMl0aih/VSqT1u4rJXCUaNbDbNeeZ7gclh1rGXbGitV3qY5huMX2WRhM8ii" +
                                          "HizNgCnBmuclI6Pqt5EOYvOr2YbSkwamNyoUx82x1gK3uWUt6jfL7jSOrBmO" +
                                          "SH161OuhqMTAyVgfTBfTGt7rU2pLGKsLa5zhQdlMGiMfvPTKzfqEFuQmSEXb" +
                                          "NVVlS9mAEHnPzEgWG1JUV2mOMplTZimvxopl1hQzMsnNuLWMs447a5GzdKXh" +
                                          "1fayF+ol4NBIJrfWfWzQSAiu4Y1aJay1jT0eRChuGtkQFvG4XqubLQdBpnoj" +
                                          "a6/j+XqhIZKeNZpSTy+V5Li/GS17w8mARNIB2BSWs3lkTUv1LS15euhyMJoF" +
                                          "SLVRcjflrsX1fHLLRuHKDDm6UVnYvZHW3pCtTbThM3821VtaQ56AYhXinWhg" +
                                          "0JxMbQZd1VKTSRNOt3RDmq+soTxZrqgs67cbJT3tb/VmtjUEsSMZU8wcdyzM" +
                                          "RnUXRSpyr8p1kvW43R832rSIa+XIolur6RrzJVXB6nqTJ5ROxZhOu6hSidDZ" +
                                          "Bo7bI90iRvOZizWrLMLBoMQ34GCGcCldtShcrrLTlhxYmpoxaMKi1mohmEPT" +
                                          "Rodki9rQdLVV6YdGrIacNna9jozNx30LmzPyIgncmYvqbSeO4nmntJjSaLjZ" +
                                          "ZmaIlRsq+Ngo06FalnoDRakGw3EAT+H6coT6TDJMq4ij2C2Rro429FBtcIK6" +
                                          "jTGfhGG0r8YLFKmVhuOZvWi5C7OOzIIgC5jUBVV1NCMlf9xtN1UNVrYlYCt4" +
                                          "XCNcSRXl2YqN4Y64jDUzHU67g8ZgjgdUzZq6SzFmkjK3rW60TuSV5EYjEbFm" +
                                          "IvfgaX2cxcqyNPQHHKjukmV2KbRZsepGmOiiPkvrzEiVV7SwnFn1wTrR09ZK" +
                                          "JLtz1NHREs8Os2ENKGtQ0imBlVZVkhpHUomYj7uLtMZt0ShAmammaXDDHtBw" +
                                          "mvGjJbPs9HBjptdAicd8orzIIswZZ2NtwdWbloFunIRhByLuJsyqzm23GJdt" +
                                          "OQmZTSoVvlWPNdjPgvpw6pOr2noteb0KT/WVLHMr/Y46AF8B6FxS441csvks" +
                                          "a/FEmYAXPcJlQ5sk3OosUVNSzTorNYnhdRuN4U0sZeUoXvNBO5XBhzziyysf" +
                                          "XQZoyGTt/rQZR8qsyrSqcOwbwmoRzQcNvNP3tUCfYF3cnESCxE57diYyRCUw" +
                                          "JnC3qtb6Xaw59OiEsz1/Qm9Kfr+/cDxSAN8djs1STrmxJGYaZk8YGp/gE74W" +
                                          "6wZC4NMqslm10zk11MjWQiF9fdhqiZ3uyNASeaMtejyjd5vRgkuaLiXR1UiO" +
                                          "Yr/Pr+RFypdnpikg5HJu+5JsDGutBbqko6jia9JqnZhB2ibibbW9CglEYDsO" +
                                          "I43DUsQ0AppfbNeMBKoh+KYdZa1JCY/I5rjcnYqxN6gNl5sAXY0r9HC8RQSj" +
                                          "3yTxuYlyoHLEcFMiqhbitVq1qayKxFaW+i3MsZB4sd5kW7i16pY7ZHXtYYIo" +
                                          "e+LILEtDRFL0MYYoYYk1ucWQam4xQx5S7sIdNwPOIDujEkfSQpop1sQeLKh1" +
                                          "nS11Fs2Wxdpqd6I5Nl8J63o2S8WarTUkt51SG7SZCrPQpLStMO6WW924N7JC" +
                                          "wuVsFAvRhsBrCjYheqBKz7G0vxDgiZQZTXYGY4oybWM+3wHbjHz70f3JdoB3" +
                                          "FRv1o4Yu2PjlL8o/wc4nfTWCEXSrKIVRALbHEXTxqMO8o36iU3XmsDHw8M2a" +
                                          "Y7tuWL7xe+hmLd1i0/fpZ557XmE/U8k3fTnONqAbud7bLXWjWtdRDKC33nyD" +
                                          "Oyg62sdNqK88868P8u9aPVV0YW5ojjHQpXzlKD84ODogeNMpPk+j/J3BC1+j" +
                                          "3iL/6h509qgldUOv/fpFT17fiLoUqFEcOPxROyqAHr1hV+zKqhIH6jHdt75Z" +
                                          "/NK1Lz99dQ+65WSfLsfw0Kmu122aG9iilRM4bO5filaBmxzPnGyBAbXeljvF" +
                                          "/eBCD7q/xX/+9h4vv78uPXatG3xm78hJuQMPCaC3HHdfCNeyVLnQ+tWpYxfN" +
                                          "ClGy1LwT+t+XH6986d8+emW3lbfAzKEZ3vbaCI7nX49DH/j6+/7j4QLNGTk/" +
                                          "LjnuJx2D7Xrw9xxjxoJA3OZ8pB/8y4d+8yvip85CZ7rQLaGRqbumeCHfhUMv" +
                                          "f/zVvfzgjOgQ+p4cOqnK+4pr7+cHY6pTSGceAjxyAzp9E+1TgeitDDkcuop6" +
                                          "CFm+ATL3fDGJ9g1bBPQD1VHUINfJQTf6cOHrC1lzQF0FXHBAD6KjWyrSvq4V" +
                                          "c30ccWJSBOc1+Q/H3/3mp7IvvLAzjySGagSVbnZ0d+PpYd4jfvzmwXriUOdH" +
                                          "1E+/+L1/nL33MPxvO/LMB3JHfAO43nngme887ZmHst5xbNeBWLxLC1yrAkAu" +
                                          "7nqRBncd9/z5/fntWgTdLgeqGKk75eVz7nEWfeq1+kcnkaYRdO8rHgjknvfA" +
                                          "DWePu/My+fPPX771/uenf13E9tGZ1kUGulWLLetkD/vE+LwXqJpRiHFxF85e" +
                                          "8fdMBN1/E0eNoPO7QcH3B3fwH4qgK6fhI+hc8X8S7tkIunQMB1DtBidBPhJB" +
                                          "ZwFIPvzlvFV+InEfFJxCo3e/lkaPlpzsdef+U5zxHibmeHTgpl94vjd8/0uN" +
                                          "z+x67bIlZllxJshAF3aZ8Ci5P3JTbIe4ztNPvHznFy8+fuiJd+4YPk5/J3h7" +
                                          "0yvnKNL2oiKrZH9w/++947ee/3bR7/0/66XQIHwfAAA=");
}
