package org.apache.batik.dom.xbl;
public interface XBLShadowTreeElement extends org.w3c.dom.Element {
    org.w3c.dom.Element getElementById(java.lang.String elementId);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Xa2wcVxW+u+t3/HbiBCdxEncTkUd3VJUilQ2hsWsnG9aO" +
                                          "ZSdVWdNs7s7c3Z14dmYyc8deu4BKJUT4U0VpSgtS/ctV1aqUClEBEq2CKtFW" +
                                          "BaSWCCioBYk/vCIaIcGP8Drn3tmd2fGu+IelvZ6599xz7nl9352XbpF21yHj" +
                                          "zOQpvmYzNzVt8nnquEybMqjrnoO5vPp0gv7twh/m7o+TjhzpL1N3VqUum9GZ" +
                                          "obk5slc3XU5NlblzjGm4Y95hLnNWKNctM0d26G6mYhu6qvNZS2Mo8BB1smSI" +
                                          "cu7oBY+zjK+Ak71ZOIkiTqKcjC6ns6RXtey1QHxXSHwqtIKSlcCWy8lg9hJd" +
                                          "oYrHdUPJ6i5PVx1y1LaMtZJh8RSr8tQl4z4/BGey920JwcQrA3+/c7U8KEIw" +
                                          "Qk3T4sI9d4G5lrHCtCwZCGanDVZxL5MvkUSWbAsJc5LM1owqYFQBozVvAyk4" +
                                          "fR8zvcqUJdzhNU0dtooH4uRAoxKbOrTiq5kXZwYNXdz3XWwGb/fXvZVebnHx" +
                                          "qaPK9acvDH4nQQZyZEA3F/E4KhyCg5EcBJRVCsxxT2oa03JkyIRkLzJHp4a+" +
                                          "7md62NVLJuUepL8WFpz0bOYIm0GsII/gm+Op3HLq7hVFQflv7UWDlsDX0cBX" +
                                          "6eEMzoODPToczClSqDt/S9uybmqc7IvuqPuY/CwIwNbOCuNlq26qzaQwQYZl" +
                                          "iRjULCmLUHpmCUTbLShAh5Oxlkox1jZVl2mJ5bEiI3LzcgmkukUgcAsnO6Ji" +
                                          "QhNkaSySpVB+bs0df+JR87QZJzE4s8ZUA8+/DTaNRzYtsCJzGPSB3Nh7JPt1" +
                                          "OvralTghILwjIixlvveF2w8cG7/xlpTZ3UTmbOESU3le3Sz0v7tn6vD9CTxG" +
                                          "l225Oia/wXPRZfP+SrpqA8KM1jXiYqq2eGPhx5977EX25zjpyZAO1TK8CtTR" +
                                          "kGpVbN1gzilmModypmVINzO1KbGeIZ3wnNVNJmfPFosu4xnSZoipDku8Q4iK" +
                                          "oAJD1APPulm0as825WXxXLUJIZ3wIzH4TRD5twcHTi4qZavCFKpSUzctZd6x" +
                                          "0H9XAcQpQGzLSgGqfllxLc+BElQsp6RQqIMy8xc0q6JUC4by8GR2sUw1a/Wc" +
                                          "wxgCA2ItVpr9f7BRRT9HVmMxSMGeKAAY0DunLUNjTl697k1O3345/44sLmwI" +
                                          "P0Kc3A1mU9JsSphNgdkUmE01M0tiMWFtO5qXyYZULUPTA+r2Hl585MzFKxMJ" +
                                          "qDJ7tQ0DXRVduLv2AhsjxxT9/ulF+9lf/eyP98ZJPICGgRCmLzKeDpUj6hwW" +
                                          "hTcUnANPCXIfPDP/5FO3vrokDgESdzUzmMRxCsoQsBUw6itvXX7/tx9u3ozX" +
                                          "D57ggMdeAWiNky5aADCjKueku45K0rHt/4G/GPz+jT/0ESdkhQ1P+WW+v17n" +
                                          "th0KR0w87+JkBDOweq8qAu/HGUO1txVYCKDbfPz6hnb2uXtkSw83NuA08Mu3" +
                                          "fvGvn6Se+d3bTXLezS37boOtMKPhPGCy4aYwK3C0xrp59YP+a7//QbI0GSdt" +
                                          "WTIMAfGogZx/0ikBm6jLPuD2FuD6ELD4/hCL4/XDsVSmAYm0YnNfS5e1whyc" +
                                          "52R7SEPtjoFoeqQ1w0eP/ubjfxo7d6J8UVRYmLPRWjvQDe6cR6atM+q+SPij" +
                                          "Kl+YfentU4fUa3FBMgjYTcipcVM6nAgw6jBgUxPdwZk+MDoR7eJotPLqkf30" +
                                          "1fxrX0yKLHQD03IKyAgkNh413kAU6VpnoakuCELRcirUwKVayHt42YFur88I" +
                                          "eBmShQ4F0ot1PQa/Az6Uiv+4OmrjuFPCkZAfF+MBHJKiuuL4eBCHQ0Ls41Bt" +
                                          "h4LmBew3ABsxI8nzJqRdL+q0YDCElX8OHLzn1b88MSgL2YCZWoqO/W8FwfzH" +
                                          "Jslj71z4x7hQE1Px7hEATCAmCW0k0HzSceganqP65ff2fuNN+ixQI9CRq68z" +
                                          "wTCxxm4eFDvxmpGS1wzh7pRYPiHGSQybj4j4fgqHT3HSX2Lcb//JtYyGs0fh" +
                                          "KMkWVR66UubVqzc/6nvoo9dvC+ca76RhHJ2ldlpmFYc0oszOKJKfpm4Z5D5x" +
                                          "Y+7zg8aNO6AxBxpVYCj3rANsUm1AXV+6vfPXP3pj9OK7CRKfIT2GRbUZirc/" +
                                          "4HAoKuaWgYiq9mcekIWz2gXDoAgA2RKSLROYj33NMz1dsbnIzfr3d373+PMb" +
                                          "HwoEt6uAGc3YCzXt2nJRlpc79eWNga6dG+d/KfqqfgHrBSQqeoYRattwC3fY" +
                                          "DivqIqS9MrC2+HcebkytiJVD7RYk8p6T0g/DeZtJgySMYcklKLCoJCft4n9Y" +
                                          "7gInPYEckJl8CItQ0A4i+FiAkMUamRpfMjjskM/ZlrkLkftdDaUqPlxq4OnJ" +
                                          "T5e8+u2NM3OP3v7kc5Lr4ZNnfV1cdOHeLhGpDsAHWmqr6eo4ffhO/yvdB+N+" +
                                          "Jw3JAwcwtDvUZgvQpDZWwFikt91kvcXf3zz++k+vdLwHRb9EYhChkaXQZ4O8" +
                                          "IwNAeMCUS9mAK0MfvgJ00oe/uXbiWPGvvxHl6HPrntbyefXm84/8/NquTQCn" +
                                          "bRnSDvTOqjn4BnIfXDMXmLri5Eif7k5X4YigBT7KMqTLM/XLHsvA51Y/FitF" +
                                          "rBFx8cPZV59FEuFkYsu3SxMmhtZdZc6k5ZkCf/oATIKZhi+qGod5th3ZEMzU" +
                                          "U7l9q+959cGvDfzw6nBiBhquwZ2w+k7XK9T5MfyRJQkTx0FBJ1V56Urks7O2" +
                                          "XbuExd7wb1yOlMF5uMIe8WcnA/TGV0+oE+Ti4bD6X74G67c/EQAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05eczjWH2eb+5h2Zk92N0Ouwu7DKiL4XMSO3GioRTHOR0n" +
                                          "ceI4h9sy6/iIHd/2c+yYLqKrtqAiUdQuLZVg/wK1RcuhqqiVKqqtqhYQqBIV" +
                                          "6iUVUFWpB0Vi/+ihLi19dr5rvplhxT+N5Ofn5999Pb9fXvoecj4MENRzre3K" +
                                          "csG+moD9tVXeB1tPDfcZtsxJQagqtCWF4QSu3ZKf/sLV/3j1o/q1PeSCiDwk" +
                                          "OY4LJGC4TjhWQ9faqAqLXD1ebVqqHQLkGruWNhIWAcPCWCMEN1nkdSdQAXKD" +
                                          "PRQBgyJgUAQsFwGjjqEg0utVJ7LpDENyQOgj70fOsMgFT87EA8hTtxPxpECy" +
                                          "D8hwuQaQwqXseQqVypGTAHnzke47ne9Q+GMo9sJvvvfa751FrorIVcPhM3Fk" +
                                          "KASATETkPlu1l2oQUoqiKiLygKOqCq8GhmQZaS63iDwYGitHAlGgHhkpW4w8" +
                                          "Nch5HlvuPjnTLYhk4AZH6mmGaimHT+c1S1pBXR851nWnYStbhwpeMaBggSbJ" +
                                          "6iHKOdNwFIC86TTGkY43ehAAol60VaC7R6zOORJcQB7c+c6SnBXGg8BwVhD0" +
                                          "vBtBLgC5fk+ima09STallXoLII+dhuN2ryDU5dwQGQpA3nAaLKcEvXT9lJdO" +
                                          "+Od7g3d95H1Ox9nLZVZU2crkvwSRnjyFNFY1NVAdWd0h3vd29jekR770oT0E" +
                                          "gcBvOAW8g/mDn3/lPe948uWv7GDeeBeY4XKtyuCW/Knl/d94nH6mdjYT45Ln" +
                                          "hkbm/Ns0z8OfO3hzM/Fg5j1yRDF7uX/48uXxny8+8Bn1u3vIlS5yQXatyIZx" +
                                          "9IDs2p5hqUFbddRAAqrSRS6rjkLn77vIRThnDUfdrQ41LVRBFzln5UsX3PwZ" +
                                          "mkiDJDITXYRzw9Hcw7knAT2fJx6CIBfhhZyB19PI7vd4NgDkWUx3bRWTZMkx" +
                                          "HBfjAjfTP8RUByyhbXVsCaPexEI3CmAIYm6wwiQYB7p68EJxbSxZWti8zvK6" +
                                          "pLjxJFDVrExAAvtZpHn/DzySTM9r8Zkz0AWPny4AFsydjmspanBLfiGqN1/5" +
                                          "3K2v7R0lxIGFAPJOyHZ/x3Y/Z7sP2e5Dtvt3Y4ucOZNzezhjv3M2dJUJkx6W" +
                                          "w/ue4X+OefZDT5+FUebF5zJDJ3kWPpY/nIV4z9y7RLey+tDNa6IMQ/ax/x5a" +
                                          "y+f/4b9ykU9W2Yzg3l3S4hS+iL30iev0u7+b41+GBQlIMIBgrj95Ojlvy6cs" +
                                          "S0+bEtbZY7qlz9j/vvf0hT/bQy6KyDX5oIhPJStSeRUW0itGeFjZYaG/7f3t" +
                                          "RWiXcTcPkh0gj5+W6wTbm4cVM1P+/EkXwnkGnc2v5OFwfw7zwA/h7wy8/je7" +
                                          "Mk9kC7vQf5A+yL83HyWg5yVnzgDkfGmf3C9k+E9lPj5t4EyAn+K9T/7NX/wL" +
                                          "vofsHVfxqyf2RWiEmycqR0bsal4jHjgOmSygINzff5z79Y9974M/k8cLhHjL" +
                                          "3RjeyMZMYrgNwu3kl77i/+23v/Wpb+4dxdhZALfOaGkZMpyE+a4GNdEMR7Jy" +
                                          "gzwNkEfXlnzjUOsp3OWgYDfWFpmb6g1wX89Fy7yyv9sa8ryCEt24R7ie2M5v" +
                                          "yR/95vdfP/3+H79yR6Tebpi+5N3ceSiXKoHkHz2dRR0p1CEc8fLgZ69ZL78K" +
                                          "KYqQogyrQzgMYCYnt5nxAPr8xb/7kz995NlvnEX2WsgVy5WUlpTtvLB+Ah1u" +
                                          "1josAon30+/Z1b/4Ehyu5bmJ5Pq/cSdOntb3HxuCdeEO+eF//OjXf/Ut34Zy" +
                                          "MMj5TRbDUIIT1hpE2UfDL7/0sSde98J3Ppz7BFbb6S++ev09GdVqzuCt+fiT" +
                                          "2YDuPJZN35EN78yG/UM3Xc/cxOfVkJVC0HcVA340KLmnfmTp4ALDhtG2OdgR" +
                                          "sece/Lb5iX/+7G63O10nTgGrH3rhV364/5EX9k58Y7zljm3+JM7uOyMX+vVH" +
                                          "rnzqR3HJMVr/9Pnn/uh3nvvgTqoHb98xm/CD8LN/9T9f3//4d756lyJ9znIP" +
                                          "gzIbSwdss1v5tR0LrvygQ4Rd6vDHFudSKZanyQyNUIBjnaVRp5Wk6cgTU1Dw" +
                                          "KSMY1qikh7PQadekocgr05kyCMmQlHGxSCj2YitXFTUi6j1GmBBCYerxK8Bj" +
                                          "MpgWJV+grWa96ZfoHmjN6hI/o2nDrS9MbEN3pa7c5qqNwMGBrZS0doR2VWsj" +
                                          "Vsq1WpKSjlXDy6X50muVitvOOh2OvI29SAfpFFQdx4+a22XfXweOOyxvOK+w" +
                                          "2pAg1jGbdNHJWk89tjjAp74Q2bW26C7NcmjJ+FwoD6ylla7bNrGolXXWGcx6" +
                                          "Axn0C0qp0q7YCz2q+JuByJf6brVeL4Y235UjEsqLpuseSplkURx2TWPi9+Q1" +
                                          "XXHCyngO1G1x1EnmfCf2QbfHWzI921atVU1nFHcRdBSBYypGmZsmxW2RlfpA" +
                                          "ZPTqmA+qYGQRKYHV2+q2ViowsTwKKBzFZFKo9prdeGTiE+immkK0y1bQoQEd" +
                                          "i3RbchpTMWHL/Y0p8LMlFTJyme0X3dhftEZ1N51uqK1JaONqupF9gVFSfSAU" +
                                          "FOC6HSIaU27SWw6DieGXzbkYLwZzJcXns7i9xLT5RpyqS6eT+BLXq0nyptEh" +
                                          "nNFI3IpNCm9hTaKnb+lVuSnXmfGUDpNkUnKlAs6Y2+7YZFOm4xESStpKpTSY" +
                                          "skwkqB5bnbW8tLAcLrp2oR12u9jKRoce3mF9Up+2Rpq1IYVZwwob84Jcn1fU" +
                                          "Zj91hw1u4sopbfF+A2B8LdoubV8mu5vI56IFRsfdeLAc0tHA8ksVP5VG8Wgh" +
                                          "WsZ4LbC0zQodz6aFyRJ+qVB6eZhYppsU1+LUKtlMedk0ujibyivbjExhJVOh" +
                                          "M6wwxkgfmBK/5b1pHV2GBUVDmXGVHIlM2iTCqihQVRRrTKTBOF2AkGbSNsfX" +
                                          "8YFOMhwoDjeBZE1WepeN110jsTYbtVWKq3KbxBLLm4i4MLGXwyYv4JaK82kB" +
                                          "hqhT2TRq9CRpW6VSeWhIWDznxqLGoXzg+VS11y+u58bC90tqm9OTco0km/NS" +
                                          "OV17W5EaFie9Kg0mY7PtTZeD4io1LBvWxa1nT7uDdFjsLdtqV8RjZzAdMLbG" +
                                          "tdwwIhKHF13Da5hRdUQYPZdiGkWK4yLLLkhhtVSezZM5KzAZXjftEJNxowxi" +
                                          "uTMxCF+UNnSr5/FCKgNRqSSFTm1OySNv1E5ZftX2NctKWBmtN61R6FXGI7/b" +
                                          "31YTueBXGIEmlttqe1wKhbgoYTM5TlY0VeqCqRfUNLI+Hk9qnandT/h+W+1R" +
                                          "1KLQiBxWGKwnVqVGmsUhjhNljCBC1o67XKEn41TRFmpMyHv6YKWYgt0sFPsF" +
                                          "YPRnLTAs+/PtQhRYgZtQaFDqWOVquZ+2ekmf8RsMCUaFxnw8VSJ2U6L0cA2j" +
                                          "t4ZFVgutWRqmbrlaVWS4Lt1ejWEQpT214Qnrih7P9IksONSAo+ddjWtwWLk1" +
                                          "xDeBazZWTV5JhdTujxM6dEdhXYgrBtjM5yQGklqEu+m8USZXq76iUjNjYG7L" +
                                          "EtWg171INSOi3CsEHYARbazNpeh6ghUgNVMfFTl0NkM3RdIBeqE3LsRVEmXM" +
                                          "emMYq37VpyKs0xaGRZBMF3SvsdS4tKI7y1I0ByYfV/FBRBWq/QjXNu2NU+FV" +
                                          "VMGXkzmrpjxOLt0h6Pc4nWvTW0JaxD2cLiSBV64tOFQiMWy07BbavAJmk26f" +
                                          "0truSkywgmHW7cqa5aJGqRU1Kk22QWA6zRLYvBFOeZta2IWFM9D4slqM9a1c" +
                                          "Lo1JvsmBtdtyVX9UjAsqh0XLtZa4pFJhqsJ0vLBZbjxbb0YNtSKPKxLooz7K" +
                                          "c8a6Z6ELDZ4nBEITJLxV76/Wi4lsePK0X3GoVVxZ11dCwimxaKL9hjsmVcYF" +
                                          "HOubGl4oakkwL2x7bGfUKODd3pZamQOdKOImJVSmnuNKZkQ32bFsBELcm0rb" +
                                          "DiBKi1YUVKtdtW7z+ohoFVxQ5EYSRqUVwdigxNAO1lGLo02R0lpov95hekYU" +
                                          "sYRapzujAhsSxTrQCdauqzFO1cOkW3VSxh8rLOoXFg26ac2rww6bOsVltdrn" +
                                          "V2xpQYsz1x9is2or1tIOE1prspgSCamPmkUO3prUhKZselYwC52Ul9WV5Phc" +
                                          "paxpJS0aDFAjGXVr9NivVNN4QieJTaitxiaxvTZfjFOd9MYLzui0+dF2uSbW" +
                                          "hLbyOxO8w89LrLzEMAYstu2woOm9vjmbjisVIVpO/VTGKs7GdWvKhkZliayM" +
                                          "9Q5TshTLs1sLueCG6bDH9DTPJsRyo5wsUDJdVaXBsEIl9cSDQbjGA2oQCnaR" +
                                          "mk/Rykbj5hzurWvDHkmPe1p3UmqPl4JoBDJGdCi3F0mz1cLwa7asmt1ZWlrN" +
                                          "Gy61okrjHs+Oh4s1jg/6aVEJl0431QJcwUkc5frLTuw2QSWi2jK+oNM5KDnM" +
                                          "2PJksqbOBiuporRRBetpvq+tOkGdH/mquxhLAMQ0ri0axsbv+nytH9AltCOr" +
                                          "S3MLDGbaIMcLs+pVJoUV1lBFwKy2fH8hm1aPpV2G1gDh1Bbkqutwi6ZsMlaV" +
                                          "7sIKQhEG2jIosy9I9tjT+ut1aPYx0QpM1tSA0pAEn4NnDGLoMJOyWkWj0qCP" +
                                          "Dzl8Q5pwjw4IceBo06KsDDsqq7e9Rkh1ZrYfVFSX0DR9iG03Sh0doEyMM1Qs" +
                                          "x6CxEcTVZuQ1xFncMkxQK5obea7haYqiJrpR2LgzXtaaC53WTWk+EolhFW6O" +
                                          "lNqnBb5mU71CX9usmELBVbFovjRmXHuzSTpWpcMFDlhuVW1uVwmsig38aDKi" +
                                          "neXY4RubydBfO0Td6WrzRn9us4FRbhoaaZbnxMJY1Sdkr+9P2D42ZzvhhioX" +
                                          "F1jLAK2g3kqqMidOy7VWM2qZizDC+aRv63DXEOWKWRZNWsNcatLtibqB+m1X" +
                                          "KQMdF+GOLwikVfPRWrkmtzcNLY0rTt2o634Ui6UYNcl5rzYp97XtmBmZk6TQ" +
                                          "qjPFabkiBGZIDuHHYdRMFDJeFrdDq98qR/2uWp3JDoVN2tMC6jZRuIstG5U5" +
                                          "SbQrpIw1RxSVfQZ3f7yTyAP5gfGosQgPINmLwo/xBZ78KIYAuSQtQxDAYxpA" +
                                          "Lh91OnfcT3RMzhweUB/KmjQxLue9mYNWTHbqeOJe/cT8xPGp5194URl+upid" +
                                          "ODJCDcgMuN47LXWjWrexCZC33/t01c/bqccdkC8//6/XJ+/Wn81bAHd0Zljk" +
                                          "SobJZV3ro+70m07JeZrk7/Zf+mr7bfKv7SFnj/ohdzR6b0e6eXsX5Eqggihw" +
                                          "Jke9kAB5+o4jmSurShSox3zf/mbpi7e+9NyNPeTcySZRRuGJUy2X12luYMNv" +
                                          "v4zUQWf5Cjxeu/Hxysn+CzTrfVkkXIfXUwetx/yevX3Iy8aHk+N4uiNQ9o4i" +
                                          "c3wQFgHytuOjP+1alirnVr8hOHZ+UpaWlpq14X5w9a3FL/7bR67tzpEWXDl0" +
                                          "wztem8Dx+k/UkQ987b3/+WRO5oyc9eqPmxnHYLsG8EPHlKkgkLaZHMkv/OUT" +
                                          "v/Vl6ZNnkTNd5FxopGrekT2zi7k8oXLV9Fx3OR9XeR7tWofZ8zobbgHk/pUK" +
                                          "DuK+vu0q2apwnIjPvtZR+CTZBCAP3621manx2B3/ouw6//LnXrx66dEXhb/O" +
                                          "A+WoO3+ZRS5pkWWd7MadmF/wAlUzcj0u72LDy28+QB67V9cVIGfhmAvt7aBh" +
                                          "iXj4btAQEo4nIWOAXDsNCZDz+f0kXAqQK8dwALmwm5wEeQ5ShyDZ9P1Zc/BE" +
                                          "tTgobbnhH3wtwx+hnOzuZRUm/1frsBpEu/+1bsmff5EZvO+Vyqd33UXZktI0" +
                                          "/xeERS7u0u+oojx1T2qHtC50nnn1/i9cfuth9bt/J/Bxzp2Q7U13T4ym7YE8" +
                                          "lNM/fPT33/XbL34r73D9H3e1QJhuHAAA");
}
