package org.apache.batik.apps.svgbrowser;
public interface SquiggleInputHandler {
    java.lang.String[] getHandledMimeTypes();
    java.lang.String[] getHandledExtensions();
    java.lang.String getDescription();
    boolean accept(java.io.File f);
    boolean accept(org.apache.batik.util.ParsedURL purl);
    void handle(org.apache.batik.util.ParsedURL purl, org.apache.batik.apps.svgbrowser.JSVGViewerFrame svgFrame)
          throws java.lang.Exception;
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1aC3QU1Rm+u4EQSCAQ3q/wCiqIu0ILiKFKCAkEF4gEUg3C" +
                                          "Mpm92QyZnRlm7oYFwSqtBduCFPHVA5zTUyjoQbCeWvvS4unxQRXPUbGKVPBV" +
                                          "X0iVttYebWv//97ZndnZRyhJmnPmz+x93+9/3zuHzpGelknKqcYCbL1BrUCN" +
                                          "xuol06KRalWyrGVQFpbvLZD+tuqDxbP8pLCJ9GuVrEWyZNFahaoRq4mMVjSL" +
                                          "SZpMrcWURrBHvUktarZLTNG1JjJYsepihqrIClukRyg2aJTMEBkgMWYqzXFG" +
                                          "6+wBGBkdgpUE+UqCVd7qyhApkXVjvdN8mKt5tasGW8acuSxG+ofWSO1SMM4U" +
                                          "NRhSLFaZMMnlhq6uj6o6C9AEC6xRp9sQLAxNz4Bg/MOl//hyR2t/DsFASdN0" +
                                          "xrdnLaWWrrbTSIiUOqU1Ko1Za8ktpCBEil2NGakIJScNwqRBmDS5W6cVrL4v" +
                                          "1eKxap1vhyVHKjRkXBAj49IHMSRTitnD1PM1wwhFzN477wy7HZvardhlxhbv" +
                                          "vjy4695V/R8pIKVNpFTRGnA5MiyCwSRNACiNNVPTqopEaKSJDNCA2Q3UVCRV" +
                                          "2WBzusxSoprE4sD+JCxYGDeoyed0sAI+wt7MuMx0M7W9Fi5Q9q+eLaoUhb0O" +
                                          "cfYqdliL5bDBPgoszGyRQO7sLj3aFC3CyBhvj9QeK66DBtC1V4yyVj01VQ9N" +
                                          "ggJSJkRElbRosAFET4tC0546CKDJyIicgyLWhiS3SVEaRon0tKsXVdCqNwcC" +
                                          "uzAy2NuMjwRcGuHhkos/5xbP3n6ztkDzEx+sOUJlFddfDJ3KPZ2W0hZqUtAD" +
                                          "0bFkcugeacjjW/2EQOPBnsaizWMbz8+ZUn70WdFmZJY2S5rXUJmF5X3N/V4c" +
                                          "VT1pVgEuo8jQLQWZn7ZzrmX1dk1lwgALMyQ1IlYGkpVHlz59460P0rN+0qeO" +
                                          "FMq6Go+BHA2Q9ZihqNScTzVqSoxG6khvqkWqeX0d6QXvIUWjonRJS4tFWR3p" +
                                          "ofKiQp3/BohaYAiEqA+8K1qLnnw3JNbK3xMGIaQXPMQHz1wi/iYgYaQ12KrH" +
                                          "aFCSJU3R9GC9qeP+rSBYnGbAtjXYDFLfFrT0uAkiGNTNaFACOWildoVkGFbQ" +
                                          "ao82m/o6sIbBhrVxJRpVwZoZcbZA0iKwvwBKnPF/nCuB+x64zucDlozyGgQV" +
                                          "dGmBrkaoGZZ3xefWnD8cfk4IGyqIjRgj02H6gJg+wKcP4PQBZ/pAtumJz8dn" +
                                          "HYTLEEIALGwDYwDWuGRSw8qFq7eOLwDpM9b1QAYkuHaOTP6Ajp7lcjvwjQZj" +
                                          "z2svfPg1P/E7JqPUZesbKKt0iSmOWcYFcoCzjmUmpdDujfvq77r73JYVfBHQ" +
                                          "YkK2CSuQVoN4gs0F23X7s2tPnjm974Q/tfACBnY63gzujpEiqRmMnCQzRnqn" +
                                          "rJXY2KCv4M8Hz3/wwT1igZC8smpb/Mem5B8A9sAxOpeh4EZu3+ZdeyNL9k8V" +
                                          "6lyWrnw14Fse+uO/nw/c9+axLPztzXTjCpW2U9U1ZylOmRYlLOI2NOlxw/Ib" +
                                          "/Xa+86uK6Fw/6REiZbDpuKSiv68yo+BJ5Dbb2JY0Q+jgePCxLg+OoYepyzQC" +
                                          "DiSXJ7dHKdLbqYnljAxyjZCML9CSTs7t3b1Lf2bzRyOWXdO6mkuR21/jbD3B" +
                                          "1WDPevSyKW86xgO/d8gHFh06Nv8SeaefOxg01lkcU3qnSjcjYFKTgifVcDtY" +
                                          "0hcmHe/VWC9aYXnyWOnR8OObKjgXeoOXZRJYRXBg5d7J05xEZVJ7cKoiAKFF" +
                                          "N2OSilVJyPuwVlBvp4SbkgFCmEFA+qJgjoXnUtuM8v9YO8RAOlSYHt6+nNNx" +
                                          "SCq4dPnxdSKSS3izy0DaLnEUFOy+CvYQOVKxXAO2Ky2K1KxSNB3/Kp049dGP" +
                                          "t/cXgqxCSZJFUzoewCkfPpfc+tyqz8v5MD4Z4w7HiDjNhDMb6IxcZZrSelxH" +
                                          "4raXRt//jLQH3CK4IkvZQLl3IbbG4qKq+LZnczrHU1eN5CpGBkapbTEji5QY" +
                                          "542VHqCjjDfEwbDwqYX3vqn46d9ZP3nvEaHu47M09oQEBw8UyadiT78rOgzP" +
                                          "0kG0G3wwuK3x1TXPc80oQtVNyaNLMUHFXTLR30D7NDG3+rkWvvenE1741t4J" +
                                          "bwHsTaRIsUDFYbAscZCrz6eHzpx9qe/ow1zEe+Ca7PWkB5CZ8WFa2MeXWmoI" +
                                          "azwMEgTOUwz+AiL4S7HJx9nEPWaaAeT5j6N5D74885UDP7xnnYB0Uu7te/oN" +
                                          "+2KJ2rz57X9yycswPlmiO0//puCh3SOqrznL+zsaj71nJjK9PCDs9J32YOwz" +
                                          "//jCp/ykVxPpL9v5RqOkxtEhNgGGVjIJgZwkrT49XhbBYWXK1I3yWhvXtF5b" +
                                          "4zZ6PVjK3HHzYiR8hJuP5fkMB4MBFU1She0AB6xSLcparbxsqDeVGMQE7bZG" +
                                          "BDeVnWnb/cFDgn1ezD2N6dZd3/sqsH2XMDoi7ZiQEfm7+4jUQ+gHXyXqyLh8" +
                                          "s/Aete8f2fSbg5u2+G0zMYWRApBrfL3Oll0UUb8AIynLAx1ZrlZ1jaKpS9aJ" +
                                          "+EvRA6ncDSoTGcKOv680+JzXZYfex6G3zXVuw9aWpy6GJArck3GVYlN5mhsZ" +
                                          "pWiMx2Q38zUxg3HDvOGXQ38++8De0zxEMxIki14PSrd/gsfz7ij97Y6yglow" +
                                          "M3WkKK4pa+O0LpIurr2seLPLIDoZniPCNrcxumPEN9ngxrEih1i6DgHC8o4T" +
                                          "n/Zt/PSJ8xmGIT3CXSQZQq4GIJmFww/1xtgLJKsV2n396OKb+qtHv+TWtliS" +
                                          "wTRaS0yI9xNp8bDdumev15/8/ZDVLxYQfy3po+pSpFbCfB2yLggFqNUKqULC" +
                                          "uHaOcPfrioD051whGXzKZBwWWIKhV6bHEOPgmWLHEFM6FUPklqTb89RtQXIr" +
                                          "KIrjiWsSjGpW0iYv4JS3vU3s7OauBKEY64bDM9UGYWo3gbAzT90uJNsY6Qcg" +
                                          "zKOWbCpGyifldJa85/ZugKQE68rgmWFDMqMLIXFbPNhaSdI+1kIGxjv8OA9O" +
                                          "+5HsBo+DymQwK3vw5fEe0+pXy1sr6t9NGvX5tkPAf02u91WM9GrWdZVKmne1" +
                                          "+LM94aC+pztRn22jPrv7UB+TcaYgjon4GeXypSE+xi/yMOLXSH6WYgT+OujA" +
                                          "80g3wMPrZsFTZcNT1YXw+J1WjyUxurLDc5eFDY3zGxW6jpq1kKsK6X0qP/Cu" +
                                          "UKEmgciBlvN+x5AcBUBbuQ3MJpw92nUl4oD8ZFeDzE9Esh+RDPGGngF+NG4Y" +
                                          "XSiTLiMn5uCdXs8jhKfF6pG8wgtOdRw6ITmJ5A0kZwBwujYuiaOXBxxwX+kI" +
                                          "3Owrei8Xzkjf5nMgeQfJn5G8n8YHZydd4G8+zlP3lwtEzpnvBge+s0jOIfmE" +
                                          "kSLwWPwsLOPAipti13n6W4tH9dHb6geIiD/PcZG34zZl7/E/fFZ6W7ZMj9/F" +
                                          "2F29/U6+VjCtmFXcyZPpVOJaDOmQhS3xMCznvQ4fS8R5/TrUjsGOdvDpU8qR" +
                                          "FO1Sd4IAVVj8RXognAQsLCcGLxs0qeT6N8V2x3WAU1iui4UbHj25ZQaPW0vb" +
                                          "FUth4lpQ3MQNSbuJS54AV6bdUGVFMix/cGTbs+M+ahzIrx4EaLjy9Qkhrhtt" +
                                          "5fBx5fATEdyPTNuTvQ5++hOWn5+izCz604kHxNZyHVmk99m4+z/HP9x0+lgB" +
                                          "KQyRPpjuSiaFfJyRQK67PfcAFcvgbR70gjS4n+gN8VOKCyANZanS1PkeI1fk" +
                                          "GptnspmHphCvgxuYq8e1CA4703O2GDcMd604DLl4ubrFJFMuALzU3m2PidEF" +
                                          "4N7P5YO0eMxdaYCHqg5VNTSEl91YXxNurFpaVzU3VMPl1YBK37Lc1jrPIdQ3" +
                                          "FTVSLZkRoZf7v+o9Yc7QY1dzvcwErqvB4hb2VMJzwdFJS+8bls/S/xXJ59hs" +
                                          "MJKhSIZ3m6X3leepG3txPtI3GskYJOPAyLdCiloN4TVWr+w0dpflwc5XwefA" +
                                          "N9y971Ikk/437Aoc7MC/axKmAh2CGMxTN/UCQXQmvgG7XeHAGUCCA/im4ZJ0" +
                                          "prSsx8rjnQZzVj4wp/M58G0GkquQXH3RYLr2lGdB1+apq+o0kNcgmYNkLiO9" +
                                          "BZBVqto1WNblw7ImhWUtkgVIFnafUi/JU3f9RSr1YiT1SJaCUjNdHCZgdajT" +
                                          "2N2YD7vlfA58a0TCmdrUzXIYzp9ulDsOrA5vLsy4wfDoyZWU+aROi+sqJKuR" +
                                          "RCCBWycprGsktS0f2tGUpOJ3F741SNSulVQ3mN40VdW1KF/k2uydsKqZN2jv" +
                                          "RBri41uNI1nnbLrTwG66MGA3INmI5JZuEGPnOMLHL5ZW8qV9uyM4b++0uG5G" +
                                          "8h0k3+1CTH9wYZjegeT7SLbZ9QlGBmX7uAXvIYZlfF8nvgmTD+8tLRq6d/mr" +
                                          "4r4y+d1WSYgUtcRV1X355XovNEzaovBNliSvwnAlOyBL7OgciJE+zg/cqu9O" +
                                          "0fkuiEqzdgYlwX/utvdASO1ty0hP/t/d7n6YzWmHB3D8xd1kNyMF0ARf90D8" +
                                          "68sR+A7uiJmur18m5EwVF8XFJ5Bh+cjehYtvPj9jv/g2CKLvDagkmGH1El83" +
                                          "8EELMnJa92jJsQoXTPqy38O9JyaPbAeIBTt6NdIRL2KBEhgoEiM83wlYFanP" +
                                          "BU7um/3E8a2FL0GSvIL4JEhzVmRepyaMuElGrwhlXk8lM6rKST9af82Ulk9O" +
                                          "8dstknFN7W0flk8cWPnyzmH7yv2kuI70VLQITfB73nnrtaVUbjebSF/FqknA" +
                                          "EmEURVLT7r6yJ6x90xJWRsZn3oR2mKD2DZFip0RwJm/Oih2cEpuVSOPC+iM3" +
                                          "QO7CoUWGkUzK/H83uCK3ZzFZpJ3L6mH+im9H/gsg3jC9HC0AAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL17adDsWHVYf+/Nvr1ZYAbGzPBm5g32IPikbvUmz2BQq1vq" +
                                          "RS2pW93qbmF4aGu11NpaS2uBwYbEhjIxEHuwnQrMjwTixGFxJabiVOIUTio2" +
                                          "eKHKLjsxTplxnM0Gk2J+kLhCYnKl/rb3vQ3mPfxV6Xzqu5x7zrlnufeeq09/" +
                                          "o3Rr4Jcgz7VS3XLDfS0J902rth+mnhbs9+kaJ/mBphKWFAQTUHZRefKXz/2v" +
                                          "b390df+Z0m1i6SHJcdxQCg3XCcZa4FpbTaVL545LO5ZmB2HpftqUthIchYYF" +
                                          "00YQPkuX7j7RNSxdoA9JgAEJMCABLkiA8eNWoNO9mhPZRN5DcsJgU3pvaY8u" +
                                          "3eYpOXlh6YlLkXiSL9kHaLiCA4Dhjvy3AJgqOid+6fwR7zueL2P4YxD8ws+/" +
                                          "8/5/drZ0TiydMxw+J0cBRIRgELF0j63ZsuYHuKpqqlh6wNE0ldd8Q7KMrKBb" +
                                          "LD0YGLojhZGvHQkpL4w8zS/GPJbcPUrOmx8poesfsbc0NEs9/HXr0pJ0wOvD" +
                                          "x7zuOCTzcsDgXQYgzF9KinbY5Za14ahh6fWnexzxeGEAGoCut9tauHKPhrrF" +
                                          "kUBB6cHd3FmSo8N86BuODpre6kZglLD06FWR5rL2JGUt6drFsPSa0+24XRVo" +
                                          "dWchiLxLWHr16WYFJjBLj56apRPz8w3muQ+/2+k6ZwqaVU2xcvrvAJ0eP9Vp" +
                                          "rC01X3MUbdfxnjfSPyc9/GsfPFMqgcavPtV41+ZfvOflt73p8S98cdfmB67Q" +
                                          "hpVNTQkvKp+U7/u91xHPYGdzMu7w3MDIJ/8Szgv15w5qnk08YHkPH2HMK/cP" +
                                          "K78w/o3Fj/+S9vUzpbt6pdsU14psoEcPKK7tGZbmU5qj+VKoqb3SnZqjEkV9" +
                                          "r3Q7eKcNR9uVsstloIW90i1WUXSbW/wGIloCFLmIbgfvhrN0D989KVwV74lX" +
                                          "KpVuB09pDzyt0u7vqRyEpRW8cm0NlhTJMRwX5nw35z+ANSeUgWxXsAy0fg0H" +
                                          "buQDFYRdX4cloAcr7aBC8rwADra67LtxoPkwv4kMXbe0nuNFYVdyVMDffq5x" +
                                          "3t/gWEnO9/3x3h6YkteddggWsKWua6maf1F5IWp1Xv7sxd8+c2QgBxILSzUw" +
                                          "/P5u+P1i+P18+P3j4fevNHxpb68Y9VU5GTslAFO4Bs4AuMl7nuHf0X/XB588" +
                                          "C7TPi2/JJyAprPM1xY+zoN8zV3fdZO43eoWvVIAqv+b/sJb8/j/7q4L0k943" +
                                          "R3jmCuZyqr8If/rjjxI/8vWi/53AUYUSUCzgAx4/bbSX2FluvadFCvzvMd7K" +
                                          "L9nfOvPkbf/+TOl2sXS/cuDcBcmKNF4DDvYuIzj0+CAAXFJ/qXPaWeKzB04g" +
                                          "LL3uNF0nhn320JPmzN96cirBe946f7+rUIv7ijYPfAf87YHnr/Mnn4m8YGcS" +
                                          "DxIHdnn+yDA9L9nbC0u3VvYb+0je/4l8jk8LOCfgLbz3iT/68l+gZ0pnjr37" +
                                          "uRPxEgjh2RMeJUd2rvAdDxyrzMTXcmH9yS9wP/uxb3zg7YW+gBZPXWnACznM" +
                                          "KQbhEYSZn/ji5isvffWTf3DmSMfOhiCkRrJlKOAlKKId4GRpOJJVCOTJsPSI" +
                                          "aSkXDrkWQPQDhF0wrUYhqleDeF+Qls/K/i5kFPYFKLpwFXU9EeYvKh/9g2/e" +
                                          "K3zz37x8maZeKpih5D27m6GCqgSgf+S0FXWlYAXaVb/A/Oj91he+DTCKAKMC" +
                                          "vEXA+sCik0vEeND61tv/+Nf/3cPv+r2zpTNk6S7LlVRSyiMy8KvhCgTxFXAG" +
                                          "iffWt+38YnwHAPcXtlkq+P+BHTmFWd93LAjaBZHzQ//1o7/zkadeAnT0S7du" +
                                          "cx0GFJyQFhPli4mf/PTHHrv7hT/9UDEnwAsLf/vbj74tx9osBni6gD+UA2g3" +
                                          "Y/nrm3Lw5hzsH07To/k08YV3pKUgHLqqARYTajFT13QdnG/YQNu2B5ESfv7B" +
                                          "l9Yf//PP7KLgaT9xqrH2wRd+6jv7H37hzIm1x1OXhf+TfXbrj4Loe4+m8olr" +
                                          "jVL0IP/H557/V//4+Q/sqHrw0kjaAQvFz/yH//c7+7/wp1+6grO+xXIPlTKH" +
                                          "lYNh83+1609s+BDSrQY9/PCPLksEOpqWxzYUVTsjnsBH6AaOCWPTi5AebQzI" +
                                          "AYGvO2RV70x1lBh6NlYZpaIztuyGuyBjfhO21Iggua6A17LJNDXdkUxos+2W" +
                                          "r0ZOMhrPualMDQSuJcwRQwjDhSbPtjCMNURHdcRxuurbDmdnUIKhEAajWdTN" +
                                          "PEqz1s5goywImS63/CnBJJFrIfXBWLJmqU8JI9KTt7TYhsJo005krunRRB+j" +
                                          "IsHvzFKRIaWV5I43VXsomDzNi97QV2bTsd/qbqfrUPJFesJQ5b7ZXwSaZ6w2" +
                                          "fo+wovU41StSfzLstNb6cLbYZHOSqkNxi2qtVd2bdqDphhDUxiZd4d56Lphb" +
                                          "lWnag7AWSgE1a0pKxCcU5C5nPFvmh8PqlBmveJqUxOHQsVabemTW3TqB4R2i" +
                                          "now9LBjReMJk1ZYOD1kLhlfpuBLC7YDEeZVBEl91aGk28315wveMKbuZlgdu" +
                                          "WZSa69AjWh3DqjCUtO71eYWJN+OW3eZrs7oi+HR1W9YGieSVt6tU6A7M8Xre" +
                                          "ws0q1usO+fHECJ12mRuW43hFZky10YjTRlfcSr66spKVvN2aabWO1QR43PR6" +
                                          "A4HxyMmYcvDa0EiJmB8zOGEwjMBNNq7XkQZ8v80QeGWETgViLFRmrSwKEt71" +
                                          "/E41aEN9IllQbc1NNRUJ8B4Uh41hNEyQYWOGkUZthG0gYNvudCUjrLJcbFTL" +
                                          "oGtyu8XpbpBR6XjENgLaRCWSQIm0tdqa2Egb1OvtVkiUhWqaCiZSFkYYo+t9" +
                                          "vr8edyx57AY42ZlUQwKpVevEoN1Pe4aip/RsZfAoL3Sksesg4SCYCyqxYWKF" +
                                          "iDI8rTDR0IzHChV1V2s3gGtAoVCnnoXrdtZJoICd9i1SVZftPjrgxMoMWYmb" +
                                          "aYi3EZlcK5GuSYppzuBKZ8RyLSeQjGw2lLMmJE6dBjJTSVvsLyp8zZ9P+zZZ" +
                                          "m6MMLFQVYVL2BL0TuU1zRI9motMQM9+el9V12Yp1nB6mo3LPWlBrT+haWQ2r" +
                                          "1hEO8RkI2WgsOdzUKRdqdYHkMRGoL8Mrk0zY8G5C1der7WY922hzRK2P5tve" +
                                          "dGa6zrjPV0NyNkY9dzkwRh4Kt9yVtMCNzgaHmoPyhnacGO0z8gBNhlRPGs25" +
                                          "4aiblWMDNhb6QhqVKwO/CyaC70/RMUYR2EbjIJ9vLRxKxkNzvmiT9JL0J0iE" +
                                          "rw2KmTASiRPszLBUV1hTpDyS3GbFht160JNbK19I+mNPiEVXVGQRR4xBvI1b" +
                                          "A4cjYYeIWlBSr2aR0rbcLKX0kaBSdstfSy4limiiLWdOu6ks19UelW565lg3" +
                                          "kUq3rvd1KB4oXJUbtUTYw8PI7mdN1ekuJnSn08NpKm4v4vYsosZ83NyQm4bG" +
                                          "0nHbG2JyeYQv1lFXYidcHTe9hqWY29gciWZWCbZLTi9zcKfR33BTUQvkwSBE" +
                                          "DN5mZ8qCVFwiM+2p7antyFxuN42G30D7C2HZ6o4W60GF4KOR4DJVPUDICjpv" +
                                          "BJWQc0wba1RHcLjEiZazqKN6Fplex9iM7aFDjLKxs3H8/nxRGRDb6rDZzVA4" +
                                          "jidlQxeJZmB7MjzU7FqriWMBnrCetqp2xAiFRFVLGRpbN4W6lc58Jy5XyUCD" +
                                          "IhZ2YljBICmhuSzM5hOT8GaVKTYti6nF2uOFRbO9CsNaSQz3ZHguQc16NKiT" +
                                          "MVwfdwxRbnvRgDe29WYK1K1fa8typb9ARpCpaxyR0DrEugvNS7MR0Tb4eb+h" +
                                          "dgcqLW8WjmXiSWqKxJDGCH4SNEJULtPLipyNU3Y2V9m6vY7GlTJsym20VZ61" +
                                          "OW3Lp4NZs57oLKw29S65QurMtslrkrZkEx0pW2tlim4c3lTMBTmY6MZSUNrh" +
                                          "AlkpdleDhRmBSYu5k85YZ9xkWXlg6nPNZefiuL8Yz1t6TW30kVrSEYV+Qxm4" +
                                          "Bj4gSabC8oYl9FMuigWrtfWqvLzWScLukDi06eumO3emYTRsbrEF2xzjrMUv" +
                                          "umEdchgm4YlNVeWcROUHPI8aWYq0JdrpTEk2hYjtYsQKg2SOs5VBWhmUBwnP" +
                                          "tFB44CFVTKW4EFbm+iYheLFPTjNXi4n1kvOWChSmm6y5rQ3bVbEaN7pG22RW" +
                                          "7aFc7yWKKPq8ZiXdqi/NxyEMm/SoixKDam+9FUe0hfZkmapuBhuIFh0l87vT" +
                                          "ssbUCA+ELsmTJx0TuNtFrVoRuhvCNNvLTiy3481ijm43TrWuYiJweNuO1I2q" +
                                          "jSGCuaNOK25OU0k1Jo2mz+oZh6wphELjOAIeojyZc0oTcUehwKQSQw+nXXI+" +
                                          "occo0m4wbQqF/DUI/5rTKTeq5bDal+NuMJHGvWDaJhcyHigi4Wd1DcT5BPgR" +
                                          "2I3LWUeDCKnBzdatGiE2Z6RUGWrzme32pCwedvQJO40zCDfoKt/o9hPM6XAz" +
                                          "ScK1Sc2sM7V2o9ps1qZtrpE4zqKFTKNGCNAyUGXQr/hZrTHH0lQJYs6yDRaB" +
                                          "YS8iVijPbvzMoaEskMxG2embA4wj2gHWRysLNs6AhAkPTtdCwnk0tq2NN+w6" +
                                          "CTsrRqcowez1dTFe+5MqNl/JrcVsPij30HS22s5DsiZXM7HOCeYA7XazhTFu" +
                                          "rvoRV1uuh63qsEVOy/xKQ/BWPeFpBexjZLBya2sCNRx1GrJItcC7M3NkWCHb" +
                                          "ulPWsnaFqauiisLBJuhW5sO2azREY9RZ2g2oak5HkN6dp/NNSq+aAYxrodZc" +
                                          "Vpa8rNeiCkQh2XAxG+Ney1/SKGtZyHQqN/Fe6oClR1n0LbFsSgOPx6Q+1NmO" +
                                          "8bqjtHl3QikDFtg8AvWzubhYakmdQrO5EMWYNPPSOtXHfWWNUsLCYmr2KhC9" +
                                          "mTFMwCKgmU0THe22tyw1B78gqNnWkCzpDJPe2ihXOd5XYT1YZg3DxBqLer7i" +
                                          "jYfobD0YVD0JYhHa60W+Xwk0mqN7bVd0DI5gfCWJbK7DYI6e+B1jVTbqbb1L" +
                                          "NN3qxIHFEOb4fjOxqd4EJeb8SBxtqlQPxNk4hstJqNP9QSBUHBSrswMZ2oTd" +
                                          "LTSZhZbBx5OxxCNpD0sYrym31cjWtuUa3ITFtkAni9EyBbES8niPlIllq5LS" +
                                          "uk5umOlgM6WJPFYo3NI33DZSK8crap4NxFY8m/UGK6Eudzssp9szutshh3Vy" +
                                          "yq2tzURuYuNwNO/5g55vGrOANylvhhiLbbXPo9spGjRYKWoNOot6VW4PsSm1" +
                                          "mLmoLuPZBEOiPhMs6iNFzwbsTAY2nRpLS+1LzRosRvpg1Kk3fTAe2R5uhnRv" +
                                          "Tsocs5J4tQeV1z0qMbdNFsdYqNYNWi7UTu1RPEC3cW3Z0RDIm6flwK+HGENt" +
                                          "57VwzeFLpBJh5dkQo/yZKgoD29HKED3EqhIBeVk4dioVk/O3jWkLmijSAvhI" +
                                          "p0pp89TjO1BiwOmQped8tz5b6BOIjUy8iehoPOR8MSAnosJMyot5DPXLMzOd" +
                                          "JpFPt5WaRrYXaEYls7rpbcrrQTCoz5ENBxPRdNCxdcVoWVsGSmq40pq25GiE" +
                                          "DvtejFWcqVV1202R1MAiDesEK2jc5ijK0UmIoaqLOW9MaGPo1CJCnQdNczVY" +
                                          "knWPasZ6yKrjuN6b2P0ajqzFuBVH5iIyJHbeSpJ4Dq17KBv7mtGcZ2tzWXOG" +
                                          "ujZa9p0a1XSai66YqmqVakKZxaFWHHYyz9m2dA0KEJPtLe3OmqfjGRcHNMvh" +
                                          "hhcaZbCQnFXDLqZ25bqu9Yw2zCkihQIfYTXgDrwkxfqsIQ5NDCYrZAWDp3VI" +
                                          "MInQJudKKnKewPalNmuPVjxYmRGZsx1Vl3xzXIMn/tQMKFbdtr1pczMmwZ5D" +
                                          "rfZwQTCb47mrO/gooAmFopMALBkndaYpVBJ0hk/LRmRUp3LXrNTEkcTNkK1M" +
                                          "TsNV1fKAZEcML0d9vlbFgR6rU0ogh0YCK9REDqAhJK2ynp9UOxJtpthovfJX" +
                                          "YVhbtpLaEp901JSbMNFkO6pB0IqdOTXIyIisjlTX3YQR065grzHMrkIZ3OWw" +
                                          "BIEsvTUYpWPOMyPekMhlH6z3B/UGt1RwUtnq8riB6CZfdSAdkM4OiBRnRMnh" +
                                          "y9xa65WXa8oLncCzu96K2OpJtNg0tTKBVxsIylaotjJUwcht2qpGsk/2yWGE" +
                                          "09kUtSucoYKtLNPgagsW0YaJKi2I7kavCcyE71gY0M6EiXzSkwTQXBhyVnnR" +
                                          "GqANWimbPtdTRyg5EXhaXI9dcdnYQi62UBqjRVnNtkrc8TfbVnUlV4RhP4tV" +
                                          "ss9DTdkKYB5O5v0atgqG/cGK74moXZ+jlqZ5FBomXNhDqWC96AN9SWmVMCyw" +
                                          "YJwIMx+KEdVbWrFSm8faEmewFGuUe+s1XEUbuKs0hgQsJQMbX1UIaphMGHhK" +
                                          "jOYje6tTjbnWxakpQeCwYVfFPuL5fJA0fdMZiZlgVmMPHtaaIJyvN9Fo3kXH" +
                                          "C9qvWJTaKkOSt4FcZM0our1g1rTBYi2xJWxCtzxjZCtu9OzVbBqudaFHOtJy" +
                                          "asBgO7DExrxfXhiTMt+XiKnJqF1C1FXJnFSYyqLd2FpLvNaUkAlhq/40m/cW" +
                                          "mYdFVjtgfby2pYO0Gi/bbirOppA0Zg0o2PQH0XhMEK1Zqng+EE7II8tKSE09" +
                                          "to+SYEnBM3xkCSPUZqqIoM7KAxJeV6JUDQYbkamY23HLN6rliOmVHUem/UlM" +
                                          "1etDCkd7jN2r9cWoQ3EOO6S7dE2cNTcCFqXDqgxBSEQBI18haxQqE5MuFi9E" +
                                          "U9O1SYOnZREbWVTLnjciHOypFqK1JJvOVrcnbagZ0uNNXYVtv+pXU0gtz/iF" +
                                          "Pg2VsVCeo7Xa3N0ynUxyty0GhJ1t7OAWm7boBgs8W78DZTqsbCKMRZbrCOzG" +
                                          "MlVfWPEcjsKtivNsOUyRFQeHsNpw6otsZndbaLuZqOU1kw5JBB8vMaTdrDeD" +
                                          "MYQ3IqNvR365adc6sUA252S/1lpBiqmtFuGWMzFzC+sVYkBv25K+tqluuWM1" +
                                          "0WanQw+dvoRVzH4wcucTbpOiTRbrpxIn41qvNQnrjNob05VBq7PS3Y4xbKKx" +
                                          "tSAlh2tNG5ENo52mVCFphOK3Pbra76wywR6DTYE0jDoW5ccra75uWsO6P+An" +
                                          "mLRsVqbWGmObahCuHZJpzJCltW4qM85JM7vbSLeVddRrIAI96k2WrQbqOH4o" +
                                          "CVPZ1GSehMnN2sE7dmc6FuhJw6+n/XqCIUl/Ng5EB3XHFXvQrrRF0vCQcdy3" +
                                          "YdZYVZSOFwk8yxGQMURHbINwpzNqPc0GcLeJRsQAFTNS9PooXbe7kGFjXbBI" +
                                          "0VGTwLoEguP4W96SH531vrfTyweKQ+ajJKVpNfIK5Hs4tUuuNWBYukOSg9CX" +
                                          "lDAs3XmUNd2NfiLLUspPIx+7Wv6xOIn85PtfeFFlP1XOTyLzjm2AMHS9N1va" +
                                          "VrNOoDoHML3x6qeuwyL9epwZ+c33f+3RyY+s3lWkBi7L2NClu/KeXJ7lPspm" +
                                          "v/4UnadR/pPhp79EvUH5mTOls0d5kssSw5d2evbS7MhdvhZGvjM5ypH4pScv" +
                                          "O6p1FU2NfO143Deelz5/8deev3CmdMvJ5FGO4bFTqZi7l65vS1Y+wGEm+q5w" +
                                          "5bvxccnJvAwQ6735LJ0Hzw8epCqL/3ntQ14OX5Uc68xlynDmSPvGB1Pvl95w" +
                                          "nBIgXMvSlELqF6aOXZygS7Kl5em5/3vu6fLn//LD9+/Oly1QcjgNb7o+guPy" +
                                          "17ZKP/7b7/zfjxdo9pQ8t3+c5DhutksYP3SMGfd9Kc3pSN73+4/9vd+UPnG2" +
                                          "tNcr3RIYmVZkcEsH6psTtSzYlgqonaorkr7vCEsP6dpBVlIdGnZxzh6AEZ++" +
                                          "usIWFOxO/V/8R099+cdefOo/FxmWO4xAkHzc16+QuT/R55uffunrv3/vY58t" +
                                          "lOIWWQp2GnX6ysPlNxouuahQ8HDPkTK8Kufr0YPc9WEOuxSWLl6epPvh85tI" +
                                          "CoxN5IbaD+0yXud3+a7zRbbr/C539fZ3nB+y7c5FBh92+PNvOe9o8UHNuyVb" +
                                          "fv7t+/v773j2Gc8rCEGORLxXiHjvOHNgJ3ulQh+962nikQu8zdIcPVwVLd96" +
                                          "wtsRYekskEr+annJ0ZBndngOs3APHeeVCMt1tFztDut2+WbD3T+6qwIqkysS" +
                                          "v9gRXwx2Zcr3CspPeM4rK9r7rlH3t3Lw");
    java.lang.String jlc$ClassType$jl5$1 =
      ("fFi6Vckp3TF2jeY/eZCSKULAO6+XuDnZe8fSpb7jCfC86UBd3nRDvuPqFH/k" +
       "GnV/Nwc/BSbl2AI7Sag5waGzt46Z/dANMHt3Xvha8JQPmC1/n5j9+9eo+0QO" +
       "fi4s3QeYbWuB4udbvF1eGzlm8+dvgM178sIHwVM/YLN+E9k8aRnAju45tCMS" +
       "+Jaiwy9eg/d/moN/AOw6T0F74ZXs+nbZdS1Nco5F8Q9vhiieOxDFc98/Ubz+" +
       "sgswuztNxYW66ZgucPzqNaTzr3Pwz4+kk//6zLEYfuUGxFAUYuDBD8SA30Qx" +
       "nDlu9S8PZYFc9zJQnxcowdBizSfBAm6nOr9xbQGf8OedJJcQMJui32/l4NeB" +
       "4FaF87iSWt2ydQ31WJj/9pUKs7j1cuVrMA+fvoqzX9zLPAiMN0fHTlyV2I1R" +
       "dPrjayjVV49j2B8WBf/p+jEsB1/JwZ/k4CUgWA2sFHZO+IRG/uH1hHhliv57" +
       "Dv6swJWD/5KD/3aaypvghL9+jbpvfJdSuWxNkoOv5eAvc/A/wSYKuPFiN3Tt" +
       "vQ0fgb3WiVubP228+Lu/9a1z79td3rj0Kkpxcfeg6+l+X/mjs5W7wwsfKfZE" +
       "R2vGO8AeIshbhqXzV78EXODa3TO5+7ra/OpjbS6GP1LmQ1U8d3J1Bary4r+6" +
       "5OLKlYVwUenZF/nPf+UD9WLBf25rBAZYjE4O7iVfuvw/vgv47CV3la8opovK" +
       "n3/up7/4xNeEh4pLqDuJ5GShyW4tVT/Q1L1CU88UhnX1Bf4BRcVu5aLyno//" +
       "9e/+xfNf/dLZ0m1gSZ7vHCVfA5vEsLR/tbvbJxFcmIC3NugFtpP37XqDBfSR" +
       "4MAEPnhUerR/DEtvvhru4pLSqW1mfvvZcoFHbbmRo+ZoHzu1d40872Ttya3D" +
       "K1GF94Kd3nchvCPeD4JPHpCTS+6G5beVTlZ6wNkTNM7zFycLrnNRwMc9vEV3" +
       "ChXzQOXepLDZ5Bqzl98bICRf3ZnNp75z51Nve+RLP1yYzeVCeoWCubrH93b0" +
       "nbytehBHbsBz7j2YF76cg2/lP8/l4IGb7zn3HrlG3WtfWTzZezgHr8nBo8Bp" +
       "rqRgRbhqoZjhDcvliRw8VuDK3x7PwfnvUi7Hp29jEOccKb9id10B/eA16p75" +
       "LgV0PPB+3u3pY1G9IQd5y7035iS5obFM88ov37CgyjkoThm/nL8VAyPfu6BO" +
       "0HuNwerXqGvesJBqOchPRPewsHTnTki4Zd0cOeWXTfeeO5JTfnq799bvg6F1" +
       "rlFHvUJDa+eAzEEXGFroHl9ARm5YLmwOBgWu/I3OAfP90p/JtZfCjx+Hj15+" +
       "QOZHXpifG5zYGOwJN6xmfA6mOViATUQsGeHN0bB35eBHjzTsHTm4eJM0bO9Y" +
       "L1rFYNpVG+zNigb6DSyH9/KQubfMweqYqRsWkHOpgNY5sG+mqp3YtrZyUGyl" +
       "9oLriSq6YZXKT/33ikC1vYnyes+l8soDxt67k7D0qit9dZOfpL/msg//dh+r" +
       "KZ998dwdj7w4/Y+7Y+nDD8rupEt3LCPLOvmhyIn32zxfWxoFk3fu0hPFtnfv" +
       "x8CO5HpnAWHpruMfOXN77911fj9Ye16xMzDF/N/Jtj8BNsen24alW4v/J9t9" +
       "EIx23C4/bCleTjb5UFg6C5rkr38n/5DlKou4B683USfyZ09ddecyjHbfZl5U" +
       "Pvdin3n3y/VP7b6EASvJLMuxgK3B7buUUIE0T688cVVsh7hu6z7z7ft++c6n" +
       "DzNy9+0IPraZE7S9/srJmo7thUV6JfvVR37luV988avF1xj/H/lbCEIyOwAA");
}
