package org.apache.batik.bridge.svg12;
public interface BindingListener extends java.util.EventListener {
    void bindingChanged(org.w3c.dom.Element bindableElement, org.w3c.dom.Element shadowTree);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028784000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Xa2wcVxW+u+t3HL+S2CEP57WJcJruKJQiFYfQ2LETh7Vj" +
                                          "xWml2m02d2fu7k48OzOZubNeO01VKqGG/oii4NKCqH+5KqC+hKgAQasgJNqq" +
                                          "gNQSAQW1ReIH5RHRCAl+BCjn3DuzMzu2wz9Wmrsz95573vc75z5/gzS6Duln" +
                                          "Js/weZu5mRGTT1LHZdqwQV33NMzl1KdS9O9nPpy4J0mapklHibrjKnXZqM4M" +
                                          "zZ0m23XT5dRUmTvBmIY7Jh3mMqdCuW6Z02ST7o6VbUNXdT5uaQwJ7qdOlnRT" +
                                          "zh0973E25jPgZHsWNFGEJsqR+PJglrSrlj0fkm+OkA9HVpCyHMpyOenKnqMV" +
                                          "qnhcN5Ss7vLBqkPusC1jvmhYPMOqPHPOuNt3wYns3StcsPvlzn/culLqEi7Y" +
                                          "QE3T4sI89xRzLaPCtCzpDGdHDFZ2z5NHSCpL1kWIOUlnA6EKCFVAaGBtSAXa" +
                                          "r2emVx62hDk84NRkq6gQJ7vqmdjUoWWfzaTQGTi0cN92sRms3VmzVlq5wsQn" +
                                          "71AWnzrT9Z0U6Zwmnbo5heqooAQHIdPgUFbOM8c9omlMmybdJgR7ijk6NfQF" +
                                          "P9I9rl40Kfcg/IFbcNKzmSNkhr6COIJtjqdyy6mZVxAJ5X81FgxaBFt7Q1ul" +
                                          "haM4Dwa26aCYU6CQd/6Whlnd1DjZEd9RszH9BSCArc1lxktWTVSDSWGC9MgU" +
                                          "MahZVKYg9cwikDZakIAOJ1vWZIq+tqk6S4sshxkZo5uUS0DVKhyBWzjZFCcT" +
                                          "nCBKW2JRisTnxsShyxfM42aSJEBnjakG6r8ONvXHNp1iBeYwOAdyY/v+7Fdp" +
                                          "76uXkoQA8aYYsaT53sM37z3Qf+0NSbN1FZqT+XNM5Tl1Od/x9rbhgXtSqEaL" +
                                          "bbk6Br/OcnHKJv2VwaoNCNNb44iLmWDx2qmfPvDot9lfkqRtjDSpluGVIY+6" +
                                          "Vats6wZzjjGTOZQzbYy0MlMbFutjpBnes7rJ5OzJQsFlfIw0GGKqyRLf4KIC" +
                                          "sEAXtcG7bhas4N2mvCTeqzYhpBkekoBnL5G/HThwclYpWWWmUJWaumkpk46F" +
                                          "9rsKIE4efFtS8pD1s4preQ6koGI5RYVCHpSYv5B3dK3IFLdSPPgpZQgSDxIK" +
                                          "kQdNymCm2f8HGVW0c8NcIgEh2BYHAAPOznHL0JiTUxe9oZGbL+beksmFB8L3" +
                                          "ECd3gtiMFJsRYjNSbEaIzcTEkkRCSNuI4mWwIVSzcOiBoH1g6qETZy/tTkGW" +
                                          "2XMN6OiqOIVbgw/YGFNTnPfPTdnP/OYXf7orSZIhNHRGMH2K8cFIOiLPHpF4" +
                                          "3aEepx3GgO69pye/8uSNx2eEEkCxZzWBaRyHIQ0BWwGjvvTG+Xc/eH/5erKm" +
                                          "eIoDHnt5KGuctNA8gBlVOSetNVSShm38GH4JeP6DD9qIEzLDeob9NN9Zy3Pb" +
                                          "jrgjId43c9IX2jBSgdwIfI3u2r4WYAiwW35scUk7+exBeax76g/hCNSYF371" +
                                          "759lnv79m6vEvZVb9p0GqzCjTicQWdctjAssDSpvTn2v4+offpAuDiVJQ5b0" +
                                          "gFM8amDdP+IUoaKosz7otuehhQgr+c5IJccWxLFUpkEhWaui+1xarApzcJ6T" +
                                          "jREOQZ+BiLp/7SofV/31x/685fTh0lmRZdG6jdIaoeTgzkmstrWquiPm/jjL" +
                                          "b40//+axferVpCg0CNqrFKj6TYPRQIBQh0FFNdEcnFkPQnfHT3LcWzl1/076" +
                                          "Su7Vi2kRhVaotpwCOkIh648LrysWg8HpQlEt4ISC5ZSpgUuBy9t4ybHmwhkB" +
                                          "Md0y2SFBxDk+Ck/ah1Pxj6u9No59EpIEfb8Yd+GQFtmVxNe9OOwTZJ+EbNsX" +
                                          "Jj/gvwH4iBFJ32dC2PWCTvMGw/Pwr869B1/56+UumcgGzAQhOvC/GYTznxgi" +
                                          "j7515p/9gk1Cxf4jBJmQTBa1DSHnI45D51GP6hff2f611+kzUB6hJLn6AhNV" +
                                          "JintC070BsTUubvUjGaVM9gtQu7i0lFh9rAgOyzGIXSfj474fQyHz3LSkZe4" +
                                          "O1yCfoVpoM3AbdpZRy8DLlb8hkC52PPB7Dc+fEGiQrx7iBGzS4tPfJy5vCgd" +
                                          "K1usPSu6nOge2WYJbbtEFBGndt1Oitgx+seXLv7wmxcfT/qWZjhpqFg6mpZe" +
                                          "w7RI05xTr1z/aP39H712Uyha33VHK8U4taVu3TgMom598Vp1nLoloPv0tYkH" +
                                          "u4xrt4DjNHBUoQa7Jx2ol9W6uuJTNzb/9sc/6T37dookR0mbYVFtlGJ/C10K" +
                                          "HBnmlqDUVu3P3yuPxVwLDF0irGRFoFdMYLbtWD2PR8o2F5m38P2+7x56bul9" +
                                          "UaPsKlgdK83IZPOKW4DsXNUXlzpb+pbu+7UAjFp32Q4QW/AMI4JHUWxqsh1W" +
                                          "0IU326VPbfH3INzkbts1cLh24r8wdEZugu65b41NUGvlS5Q+D7e6OD3wFf9R" +
                                          "OtjdFtIBK/kSJSlxkgISfNXBdYn6ngQ/JnHYJN+n1oxhpI3ZU5ey4ooWlAhP" +
                                          "XtJy6ktLJyYu3PzMs7KrgcvdwoJo6eGGInG3VmZ2rckt4NV0fOBWx8ute4PT" +
                                          "0y0VDsF2awREHoBCbmM6bIkhmJuuAdm7y4de+/mlpncg+WdIggJmzUQuSPI2" +
                                          "ADDoQT8wkw07gsgVX0Dr4MDX5w8fKPztdyIt/Q5i29r0OfX6cw/98urmZYDg" +
                                          "dWOkEVKYVafhtucenTdPMbXiTJP1ujtSFUnN4fo5Rlo8Uz/vsTG4WHZg5lK8" +
                                          "vAm/+O5cX5vFUsnJ7pX4tbLfgCM8x5whyzM1UXgBVMKZurtjUKk9245tCGdq" +
                                          "ody40vacevTLnT+60pMahdNXZ06UfbPr5WtdQPQ6KduCCNzK9jKVy47bdtBu" +
                                          "Jrv93nJe0uA8J4n9/iyCTUJ2ePj5sGB3Qbzi8Mh/AT7Dh20pEgAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028784000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05e8zrVn2+333flt7bFtqu0JaWW7QS+Jw4fiS6DEicOLGT" +
                                          "OE7svLyNW7/t+Bk/EsfQrXTaqIbE0FY2JkH/Am1D5aFpaJMmpk7TBgg0iQnt" +
                                          "JQ3QNGkPhkT/2ENjGzt2vtf9bm8r/lkk2yfHv/frnPPzS9+HzkchVAp8Z2s4" +
                                          "fryvpfH+0sH2422gRftMH+OkMNJU0pGiSABzN5Unvnj133/4MfPaHnRBhO6X" +
                                          "PM+PpdjyvWisRb6z1tQ+dPV4tu1obhRD1/pLaS3BSWw5cN+K4ht96K4TqDF0" +
                                          "vX8oAgxEgIEIcCEC3DiGAkhv0LzEJXMMyYujFfRz0Jk+dCFQcvFi6PFbiQRS" +
                                          "KLkHZLhCA0DhUv5/CpQqkNMQeuuR7judb1P44yX4hd94/7XfPQtdFaGrlsfn" +
                                          "4ihAiBgwEaG7Xc2VtTBqqKqmitC9nqapvBZakmNlhdwidF9kGZ4UJ6F2ZKR8" +
                                          "Mgm0sOB5bLm7lVy3MFFiPzxST7c0Rz38d153JAPo+sCxrjsNqXweKHjFAoKF" +
                                          "uqRohyjnbMtTY+ix0xhHOl7vAQCAetHVYtM/YnXOk8AEdN/Od47kGTAfh5Zn" +
                                          "ANDzfgK4xNDDdySa2zqQFFsytJsx9NBpOG73CkBdLgyRo8TQm06DFZSAlx4+" +
                                          "5aUT/vk+++6PfsDrenuFzKqmOLn8lwDSo6eQxpquhZqnaDvEu9/R/3XpgS8/" +
                                          "vwdBAPhNp4B3ML//wVfe985HX/7qDubNrwIzlJeaEt9UPi3f8823kE/Vz+Zi" +
                                          "XAr8yMqdf4vmRfhzB29upAHIvAeOKOYv9w9fvjz+s8Wzn9W+twddoaELiu8k" +
                                          "LoijexXfDSxHCzuap4VSrKk0dFnzVLJ4T0MXwbhvedpudqjrkRbT0DmnmLrg" +
                                          "F/+BiXRAIjfRRTC2PN0/HAdSbBbjNIAg6CK4oDPgehLa/R7LbzH0NGz6rgZL" +
                                          "iuRZng9zoZ/rH8GaF8vAtiYsg6i34chPQhCCsB8asATiwNQOXsihpRoaHK2N" +
                                          "CgI3QeCBgMpLQq7Sfh5pwf8DjzTX89rmzBnggrecLgAOyJ2u76haeFN5IWm2" +
                                          "X/n8za/vHSXEgYVi6F2A7f6O7X7Bdn/Hdr9gu3+KLXTmTMHtjTn7nbOBq2yQ" +
                                          "9ADg7qf4n2Wefv6JsyDKgs253NBpkYUPFX/OAryn7lyiqbw+0EVNVEDIPvRf" +
                                          "Q0d+7u//sxD5ZJXNCe69Slqcwhfhlz75MPme7xX4l0FBiiUQQCDXHz2dnLfk" +
                                          "U56lp00J6uwxXeSz7r/tPXHhT/egiyJ0TTko4lPJSTReA4X0ihUdVnZQ6G95" +
                                          "f2sR2mXcjYNkj6G3nJbrBNsbhxUzV/78SReCcQ6dj68U4XBPAXPvj8DvDLj+" +
                                          "N79yT+QTu9C/jzzIv7ceJWAQpGfOxNB5ZJ/YL+f4j+c+Pm3gXICf4oNP/fWf" +
                                          "/3N1D9o7ruJXT6yLwAg3TlSOnNjVokbcexwyQqjlxvq7T3C/9vHvf/ini3gB" +
                                          "EG97NYbX83suMVgGwXLyi19d/c13vv3pb+0dxdjZGCydiexYChhExaoGNNEt" +
                                          "T3IKgzwRQw8uHeX6odZTsMoBwa4vHaIw1ZvAul6Ilntlf7c0FHkFJLp+h3A9" +
                                          "sZzfVD72rR+8YfqDP3rltki91TADKbix81AhVQrIP3g6i7pSZAI49GX2Z645" +
                                          "L/8QUBQBRQVUh2gYgkxObzHjAfT5i3/7x3/ywNPfPAvtUdAVx5dUSspXXlA/" +
                                          "YxMs1iYoAmnw3vft6t/mErhdK3ITKvR/806cIq3vOTZE3wcr5Ef+4WPf+JW3" +
                                          "fQfIwUDn13kMAwlOWItN8k3DL7308UfueuG7Hyl8Aqrt9Nknv/dsTrVWMHiy" +
                                          "uP9kfivtPJYP35nf3pXf9g/d9HDuJr6ohn0pige+aoFNg1p46jVLBxdaLoi2" +
                                          "9cGKCD9z33fsT/7T53ar3ek6cQpYe/6FX/7R/kdf2Duxx3jbbcv8SZzdPqMQ" +
                                          "+g1Hrnz8tbgUGNQ/fuGZP/ztZz68k+q+W1fMNtgQfu4v/+cb+5/47tdepUif" +
                                          "c/zDoMzvyAHb/IG9vmPju+IuGtGNw1+/MpeQjTJNZ6WkFFe7/RKPkG0OI2aM" +
                                          "woRJjxlZ1EIfIf22YBLTZTpzHcQtIyqiJ4SN1obZUExkVhuWK9PeqtOBfctC" +
                                          "2R656paw3oosmT2jMZIig2FXK4Md8Y3RrDLW6C427o7JhlNqkkuv2kqyQZYg" +
                                          "m6w+c8Moq2MYUV0rBJZhsJHxeCtxPCaCN5qYYO64IwiVfldUV5vRtFplB5lT" +
                                          "6al8fVj3uGCLMmVXCmyna8nhsufNxdUAHWRi2UWqcwFTxxNXWDddekEwZtUd" +
                                          "rFQymeFiGeEFwsen8oSdqwKWSKMNQ6zUoeONhcws14lqG8GWnCF2oxlLddpM" +
                                          "tBqXOMZwQj50lmXddktDu1HvTgNy2x0E26Hm9bzVYLryTIXF+IhY95srm0si" +
                                          "srJcu+aCGwxXXJcbJmxc3Sy8qMrHSsStncyDlcTpr9oWsRi1qwJwU62ejrO+" +
                                          "xJExmQWtjtptUSKSYWyXJ4N+xZ7Rw4njNfB2j6SmDanTjPnGXAoRzZ2mOGK2" +
                                          "7BrKju0VbowYYr1y1eXEn830TBJGHcEqK2wdicZuVJ262dRZYZto5BGVxszL" +
                                          "QqEulie4uHE92cdMbeX7jVGXVjljQsnDQU2p+64zcLeyyhhjwlraOKuPKK5O" +
                                          "10MHLfd0xYBpSlbYXubyrG2GODmkmXi5Urdb3BWnaYPB5rUKZaRSk4qJUSVx" +
                                          "TGmAtjYSgkvkYoKTIxXGZ6bjqZXWUmyr9XGUdetNnmyESsVJ7XgmTPkWP+uQ" +
                                          "9YExGUimOO0tjLqyseyWKNl0Y8hU1jORXpXilY3zaBSZqS36WDLhy61pz9w2" +
                                          "Z9lSpEhF8Mhmb4YwYysSvDTizW2qD1BE4pl201tKdgcPa0N2Pe+yQcVqaovN" +
                                          "sKFuF/C6RFBqQODJ3PZHjZq0WESSgFWjQZXIqiO9VGZ5ma1Q4koozdkBJjiV" +
                                          "oQqn9VA2jXnMr9pSX5ZtvBnCQ8Xr9pg1Mt1IPkuyrIyiVt+dtVJk5ercuuXH" +
                                          "dUe3V+N42eIDJ+lM6UUJn0pxhG/EbLnsCENxlMmLbXngDGQqiZdB09MiImSw" +
                                          "YcaMIsrR6U250+mttuO+jvZoMmo35rHSIWRTilAWcdekoK2yhRk0bc32m14f" +
                                          "68BdwdwoziKYzWbuhJlJiWsHNopT9TDq0W1U06mYrwWtSoQGoTbCbb9DY+PF" +
                                          "lOwG/GKNNatqr0pTfZXnOCMQRwbfSumePVLZrUu6iF7rdqazslJjFdpom0hz" +
                                          "0W00uGHmdftlxhImqVb3xY7cL8maHblUs9avtkm1asTWgGKi8WIJTNuW6EwR" +
                                          "2rY9Jnk2oVF3tqGnfKYMrabfrRj4qi2IWzgW7M4MmQ9YfGithvRUNjbwokOx" +
                                          "gsfpnKB6HDxczHXCD3mRNtnuuDPoIr2aQtFDq891AwqtSm0tSKsdY4jXg60G" +
                                          "1xKeTRGt3bbJVMxmTWm87dKjcnO26SzXa6FTmiuw1oUxLey5Gu23ul6M9Trg" +
                                          "4Ms2akbTmQ7BNoed8rzpVmudLspoHN5q1Vd0O+u3NF+us2xd3FY5eRkaS1pF" +
                                          "q0qdniPLJm+oG1qnqwkSorNFw9rMqlikTGyipKVNTUoJ3IBNkuUXVJWoEFjd" +
                                          "8dZE3cXX7bU4letBubPKyKVgKaOZqsTLRhSBUFoLHrJGS+D8FDSSljVlRphc" +
                                          "NqhBTXJbKleiJ77U86OM8ONEM82REZYUjGYUZZb2qUlgt00QFVapkkphI8gU" +
                                          "BheW4/ZwJJaaVj+ACd7Xp3C1ksJ4DdMFs+y4Y1Ht4EuVlnxNMDLbjeJwtkos" +
                                          "zoWXy76MlmG4JKVg5w1KqFEm2VVI9Za4sODGI7o5MssUxaptxaNsbuTpXaHa" +
                                          "V2ag7MNlAucTYmoh9ticSn4cbMihTZs4WuuH22hm1LrByGnHKM2TmMgHxiRp" +
                                          "busxupW77sa0mwO1vEV4qpm27BJpw5JZ4dIlntRZH6u3A7qty7WFWuqMqBiU" +
                                          "U1arD4cbQWRKbZmN5swSNtabLmo1KaaKqCTCzUhhPehsYG4T1vB6swJjeGmS" +
                                          "uIrRyRojc7gm4c5CyLzUsJYEVsECuG7YFTLV0WWTcUdCU6q0+K5Ho1gLq3Q4" +
                                          "3NR1RMcrlZKdTZq4yfQ9vGGyU8byYrJMlJuRMEnk9WTZkaaDuhGPEsIqO5RZ" +
                                          "DxvGcJt16DmvL1EC1Ufbblbt87aoocPKltT9aeAPqg1ZDcTxttbqO3LNtEkM" +
                                          "4bgm0VJKertjjcKUsJqdjEdjTme22Jo01F4liTg+wb2hoSGzBSPLcZtqdsAG" +
                                          "qTK0YiMtRdq8vyY2bqroAryaiUszWFEG7gaitiHGdBlLhbCSwRJXrXeJCjLZ" +
                                          "mlK1Ou32ahM0lqZJVTAGvovVa9Og4vV9x+fW5XhhdxM0DWO0tWS7zYk/kggm" +
                                          "RXynPsOThBHYTIbrkQLjQpVQfd8el115MaVip8PAZKXc6zY911m1JoA6V90m" +
                                          "XDrd9FtU2Qo7Y8qn1MGiL8ezFsKNaz5CYSApOaREpBguJ059InFRzwF616q0" +
                                          "yA17M7QVzdnJ3MkCuRTISYmYNJZUUEVG6GgGNwY0ynQns3QVmZVZmZ5UEXzK" +
                                          "yXq3SrOZLcdRRembCBrWNmpbTIwEx2S0wk46a4fHRqUWoeHDVnVD6fXxMF6q" +
                                          "VEw3e7DNMzxY6gya19l5U114uGeMYMbrLhi25FX81AzoqjjBtC3q+zOnYXLz" +
                                          "mNnidtxntgugcTaIiF5oKGt14zM+rnU6tNcBS72IhIodo+y0rA+bs7SWxBrK" +
                                          "CeVtedqKKETajNtdv0nK7gCXadt0mSRpqC6xRVWtBLtO4ClGaabShsG42WSU" +
                                          "8ByNNFotfyTUNvamTBiRMZ2XWyE6aM2xTU3vcVmsbukYHmEWUg/LQ32OKxu4" +
                                          "XktCV1y0DHU2tNtg8Z5KuhkniuYJKjeQ55bAcJVkGfPUxGNR3cfGjl+bZPA6" +
                                          "EjrorCsamNOrrRsuXBpiyhxbU5PIY4hgjsZyXzfIQS3FNuY2G1Qmc6M5HfTE" +
                                          "JIyXk55dR1AsJjvqyle3aHktKdpa6HtCCS8HYBehsnOxjE90mQuxWayOuBHe" +
                                          "UxOSZLNefdmbblFCVuNmwoTretVjtHLSqDGoV4etLSlMGETjlljUaVZHcmbV" +
                                          "BibcEIiWiZSDttFo5Ntv+sc7Ad1bHFSPGprg4JO/KP8YO//0tRjG0CVJBnUY" +
                                          "HA9j6PJRh3XH/USn5szhwfjEAbW91rz4sA2Un3geuVMvszjtfPq5F15Uh5+p" +
                                          "5KednFgLMIz94F2OttacW1iF0DvufLIbFK3c4+7LV577l4eF95hPF+2H27pC" +
                                          "fehKjsnlHfOjzvhjp+Q8TfJ3Bi99rfN25Vf3oLNHvZjbmsy3It24tQNzJdTi" +
                                          "JPSEoz5MCD1x23HQVzQ1CbVjvu94q/Slm19+5voedO5kgyqn8Mipds9duh+6" +
                                          "kpMzOOxqXwFHe39zPHOy9wPMWjTfWuC6ftD2LJ752/uD/P7G9DimbguWvaPo" +
                                          "HB+ERgi9/TgSSN9xNKWw+vWJ5xandEl2tDw4/vvqk5Uv/etHr+3OsA6YOXTD" +
                                          "O1+fwPH8TzShZ7/+/v94tCBzRsm/Exw3Uo7Bds3n+48pN8JQ2uZypB/6i0d+" +
                                          "8yvSp85CZ2joXGRlWtEN3tvpdxje9+e9z01V2Vd9dz//xgNCPH9lFWqbBZhS" +
                                          "3I0iz3Ytzfx/0Zy/GUP3yLv+KGlKnqHtvjm890SOkuDsvvYt9Th5n369Y/tJ" +
                                          "VmkMXT3Vgc01fui2jz27DxTK51+8eunBFyd/VcTU0UeEy33okp44zsmm4Ynx" +
                                          "BbCl13cqX96FUVA81jH0yGs2h2PofPEsxE52SFtQNO6AFEMXdoOT8B+MoWun" +
                                          "4QHd4nkS7udj6MoxHCC1G5wEeS6GzgKQfPgLeUPzRJU5KIuFA+57PQccoZzs" +
                                          "SOaVqfgSd1hFkt23uJvKF15k2A+8gn9m1xFVHCnLii83fejiLm2PKtHjd6R2" +
                                          "SOtC96kf3vPFy08eVs17dgIf5+oJ2R579YRqu0FcpED2Bw/+3rt/68VvF125" +
                                          "/wMS3TDtIh0AAA==");
}
