package org.apache.batik.ext.awt.geom;
public interface ExtendedShape extends java.awt.Shape {
    org.apache.batik.ext.awt.geom.ExtendedPathIterator getExtendedPathIterator();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVXa4wbVxW+tvedfSfZTfPYJFsnah54KFCk4hCa3e42Dt6N" +
                                          "tZtU4KXrXI+v7cmOZyZ37ux6t4BKJUT4U0UhpQWp+2urClRKhaigUlulQqKt" +
                                          "CkgtEVBQCxJ/eEU0QoIf4XXOnRnPeHYN/MGSr8d3zj3v851zn71J2m1Oxpgh" +
                                          "UmLVYnZqyhA5ym1WmtSpbZ+DvYL6RIL+ZfF3s/fGSUee9FepPaNSm01rTC/Z" +
                                          "ebJPM2xBDZXZs4yV8ESOM5vxZSo008iTnZqdqVm6pmpixiwxJHiQ8iwZokJw" +
                                          "regIlvEYCLIvC5ooUhPlVPR1Okt6VdNaDch3hcgnQ2+QshbIsgUZzF6ky1Rx" +
                                          "hKYrWc0W6TonxyxTX63opkixukhd1O/xXHAme88mF4w/P/DX21eqg9IF26lh" +
                                          "mEKaZ88x29SXWSlLBoLdKZ3V7Evk8ySRJdtCxIIks75QBYQqINS3NqAC7fuY" +
                                          "4dQmTWmO8Dl1WCoqJMjBZiYW5bTmsclJnYFDl/Bsl4fB2gMNa10rN5n4+DHl" +
                                          "2hOLg99JkIE8GdCMeVRHBSUECMmDQ1mtyLh9qlRipTwZMiDY84xrVNfWvEgP" +
                                          "21rFoMKB8PtuwU3HYlzKDHwFcQTbuKMKkzfMK8uE8v61l3VaAVtHAltdC6dx" +
                                          "Hwzs0UAxXqaQd96RtiXNKAmyP3qiYWPyk0AARztrTFTNhqg2g8IGGXZTRKdG" +
                                          "RZmH1DMqQNpuQgJyQXa3ZIq+tqi6RCusgBkZocu5r4CqWzoCjwiyM0omOUGU" +
                                          "dkeiFIrPzdkTjz1snDbiJAY6l5iqo/7b4NBY5NAcKzPOoA7cg71Hs1+lIy9f" +
                                          "jhMCxDsjxC7N9z57677jY9dfd2n2bEFztniRqaKgbhT739o7eeTeBKrRZZm2" +
                                          "hsFvslxWWc57k65bgDAjDY74MuW/vD73w08/8k32xzjpyZAO1dSdGuTRkGrW" +
                                          "LE1n/AFmME4FK2VINzNKk/J9hnTCc1YzmLt7tly2mciQNl1udZjyP7ioDCzQ" +
                                          "RT3wrBll03+2qKjK57pFCOmEL4nBN0nczxgugiwqVbPGFKpSQzNMJcdNtN9W" +
                                          "AHGK4NuqUoSsX1Js0+GQgorJKwqFPKgy7wVWJl0RSoWZNWWqLkBTKJgqtVgK" +
                                          "88z6v0uoo43bV2IxcP/eaPHrUDenTb3EeEG95kxM3Xqu8KabWFgMnncEOQZC" +
                                          "U67QlBQqoRKEplBoqkkoicWkrB0o3A0zBGkJyh3wtvfI/ENnLlweT0B+WStt" +
                                          "6OK6rL89/h84GFFSVvrH562nfvGT3384TuIBKAyE0HyeiXQoEZHnsEy5oUCP" +
                                          "c5wxoHv3ydxXHr/5pQWpBFDcuZXAJK6TkICAqoBOX3z90ju/fm/jRryheEIA" +
                                          "EjtFaGiCdNEiwBhVhSDdDTxyDdvxL/jE4PtP/KKNuOHm1vCkl+AHGhluWSF3" +
                                          "xOTzLkH6pQ3ob+li9NK+Vggh0W3j0WvrpbNP3+3W8XBz1U1BU/nWz/7xo9ST" +
                                          "v3lji2B3C9P6gM6Wmd6kCohsGg9mJHj6rbagvtt/9bcvJisTcdKWJcPgC4fq" +
                                          "2OhP8Qq0EHXJQ9neIswMQes+EGrdOHNwU2Ul6BytWrjHpctcZhz3BdkR4uAP" +
                                          "FgihR1u39ajqrz36h93nTlYvyOQKN2qU1g49Bk/msL022uj+iPujLL8x8+wb" +
                                          "DxxWr8ZlZ0GU3qIjNR9KhwMBQjmDFmqgObjTB0LHo+Ub9VZBPXqAvlB4+XNJ" +
                                          "GYVuaK+CAhxC5xqLCm/qDmm/qFBUFzihbPIa1fGV7/IeUeXmSrAjcWXIzXFI" +
                                          "kDswpT8I33EPP+Uvvh2xcB11cUjSj8n1IC5JmV1xfDyEy2FJdhdk2+GgbgHw" +
                                          "dYBEjEjyvAFh18oaLeoMEeXvA4fufuFPjw26iazDjh+i4/+dQbB/xwR55M3F" +
                                          "v41JNjEVB44AWwIyt4ttDzif4pyuoh71L7y972uv0aegH0IPsrU1JtsK8XAN" +
                                          "lZqUZp+U60Tk3RQuHxNktMKED6c5aFAZwST++Ejwof8NiZuOcpJsUQuhabOg" +
                                          "Xrnxft+D779yS7qgeVwNA+0MtdJu7HFJIxaNRqH+NLWrQPeR67OfGdSv3waO" +
                                          "eeCoQvuyz3JoNvUmWPao2zt/+eoPRi68lSDxadKjm7Q0TXEwhPYOqcfsKvSp" +
                                          "uvWJ+9z0WumCZVD6j2zy6KYNjNr+rfNhqmYJGcG1749+98Qz6+9JiLfqgvQ1" +
                                          "9TVksWvT8OwOfOpz6wNdo+vnfy7LrjGU9QJQlR1dD1V1uMI7LM7KmvRlr+tR" +
                                          "S/6chwvQfwyzIG34I6085575FExerc4IkoA1TL0AsLkVNVDCGqZchDtTlFKQ" +
                                          "dvkbpqOC9AR00BrdhzAJzOQJIMFHBv6NNfd9/JPBZaf7nG0Z6NCocGdTXssL" +
                                          "kI/HjnsFKqjfXj8z+/Ctjz7tTg5wdVpbkwMzzP8uyDUw/WBLbj6vjtNHbvc/" +
                                          "330o7lXtkKtwgGx7QiU9B13TwqzZHYELO9lAjXc2Trzy48sdb0OFLJAYOHH7" +
                                          "Quj64c7agDkONN+FbNB+QxdoiWPpI19fPXm8/Odfydz12vXe1vQF9cYzD/30" +
                                          "6q4NwLttGdIOEwOr5+EuZd+/aswxdZnnSZ9mT9VBReACl7sM6XIM7ZLDMnBt" +
                                          "68cEp3g1kn7x3NnX2MW+JMj4pjvQFs0d6nyF8QnTMUqyywHyBDtNNzO/LTqW" +
                                          "FTkQ7DRCuWOz7QX1/i8PvHRlODENRdpkTph9p+0UGy03fFlzezCug7JD1d0R" +
                                          "LlHIzliWP9KRsje/OS4N7gsSO+rtIiLF3HEK/9YluxX5iMvavwE+eNXlhxEA" +
                                          "AA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5eczjWH2eb+7ZY2YX2F0WdmGXAXUxfI7jJE40QMnlxLHj" +
                                          "OIlzuS2zju34iK/Yz0cM29LtASoSXbW7LZVg/wK1RcuhqqiVKqqtqhYQqBIV" +
                                          "6iUVUFWpB0Vi/+ihblv67HzXfLOzW/5opDy/PP/u6733ywvfR84HPoJ6rrXV" +
                                          "LBfsqwnYN63yPth6arDfY8u85Aeq0rSkIBDg2k358S9e/beXn9Gv7SEXROR1" +
                                          "kuO4QAKG6wQjNXCtSFVY5OrxattS7QAg11hTiiQsBIaFsUYAbrDIXSdQAXKd" +
                                          "PRQBgyJgUAQsFwGrH0NBpHtUJ7SbGYbkgGCD/DRyhkUueHImHkAeu5WIJ/mS" +
                                          "fUCGzzWAFC5lv6dQqRw58ZG3Hum+0/k2hZ9DsWd//QPXfucsclVErhrOOBNH" +
                                          "hkIAyERE7rZVe6n6QV1RVEVE7nNUVRmrviFZRprLLSL3B4bmSCD01SMjZYuh" +
                                          "p/o5z2PL3S1nuvmhDFz/SL2VoVrK4a/zK0vSoK4PHOu605DK1qGCVwwomL+S" +
                                          "ZPUQ5dzacBSAvOU0xpGO1xkIAFEv2irQ3SNW5xwJLiD373xnSY6GjYFvOBoE" +
                                          "Pe+GkAtAHr4j0czWniSvJU29CZCHTsPxu1cQ6nJuiAwFIG84DZZTgl56+JSX" +
                                          "Tvjn+9x7Pv5Bp+vs5TIrqmxl8l+CSI+eQhqpK9VXHVndId79TvbXpAe+/NE9" +
                                          "BIHAbzgFvIP5vQ+99P53PfriV3cwb3oFmMHSVGVwU/708t5vvrn5RO1sJsYl" +
                                          "zw2MzPm3aJ6HP3/w5kbiwcx74Ihi9nL/8OWLoz9dfPiz6vf2kCs0ckF2rdCG" +
                                          "cXSf7NqeYal+R3VUXwKqQiOXVUdp5u9p5CKcs4aj7lYHq1WgAho5Z+VLF9z8" +
                                          "NzTRCpLITHQRzg1n5R7OPQno+TzxEAS5CL/IGfi9juw+j2YDQD6A6a6tYpIs" +
                                          "OYbjYrzvZvoHmOqAJbStji1h1K+xwA19GIKY62uYBONAVw9eZJkpxQDTVNfG" +
                                          "2gmAksKE0SVP3c/izPt/55BkOl6Lz5yB5n/z6eS3YN50XUtR/Zvys2Gj/dLn" +
                                          "b3597ygZDqwDEBQy3d8x3c+Z5oUTMt3PmO7fwhQ5cybn9fqM+c7N0ElrmO6w" +
                                          "EN79xPinek9+9PGzML68+Fxm4iTPv4fyH2ch3hN3Ls5UVhnovBrKMFgf+s+B" +
                                          "tXz67/4jF/hkfc0I7r1CQpzCF7EXPvlw833fy/Evw1IEJBg6MMsfPZ2Wt2RS" +
                                          "lp+nDQkr7DHd4mftf917/MKf7CEXReSafFC+p5IVqmMVltArRnBY02GJv+X9" +
                                          "reVnl2s3DtIcIG8+LdcJtjcOa2Wm/PmTDoTzDDqbX8mD4d4c5r4fws8Z+P2f" +
                                          "7Jt5IlvYBf39zYPMe+tR6nlecuYMQM4X98n9Qob/WObj0wbOBHjv2PvUX/3Z" +
                                          "PxF7yN5x/b56YkeERrhxomZkxK7m1eG+45ARfDUz1t9+gv/V577/kZ/I4wVC" +
                                          "vO2VGF7PxkxiuAHCjeQXvrr56+98+9Pf2juKsbMAbprh0jJkOAny/QxqsjIc" +
                                          "ycoN8jhAHjQt+fqh1lO4v0HBrpsWmZvqDXBHz0XLvLK/2xTyrIISXb9DuJ7Y" +
                                          "yG/Kz3zrB/dMf/CHL90Wqbcapi95N3YeyqVKIPkHT2dRVwp0CFd6kfvJa9aL" +
                                          "L0OKIqQow8oQDHyYx8ktZjyAPn/xb/7ojx948ptnkT0KuWK5kkJJ2Z4LKyfQ" +
                                          "4TatwxKQeD/+/l3liy/B4Vqem0iu/5t24uRpfe+xIVgX7o0f+/tnvvHLb/sO" +
                                          "lKOHnI+yGIYSnLAWF2bHhV984blH7nr2ux/LfQLr7PTnX374/RnVas7g7fn4" +
                                          "Y9mA7jyWTd+VDe/Ohv1DNz2cuWmcV0JWCkDfVQx4XFByT71q6eB9w4bRFh3s" +
                                          "hdhT939n/cl//NxunztdJ04Bqx999pd+uP/xZ/dOnC7edtsGfxJnd8LIhb7n" +
                                          "yJWPvRqXHIP6hy889Qe/9dRHdlLdf+te2YZHwc/9xX9/Y/8T3/3aK5Toc5Z7" +
                                          "GJTZWDxgmz3Kr+1YcNelbimg64cfdjqXSvFymsxQAE9qq/FKFFb8okcFjqSX" +
                                          "SwzVXJf0pkSopWILVDgggkmJmftzGo1I2R6IW5Egw6QCSg2mNxFKk8JE94Yz" +
                                          "Dy2GftMaMbpkaBMrtIYbBjTXGmhPG8Nm0sPU9qQwdOlVaT4fOCOHV7sLDut3" +
                                          "xn5VIVKTiKplPHVIvFe08UHiafrEZqcLR9xs9Xp5a+MzG4y9pYi2ogVbGdEs" +
                                          "Kq4oIsBWnfFEVWuU6vESN7YLuC80MVFd9vh+MWm0xLkYlLbTans86JejRBy7" +
                                          "hULVECBZZTO1Kx6sCYkRJ72uMawaseiue7GvarQVtRdNlo6aZded6Lw15Uf4" +
                                          "YA0qU4WTWrJO6LLmDIvoMNCXdKBNxJSqrLf4KNGZhT+TC7OK4DrJNhHmFcL1" +
                                          "1kYSrnUFH2DJvFu31WrVpkoxxmOteRFXN1qNpooVS7fbjCRWq0mxNp7Pxhbb" +
                                          "cFmFEYkp2Y7W1e141FNAM6HpdUCWh43FcENzY4Lb1JvkKlyUlKEtzOxBtWXh" +
                                          "s6a76fXNhmgsZuWlYAey1XMWVMvCGoFVWjWKWp+T8ILPlZ0S2upaRX3AarVa" +
                                          "b023qx2l2Veno25jPGk3+3ZriNtgy+q1jTUyPCEW+0ZrUS0l/pRbzaK2xhdx" +
                                          "n3L7TKPKgzCeEN2FlTKtbkzJQ2EZMn1mna76TDVsV6MKbhFTqT4F3boFlGZF" +
                                          "SbpxGhQm9WS+kYZKrTICxpxj6vaWJzZQcn67LtTroxT4AiVw+kYralW605mL" +
                                          "wohROiPR7uKt/mbIeeFQ622Hc4kQ6Q0KNkZl1AwDrbEWXTks+6XmZpa6TTM2" +
                                          "tv2Caw8mnYmyVg2K9vlUWQtmigdOa2n06ouKVTY2LkYuS1xjUebqMpPyA7dO" +
                                          "yhqJdwMctehtbWXq/WbSCsykSXK1tExWSNJc1JSVUnSKyzaVAscYbSRGW+oC" +
                                          "SdRcUlUFtcH4I1G0i3pARYGVzGZymVxXykutVTdbC7LUD2dY1CKJuFDFqmui" +
                                          "mKSmtxXrA1wZK51QGK07/oxt4w5Wp+x+u0QxxSnNpRyzxno13RGaMr5IbRaQ" +
                                          "wNoWbdkYchYeKqK55UnDbTXT4UggYr9hWQUCLW4YkymTHtUc2G225DS4giOn" +
                                          "iRZqRryZLvkOxXjjYcr1e7LCAa42q3c7TIkLNxN3HMzxXlBAO0PN9XtMvKF4" +
                                          "RtuS8XTWswqjsTsTudlsw64bAtPTNmCqMdVqWokKoeuWiOW0SCcyj6kS3/Un" +
                                          "LdURlkRbbXdq5XXSJ+absMpIyxml9R1Hbg+GYnNSIYdWY7hxR0zbsxruZr12" +
                                          "DXm29hsFl6gX0kZn3dvqRAyiFY21OYe1YlUoNNDZGIDKgKn4bLWG6dVSh6LG" +
                                          "08jvlitFZxV1BIKoloSQbjD1bbvQ3arGfOi2xa4TtLdld9Lk5XKcuN2I2Cow" +
                                          "VX2snNW1BtWSQ3Fe7zEVYU036xu3MZgTaa1ghtjKxsyRv9XVNl1vm4CSOkZT" +
                                          "4dpG3NCn+riltIRk21KihMXMdokHPMYwXDjo2njUXFsotK5uhbMxRSQDIWXX" +
                                          "3Yo3JNwlahk1jkGnmqYXZoRZmEW+t+R4AiVm1XkjxSd4Y4I5sxQjE7c2FiLC" +
                                          "Mo1ig2jW+IrWr8xspbJuunrQ0Wp2r2tW/KWkRQBgtaUc9YxAkBVm1pN5rVla" +
                                          "bYoDna8ON4V2d94b1uDVKoj7QzVA2x1fGXS5eFKcWJXGFsx8s+vJQBb1lGgo" +
                                          "61EprPOUZugjPCRqkrnxU6Ki1whHsBbRdjBkuOJmgmulWmON2QFbKBZDEzX4" +
                                          "0GTZalJF42UrSWZ+VbTEQmdCbGiTG9UYPe43hqbdouyNBg/HQqPAdl10sqxN" +
                                          "xQY/39Qjq1FC51yvs5iGEoM263rSLCcbtmljm5YNB6oxoVJDX/K0hK86UxKj" +
                                          "1Yk6t8d+3ZRnczqdU/S6FcSeUKUJos3z6CSK9GIiN3Bcnphjs+rgdLPcs6d4" +
                                          "smpt29si1VN0ZV1EO9pS68bKotE22+Y2qlM6XnUlVnX7bXUe1UurcBVSvBkX" +
                                          "K4aUtkwdNUoYqgyXDSyJR+Vyn6CiEt7jTLgTlkr1WUxvQQmAVmqsSt42dHUS" +
                                          "Z8ltjSyGUUFStW6B5gN/gvdAwFTndc4SNxPRQyeVgrAmRsOwm3Br0GfarYpc" +
                                          "lqi6GI8FFG2bsbuqcoYYDmSvF0yGoS4tB9rcd5IVQFskWduOyY2mTmOujhb6" +
                                          "QOmFZJfq0YnEjTZdlGNn/pBXRxVysOoo44iIpYGqNt1hFG5Toudy0cSe8ZJb" +
                                          "TAGGqi4/MipVa9xKJIUxbXJYEObtWOcXg428Cpho7IXRrIfW0sIstJvitFUx" +
                                          "i+m2wiw4k/NRfwXLub3odeQOTpZqaK06TCtorWewq40WDfGaMF0Hs0ioDuLB" +
                                          "auCllZhTXDRyVluS9c3OpDbsDa0RrrTwKR72aZLtk4wdjSwfBaMxVpH1OBqu" +
                                          "4m1Kd4gSXSlUy2WyTLUT1ZdL9Nqt4wJbqAfsespNW83ORpT1FhAsihkq0Xrp" +
                                          "bQbNWn1UKDR8RU/rvXQw7NF9qtuIKhy3UmpYj2+I0op0OgWxwjVduaMI8wBS" +
                                          "o7Gu6QQUszFXc7OaolgTmCkJBK0cK1NvuY77acpXw21rEmOzBrs0K5EJuO4y" +
                                          "kjGCKLikNQdrBsRaJyGHxqTWwAkh3qRid9FmBzWrbs7louCn21I1UJaFAcXC" +
                                          "DWvQ7ZLD0KyUZFLSWusBx6HUkmugw0RxjRnv0Xhtxc/tKjZQVlslxYvRXMWj" +
                                          "IVWTF2kLIwqVTYmLWQA6Cj1oxwO/jLZDUUExKYgTRXScsVizhdq0MVLrTXgC" +
                                          "71fmdJ8U2VbfaYBKVW57hIavHTIhOGde7M9QeOYoeSZkEBSUirOlqkNH6E82" +
                                          "223c3TZagOPSAcYKmxklrIdkC+7Ss0FKDuc4ZlT5qDuyBq02N1K8teDpNQ8t" +
                                          "TDrbArGirFRNm6FG9lq4UhixVpdOLahdjRkFpooNxiWO1ILxAPUBbbAU0W0z" +
                                          "WG1hhcm8bPQjKYrbqMrNLT1pw4Pve9+bHYnpH+1Wcl9+eTxqL8LLSPai8COc" +
                                          "xpNXYwiQS9IyAD68sgHk8lG/c8f9RPfkzOFldXdHy9ozeUcmu3w8cqeGYn7x" +
                                          "+PTTzz6vDD6DZxePjEYL8gGu925LjVTrFg4+8s47X7L6eT/1uBHylaf/+WHh" +
                                          "ffqTeSfgtgYNi1zJMPmsbX3Unn7LKTlPk/zt/gtf67xD/pU95OxRW+S2Tu+t" +
                                          "SDdubYZc8VUQ+o5w1BLxkcdvu5m5sqqEvnrM951vlb5088tPXd9Dzp3sFWUU" +
                                          "HjnVeblr5fq2ZGUMDlvLV+At242PV062YaBZ35gFQQF+Hz/oPebP7O3rvGx8" +
                                          "fXIcSrfFyN5RUI4OIsJH3nHcAWi6lqXKudWvTxw7vzBLS0vNunH/dfXt+Jf+" +
                                          "5ePXdtdJC64cuuFdr03geP2NDeTDX//Avz+akzkjZ836457GMdiuA/y6Y8p1" +
                                          "35e2mRzJz/75I7/xFelTZ5EzNHIuMFI1b8kiBw3CTCg9V1vOR+3UOzMbbgLk" +
                                          "QU0Fh61IXgI6DdS8IXSYFsX/WxfzNtQ8e598rbv0SakSgNxzS1M00/yh2/55" +
                                          "2f1bIH/++auXHnx+8pd5bB119C+zyKVVaFkn+3gn5hc8X10Zuf6Xd+Hk5Y8A" +
                                          "II+8qp4AOZc9cpn9HU4EkIfuhAOQs3A8Cb0FyOtfCRpCwvEk5IcAcu00JEDO" +
                                          "58+TcD8DkCvHcAC5sJucBHkaUocg2fTnslbkiaJ0UDxzL93/Wl46QjnZS8xU" +
                                          "zf89Oyw64e7/s5vyF57vcR98qfKZXS9TtqQ0zf9tYZGLuyw/KlyP3ZHaIa0L" +
                                          "3SdevveLl99+WGTv3Ql8nNonZHvLK+df2/ZAnjHp7z/4u+/5zee/nffT/hex" +
                                          "d2LP1hwAAA==");
}
