package org.apache.batik.dom.svg12;
public interface SVGGlobal extends org.apache.batik.dom.svg12.Global {
    void startMouseCapture(org.w3c.dom.events.EventTarget target, boolean sendAll,
                           boolean autoRelease);
    void stopMouseCapture();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVYe2wcRxmfu/M7fid2Uid2EucS4TTcKilFKg6hsWvHF872" +
                                          "YcepuJBc5nbn7tbe293szp7PbgOhEqpBIgrBpQVR/+WqD/Ul1KogaBWERFu1" +
                                          "ILVElILaIoFEeUQ0QoI/ApRvZvZu99Z2KoGwdHN7s9988833+P2+8ZPXUK1t" +
                                          "oT6i0xhdMIkdG9FpEls2UYY1bNsnYC4tPxjBfzvz/sQdYVSXQq15bI/L2Caj" +
                                          "KtEUO4V6Vd2mWJeJPUGIwlYkLWITq4ipaugp1KXa8YKpqbJKxw2FMIGT2Eqg" +
                                          "DkyppWYcSuKuAop6E2CJxC2RjgZfDyZQs2yYC574Np/4sO8Nkyx4e9kUtSdm" +
                                          "cRFLDlU1KaHadLBkoVtNQ1vIaQaNkRKNzWq3uy44nrh9jQv6n237+41L+Xbu" +
                                          "gs1Y1w3Kj2dPEdvQikRJoDZvdkQjBfsc+iKKJNAmnzBF0UR5Uwk2lWDT8mk9" +
                                          "KbC+hehOYdjgx6FlTXWmzAyiaHe1EhNbuOCqSXKbQUMDdc/OF8Npd1VOK065" +
                                          "5ogP3CotP3im/XsR1JZCbao+zcyRwQgKm6TAoaSQIZZ9VFGIkkIdOgR7mlgq" +
                                          "1tRFN9KdtprTMXUg/GW3sEnHJBbf0/MVxBHOZjkyNazK8bI8odxftVkN5+Cs" +
                                          "3d5ZxQlH2TwcsEkFw6wshrxzl9TMqbpC0c7gisoZo58FAVhaXyA0b1S2qtEx" +
                                          "TKBOkSIa1nPSNKSengPRWgMS0KKoZ0OlzNcmludwjqRZRgbkkuIVSDVyR7Al" +
                                          "FHUFxbgmiFJPIEq++FybOHzxHn1MD6MQ2KwQWWP2b4JFfYFFUyRLLAJ1IBY2" +
                                          "7098C3e/uBRGCIS7AsJC5oV7r995oO/KK0Jm+zoyk5lZItO0vJppfWPH8MAd" +
                                          "EWZGg2nYKgt+1cl5lSXdN4MlExCmu6KRvYyVX16Z+unnLzxB/hxGTXFUJxua" +
                                          "U4A86pCNgqlqxDpGdGJhSpQ4aiS6Mszfx1E9PCdUnYjZyWzWJjSOajQ+VWfw" +
                                          "3+CiLKhgLmqCZ1XPGuVnE9M8fy6ZCKF6+KAQfGaR+OtlA0V3S3mjQCQsY13V" +
                                          "DSlpGez8tgSIkwHf5qUMZP2cZBuOBSkoGVZOwpAHeeK+UIyCZBdzBw9J0yeP" +
                                          "HdOMDNZiLMHM/5/qEjvV5vlQCBy+I1juGlTKmKEpxErLy87QyPWn06+JVGLp" +
                                          "7/oDAAp2i4ndYny3GOwW47vFKruhUIhvsoXtKiIK8ZiDygZobR6YPn387FJ/" +
                                          "BFLJnK9h3izxUtte/gELA9bxov70tPnwr37+x9vCKOzVf5sPuKcJHfTlHNPZ" +
                                          "ybOrw7PjhEUIyL3zUPKbD1y7/xQ3AiT2rLdhlI3DkGsAoABEX3nl3Nvvvbt6" +
                                          "NVwxPEIBdJ0McBdFDTgDiIVlSlFjBXrEwbZ8CH8h+PybfdgZ2YRIo85hN5d3" +
                                          "VZLZNH3uCPHnbQDqN3G88DpzXO9G+MCxbfW+5RVl8pGDooo7q2tuBCjlqV/+" +
                                          "6/XYQ799dZ3AN1LD/LhGikTzWRdmW1Y1B+McOstEm5bfab38ux9Ec0NhVJNA" +
                                          "neAeB2uM5o9aOSAQec7F2OYMdAwece/yETfrOCxDJgrwxkYE7mppMIrEYvMU" +
                                          "bfFpKLcVDED3b0zqQdNfvu9PPSeO5M/yfPPTNNutFhiGrUwycq2Q6M6A+4Mq" +
                                          "Hx9/8tVj++TLYc4rDKPX4aPqRYP+QMCmFgEC1dlx2EwLbNofLOWgt9Ly/l34" +
                                          "+fSL56M8Co1ArhQDGAJv9QU3r+KGwXKdsa0awAlZwypgjb0qu7yJ5i1j3pvh" +
                                          "GNMh0h4ShFe0BJ+ki56TbGBvu002bhWYxOX7+LibDVGRXexxLxv2cbGPQbbt" +
                                          "80oZ4F4DXGQRic7oEHY1q+KMRhjI/LNt78Hn/3KxXSSyBjPlEB34aAXe/C1D" +
                                          "6MJrZ/7Rx9WEZNZueHDjiQkO2+xpPmpZeIHZUfrym73ffhk/DGwIDGSri4ST" +
                                          "SkTAR7m2+1htz98m85KGEoOeLjbCvk5gK0co6O73ioxl87QDYJO01AIAXdGl" +
                                          "8UPJs/JSNPl7Udy3rLNAyHU9Jn395Fuzr/O0bmB1V0kmX1VBffoC2s7dzwBm" +
                                          "4CZNcbU90vnO9+a++/5Twp5gDxIQJkvLX/swdnFZxEs0anvW9Er+NaJZC1i3" +
                                          "+2a78BWjf3jm/A8fO38/s4oti1FUnzEMjWBR10MMc13kBR6q9qKw9a6vtv3o" +
                                          "UmdkFIopjhocXT3nkLhSXab1tpPxudXr7UTR+qxmVEBRaL9p8tkxPg5zW45U" +
                                          "LEIuNbLfM2z4FIUio9iCK5Njk2HoGlhXzd7EXWewr3GKaoqGqsBJohvEzXev" +
                                          "SMuXrn7QcvKDl67zKFRfTPw8O45N4fgONgwyx28NMv0YtvMg94krE19o167c" +
                                          "AI0p0ChDv2JPWtBklKpY2ZWurf/1j3/SffaNCAqPoibNwMooZlcAaOQAZoid" +
                                          "h/6kZH7mTgEl8w0wtHO/oDWeWjPBKnTn+rU/UjApr9bF72997vCjK+9yhhcs" +
                                          "fKgayrbDZ8aFspn/Cco2DrB6k3ecL6E22m2gY3/s2fzdfEmKDW7ncfq/9BWb" +
                                          "kM0SsH6lp2P+27bmjijuNfLTK20NW1dm3uL8Url7NAO+ZB1N89WFv0bqTItk" +
                                          "VX6sZpFOogQg23o2bnYoquXf3GhLrCgC36+3gqIIjH7JBXBdUBI08m+/3L0U" +
                                          "NXly0OaJB7/Il0A7iLDHC1C8oeoethKJro+KhK/t3VNVpPzeXkYfR9zc0/Iz" +
                                          "K8cn7rn+yUdEFww3/sVFfs8DzBHsXGlGdm+orayrbmzgRuuzjXvLYNghDPby" +
                                          "eLsv9WSARJNlQU+A5+xohe7eXj380s+W6t6Ecj+FQpiizad8t2ZxRQSydKBr" +
                                          "PJVYi63QynECHhz4zsKRA9m//oYXoovFOzaWT8tXHz39i8vbVoGoN8VRLeA8" +
                                          "KaVQk2rftaBPEblopVCLao+UwETQomKtCrhbWcJidqPnfnHd2VKZZQ0VRf1r" +
                                          "6WhtVwqgNU+sIcPRFRf6N3kzVf9QKPdzjmkGFngzPgb+nIB1cWmIpBPjplm+" +
                                          "RNRdNHnBTgUJjE/y1d/gj2y4/B8KbP/70xMAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5eczkVn3eb88sIbsJkKQhCSQsqMHwecaew9ZyjT32jMce" +
                                          "j+fyzJiWjW97xtf4mPEMBFEEJSpSSmloqQT5C9QWhUNVUStVVKmqFhCoEhXq" +
                                          "JRVQVakHRSJ/9FDTlj57vmu/3U2Eqo7kZ897v/t6fj8//yPofBxBcBi4G8sN" +
                                          "kn0jS/bnbnU/2YRGvN/hq6ISxYZOuUocj8DcDe3xr1z5t5c+YV/dgy7I0GsU" +
                                          "3w8SJXECPx4YceCuDJ2HrhzP0q7hxQl0lZ8rKwVJE8dFeCdOrvPQq06gJtA1" +
                                          "/lAEBIiAABGQQgSkcQwFkF5t+KlH5RiKn8RL6IPQGR66EGq5eAn02M1EQiVS" +
                                          "vAMyYqEBoHAp/y8BpQrkLILeeKT7TudbFP4UjDz76++7+jtnoSsydMXxh7k4" +
                                          "GhAiAUxk6G7P8FQjihu6bugydK9vGPrQiBzFdbaF3DJ0X+xYvpKkkXFkpHwy" +
                                          "DY2o4Hlsubu1XLco1ZIgOlLPdAxXP/x33nQVC+h6/7GuOw2ZfB4oeNkBgkWm" +
                                          "ohmHKOcWjq8n0BtOYxzpeI0DAAD1omckdnDE6pyvgAnovp3vXMW3kGESOb4F" +
                                          "QM8HKeCSQA/dkWhu61DRFopl3EigB0/DibslAHVXYYgcJYFedxqsoAS89NAp" +
                                          "L53wz4+Edzzzfr/t7xUy64bm5vJfAkiPnkIaGKYRGb5m7BDvfiv/a8r9X3t6" +
                                          "D4IA8OtOAe9gfu8DL77nbY++8I0dzOtvA9NT54aW3NA+p97znYepJ4izuRiX" +
                                          "wiB2cuffpHkR/uLByvUsBJl3/xHFfHH/cPGFwZ/OPvQF44d70GUWuqAFbuqB" +
                                          "OLpXC7zQcY2oZfhGpCSGzkJ3Gb5OFessdBE8845v7GZ7phkbCQudc4upC0Hx" +
                                          "H5jIBCRyE10Ez45vBofPoZLYxXMWQhB0EVzQGXDNod3vkXxIoAliB56BKJri" +
                                          "O36AiFGQ6x8jhp+owLY2ooKoXyBxkEYgBJEgshAFxIFtHCzogYfEK6uMIkOp" +
                                          "1XIDVXH38wAL//9IZ7lWV9dnzgCDP3w63V2QKe3A1Y3ohvZsStIvfunGt/aO" +
                                          "wv/AHqBAAW77O277Bbd9wG2/4LZ/xA06c6Zg8tqc686jwB8LkNmg5t39xPDn" +
                                          "O08+/fhZEErh+lxuzaxItQeLP2cB3hN3rsNMXgTYovBpIC4f/M+eq3747/6j" +
                                          "kPRkKc0J7t0m9k/hy8jzn3mIetcPC/y7QNVJFBAlIKEfPZ2BNyVNnoqnLQiK" +
                                          "6TFd9Avev+49fuFP9qCLMnRVO6jUkuKmxtAA1fKyEx+Wb1DNb1q/udLs0ur6" +
                                          "QUYn0MOn5TrB9vphWcyVP3/Sc+A5h86fLxdRcE8Bc+9PwO8MuP4nv3JP5BO7" +
                                          "+L6POkiyNx5lWRhmZ84k0Hl0v75fyvEfy3182sC5AO8chp/9qz/7J2wP2jsu" +
                                          "1VdObH7ACNdPlIec2JWiENx7HDKjyMiN9befFn/1Uz/62HuLeAEQb7odw2v5" +
                                          "mEsM9jqwZ3z0G8u//v73PvfdvaMYO5uA/TFVXUcDD3GxdQFNTMdX3MIgjyfQ" +
                                          "A3NXu3aotQS2MiDYtblbL0z1OrB5F6LlXtnf1f8inYBE1+4Qrif27BvaJ777" +
                                          "41dLP/7DF2+J1JsN01XC6zsPFVJlgPwDp7OorcQ2gKu8IPzcVfeFlwBFGVDU" +
                                          "QC2IexFI4OwmMx5An7/4N3/0x/c/+Z2z0B4DXXYDRWeUfHsFRTKxwY5sg9zP" +
                                          "wne/Z1fk1pfAcLXITajQ//U7cYq0vufYEHwAtsGP//0nvv3Lb/o+kKMDnV/l" +
                                          "MQwkOGEtIc3fDH7x+U898qpnf/DxwiegpEofeemh9+RU8YLBm4vxZ/MB3nks" +
                                          "f3xbPrw9H/YP3fRQ7qZhUft4JU66ge6ANwO98NTLlg4xcjwQbauDbQ956r7v" +
                                          "Lz7zj1/cbWmn68QpYOPpZ3/pJ/vPPLt34kXiTbfs5Sdxdi8ThdCvPnLlYy/H" +
                                          "pcBg/uHLT/3Bbz31sZ1U9928LdLgre+Lf/Hf397/9A++eZvafM4NDoMyH9ED" +
                                          "tvmt+sqOTe5+uF2J2cbhj5dmBrrWBplnpki3bjo6OgYXnWrDymikcY7LcFbN" +
                                          "jierNoPX0ZlmhGmH1Kq+6tfBPoUSWLwN66Jq9Wx6GZKsFZFhXxog8GTZRMZu" +
                                          "mQsshZzQAyYts7xEuyyvsAFDG+N+qR+wSCMcrOSVnBKEjHJBa623hXpMEDiO" +
                                          "YxgsojAui9MxV06CUc0pZbbeZRd6i2BC2o3R8WxWVoXYn1GVRMzmpLldbZG4" +
                                          "r8+k4bS/LFdVFuFRSplzCT3uVaSapKPepGN0xHGLXbuzBT9hR8uKEyqpFZa5" +
                                          "qYLPuHCpdrhsjTJdtjVC6aXVXGzCcDLThimXNoKwRqNUJ6PQwdySzeZG7sfo" +
                                          "ZkZV6xUhRCpxDxcWm6xiEItxMtQ9bcDwTXdc5pS2ovPkIpASoV9esUpfERYD" +
                                          "TthOlli6qVT8yCbm/VXNR7E6XCnz8FRNrbg8K68xbo7qIq2v+s5i0Ama8kpf" +
                                          "9IGisQY7HNcRGp6/JZnSeFAdrxeoO2mOcG9BcCoF24bdm+lzK6sx7mg68baN" +
                                          "jaO0jTJtC2rao5bDKaf2x92mriE9BhdCvSz1uFKtWg0sEaOCRMQcD5nGg3JH" +
                                          "plQlgLfaZrDuW5xXGzUCZdhnZZmQmBa7WLB6zxrUPddalpMBIxCcnoTRqDsd" +
                                          "W0hrgsW03+6QqllCulJGtnvyfLERlC2Hqywe6JmZSAuhClMxplflrO+20dFa" +
                                          "i+kFs66tYzvKti4x6i7VkCppdcuJAzmo4kxDspXpplFSy0N0mdDZiCN7iyGr" +
                                          "lH1xKHBDw7fEwcTqDkscF8ilnrsVNM9N9fV8OZAHlrpYpKw0bEqbQb3hMu0x" +
                                          "k6mW5zAdkaWXMMxs1F57m7X9crdZ6/ZRbt2fTERUrXQYc8Yw482A5xudMkvO" +
                                          "0HqJwCnMQFJy0KLYYb0Rd6hqINUjgqgGPYTjSh0P3gabRdWV2aRXWnXC0JyI" +
                                          "bbzb0OmJ3LJQf8ZZCVzW3Ko7nOpCpevSGeWlNW6wmm2kabkmw6nv89uMROys" +
                                          "NZoy406WKuNKA6+FlGAt3WXWDFt6q2MPw35FcYa1brw1szJNiJQ+9mdzeTPZ" +
                                          "TjrzYU+Z92FpYq4xmHJ4zrZ4b0nJ5anYSiWfJrq4uanJFMfUYK7RN1vKAO4l" +
                                          "bqMkYUPMm/epfjwrY1Jz6IYtY4sn1pBdrNtmdTnuyiKqyWTaI4eLoCXJvXXY" +
                                          "aBsGB4/ZDSWT+pZcE53SxhDbeq/bFGSH77a7SBVZ0vOVVF25fYrcwGx5nrbc" +
                                          "EedxdJjREb/B6/2NOPFLNbgjtfiwjgTNRiNEnYqvz/wN1uqtJ5X6iuGi1B6z" +
                                          "9ioOpgnnsBwuO82NJQfqoDYTfQyvMx2EZPiOzxE25myzcZIYiEXzDULNglW9" +
                                          "lIj+OgIplxEriuttJbMaiymnddrmyG0LogwiIVrXxblNA214bDsWObVZ3tSR" +
                                          "rI81nBEa8brtslhz0YobQYOkp5jvYsJqtVKTmiCtM5FmSb1T6mqkzjRHVtNh" +
                                          "JXfoMnNyGtFrVcapNm7D4kY1dUtGZwM2wKu2UNUxSeZloY2llNj21X5zKWAt" +
                                          "HG+G22mPaMFdKlPNCVwdSC4etppBENSXaJKS1NxdSghcQ6azfp0gdBlrCGW+" +
                                          "ifB2y1mMtpOB7k1ASSHhrtaLE9qrqqaiYniaEbRWEmwJFBPfaBgkmnarAaH0" +
                                          "ho2+odUZtDfr6o21oRnIhh6ZUY/Kmh0rWmeLGV33wrDLRvRs1R2rJhNyvCY1" +
                                          "6SamlrbLvi6Yq5QQxaHRq3aRjSmKI0FIE8Z2WtF4vdGWaL/WrTXgSnfZzggE" +
                                          "T6Q5DI/4mVaJmpw4rSjicjAT4X6X8hiLpsq6m6H0mleFwOR7Eysh+A3iYhXY" +
                                          "HPLVWhengnIjsvvNVqOzIvpjLIK51nrK6bFSUtYNV15vQmuulpZpfdOpOuU5" +
                                          "Fq7sltC1S3ZlaDNGiezAC6daG6ktcpWWSqhqT2ZZb1qHeUdtSq3B1MgyPluh" +
                                          "mtoS+6qa4KVArjCV5rTVHzhaPaDbs/IS5roDew52HSGp420fwbhsOhxuyLno" +
                                          "0iRWURpTA6HKoKx0IhmpDzJiQsuCnBrt5tzpL3oonIWiF8oG25bHZrTx6php" +
                                          "2guk2VqzzdYwcirD0XAxaoBqi8JlO9kSuIdXuRYd9Ax+rlKrRdXiSlpQ69Ux" +
                                          "J8hckEbNWadXKjfYxlRvufhY7MRIZyiIbn2sb7CIFxqb9pjo+BhRZdJthPRK" +
                                          "qkeWpdLCm5Yl0jQDCo3r+nZNehVKFjR1TJRWfo+AFRhGqqN1WLWaGdvvLFb8" +
                                          "FInXus/IGR2XFH81IegIFhSweZQdDEaVOk5O5iY295AGbvYwHIkrQeKUmbG/" +
                                          "pbvzCTkol7pdrYwtyEFtSSy5NaHUVskKC8aevmDYIJzbgTYdYf6Ct4dTRS0n" +
                                          "oZil+jSqj0cDeJl5Ek0OFJ4I8WSRiVZ1O6lUxzzNpoLKm110W2HYsRMQDsVV" +
                                          "hfkCbQct155u9To9nRigBrQ4JVi2ljHZCewVvZ0aq2E3nUZ+va+tuKZbq285" +
                                          "ZmCOxDXeq1SFimn1BGu9yVBc6K5Ks2TVtYjKIqLLRFCu1bUGWwpLlN1coR1x" +
                                          "kpALlwtnqDxJIxMBgYcMTVMRqMZSDBxVWHeDQHa1htLrN+TA0W2ktpDbdW9k" +
                                          "0S6+Lq2Tdg9Uv4kxmYsk5498OBoj43kjjAiVqaMEUV9Rcw4mNratxSZnKZtI" +
                                          "bcq4wsShj1BagDYjsrbADI0Hby6oh1ozDIlRc6ubtMc1J3VfM5cIQU7URbc0" +
                                          "jNs1N0RFGK2r3tyZp4LJjzi0JEzKuoelPD6O3LrQ6MEyWRZwYsKsSupyxCYL" +
                                          "aVqL5ZDpBVbfQrEAVf1ZsEynJtay+YiyKKwGY9aSZefteoeckvqYZEu4ByMY" +
                                          "XxoLU3dT6ikdso6wbqlRd/hmmypTeGAERmJznSiAOZtDEkwSpFDcGtPFzBwQ" +
                                          "W62EsOAlQvPrkQ9vxjrNrNdAM4kxY7y5JdvxtOW2dA8Ootwi3tYapOl2Pl3x" +
                                          "M8Gym6K6Mfh4RUyGjUFHcPtjuFGFs8A26sZ0juGlGJ7UkhqtzWGmHzrOVtHx" +
                                          "BJWzQX+40TkyEjvSzKlh/Y1PU217W9nG3KBBeAgSzKZBsGJ6W2UywpNpe4sR" +
                                          "Dr5SpaAVCLg04I0GzilSf4FGZqKQIq26QShRPHi9Gq/pUT/wuISKbHWidRx9" +
                                          "Kfqm39ZRiZPlfkkamOWoNrETab20hDEcs5o4ACFZE7AF2LiIPifq27m3aDG+" +
                                          "tRUtFfZZsqxNPDYkxXnoevBAGOhC2ydH1rgzp5FNWUesObqpICTOqSJSL2Vd" +
                                          "cBh45zvzYwL7053U7i0O1EfdVXBAyxdKP8UJJXs5hgl0SVHjJALH2AS666jd" +
                                          "u+N+oqN05vAA/9jL9K52jav8jPbInVqsxfnscx9+9jm99/lyfj7LyTYB6yQI" +
                                          "3+4aK8M9wXQPUHrrnc+i3aLDfNwv+vqH//mh0bvsJ4uGyS19LB66nGOKeSP/" +
                                          "qGH/hlNynib5293nv9l6i/bJPejsUffolt73zUjXb+4ZXY6MJI380VHnKIIe" +
                                          "v+UAG2iGnkbGMd+3vlH56o2vPXVtDzp3sqWWU3jkVIPqVWYQeYqbMzhstl9O" +
                                          "7ChYH8+c7FYBsxbtQgRc4kE3tpcP+eprwnx8bXYcXbeEzd5RnA4OgiSC3nLc" +
                                          "KKEC1zW0wurXxr5X9BUU1TXypuV/XXlz+av/8szV3anbBTOHbnjbKxM4nv8Z" +
                                          "EvrQt973748WZM5o+eeL49bPMdiuJ/6aY8qNCJSrXI7sF/78kd/4uvLZs9AZ" +
                                          "FjoXO1ujaFKfPWidHgT6o3mgrzGtiG8QmH4S79P5baRElrH7YPTuE7lHJdBF" +
                                          "NQhcQyk6cYvCOnaxpBWjVSTmrleb/y965TdAhgOnR0k3SGODUsLiy85taJ9b" +
                                          "gf3rOOGffKWWxEluxcR7b/b/68E1PvD/+P/k/ztr+IGXWftgPqwTwAZk/knl" +
                                          "8/nlsaLZT6NoBgrJUQM9d/+Dt3yQ231E0r703JVLDzw3/ssiwY4+9NzFQ5fM" +
                                          "1HVP9nxPPF8II8N0CvHv2uVUWNw+mkAP3bksJtD54l5I+5EdxtMJ9NrbYSTQ" +
                                          "WTCehPw4MNFpSECxuJ+EeyaBLh/DJdCF3cNJkF8B1AFI/vjJvA19otIexEhh" +
                                          "8fteyeJHKCf7yHl1Lj6SHlbSdPeZ9Ib25ec6wvtfrH1+18fWXGW7zalc4qGL" +
                                          "u9J1VI0fuyO1Q1oX2k+8dM9X7nrz4c5xz07g43g9Idsbbl9UaC9MijKw/f0H" +
                                          "fvcdv/nc94pe6v8CGPjM+L0eAAA=");
}
