package org.apache.batik.bridge;
public interface GenericBridge extends org.apache.batik.bridge.Bridge {
    void handleElement(org.apache.batik.bridge.BridgeContext ctx, org.w3c.dom.Element e);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028784000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVXa2wcVxW+u+t3/HZihzyc1yaq07Cjqi1ScQiNXbvZdO1Y" +
                                          "dlLBmmRzd+bu7sSzM5M7d+y1g1GphBr4EUXBfSHqX65aUF9CVIBoq1RItFUB" +
                                          "qSUCCkqLxA/KI6IREvwIUM69d2Znduwtv7C01zN3zj3v851zn7uBGh2KBonJ" +
                                          "UmzRJk5qzGRTmDpEGzWw45yEvZz6eAL//cyHk/fEUVMWdZawM6Fih4zrxNCc" +
                                          "LNqpmw7DpkqcSUI0fmKKEofQecx0y8yiLbqTLtuGrupswtIIJ3gQ0wzqwYxR" +
                                          "Pe8ykvYYMLQzA5ooQhPlaPTzcAa1q5a9GJBvDZGPhr5wynIgy2GoO3MOz2PF" +
                                          "ZbqhZHSHDVcout22jMWiYbEUqbDUOeNuzwXHM3evc8Hel7r+cetyqVu4oA+b" +
                                          "psWEec40cSxjnmgZ1BXsjhmk7JxHX0GJDNoUImYomfGFKiBUAaG+tQEVaN9B" +
                                          "TLc8aglzmM+pyVa5QgztqWViY4rLHpspoTNwaGGe7eIwWLu7aq20cp2Jj96u" +
                                          "rDx+pvt7CdSVRV26OcPVUUEJBkKy4FBSzhPqHNU0omVRjwnBniFUx4a+5EW6" +
                                          "19GLJmYuhN93C990bUKFzMBXEEewjboqs2jVvIJIKO+tsWDgItjaH9gqLRzn" +
                                          "+2Bgmw6K0QKGvPOONMzppsbQruiJqo3JB4AAjjaXCStZVVENJoYN1CtTxMBm" +
                                          "UZmB1DOLQNpoQQJShrbVZcp9bWN1DhdJjmdkhG5KfgKqVuEIfoShLVEywQmi" +
                                          "tC0SpVB8bkwevnTBPGbGUQx01ohqcP03waHByKFpUiCUQB3Ig+0HM4/h/lcv" +
                                          "xhEC4i0RYknzgy/fvPfQ4NU3Jc32DWhO5M8RleXUtXznOztGh+5JcDVabMvR" +
                                          "efBrLBdVNuV9Ga7YgDD9VY78Y8r/eHX6p1986LvkL3HUlkZNqmW4ZcijHtUq" +
                                          "27pB6P3EJBQzoqVRKzG1UfE9jZrhOaObRO6eKBQcwtKowRBbTZZ4BxcVgAV3" +
                                          "URs862bB8p9tzEriuWIjhJrhh2LwG0LybxdfGPqCUrLKRMEqNnXTUqaoxe13" +
                                          "FECcPPi2pOQh6+cUx3IppKBi0aKCIQ9KxPuQp7pWJIowQVdHxFuKZ5j9f+Rd" +
                                          "4Xb1LcRi4PId0YI3oFaOWYZGaE5dcUfGbr6Qe1smEy8AzyMM7QdxKSkuJcSl" +
                                          "pLhUjTgUiwkpm7lYGVQIyRwUN6Br+9DM6eNnL+5NQDbZCw3coRVRbdv9FzgY" +
                                          "UU/U9edm7Kd+84s/3RlH8QACukLYPUPYcCjtOM9ekWA9gR4nKSFAd/2JqW8+" +
                                          "euORWaEEUOzbSGCSr6OQboChgEVfe/P8ex+8v3YtXlU8wQB33Ty0L4ZacB5A" +
                                          "C6uModYq+kjDNn8MfzH4/Yf/uI18Q2ZS76iXzrur+WzbIXfExPNWhgbreV66" +
                                          "nHttZz18ENi29vDKqnbi6TtkFffW1twYtJTnf/Xvn6We+P1bG4S9lVn2pw0y" +
                                          "T4wa1UBkzXAwIaDTb7Q59XrnlT/8KFkciaOGDOoF37jY4G3+KC1CA1HnPIxt" +
                                          "z8PEEDTu3aHGzScOaqlEg75Rr4F7XFqseUL5PkObQxz8sYID6MH6TT2q+hsP" +
                                          "/3nbySOlsyLZwm2aS2uEDsNPTvHmWm2iuyLuj7L8zsRzb91/QL0SF32FY/QG" +
                                          "/aj20HA4ECCUEmigJjeH73SA0L3RQo56K6ce3I1fzr26nBRRaIXmyjCAIfSt" +
                                          "wajwmt4w7BcZF9UCTihYtIwN/sl3eRsrUWsh2BEI0yNzHhJElPNd8LvNQ0/x" +
                                          "n3/tt/k6IBFJ0A+KdQ9fkiK74vxxP18OCLLbINsOBHUMcG8ALPKIJE+ZEHa9" +
                                          "oOO8QTjC/Ktr/x0v//VSt0xkA3b8EB363wyC/U+NoIfePvPPQcEmpvJxI8Ca" +
                                          "gEz2sL6A81FK8SLXo/LVd3c++QZ+CrohdCBHXyKiqcSlfX5h14VUWdjejOVT" +
                                          "93HqhTvVlGaVU3yUhEwX/hkVFEfEOsL97KEpf0/z5bMMdZSwqRnEOwZaD33C" +
                                          "lEv1MsDovDcnKMu9H8x9+8PnJXpEh4oIMbm48o2PU5dWZADk5LVv3fATPiOn" +
                                          "L6Fst4g2x7M9nyRFnBj/44vLP352+ZG4Z2iKoYZ5S9fgcLKOaaFZOqdevvZR" +
                                          "x4MfvXZTKFo7jIcbywS2pW49fBnmug1EW9sx7JSA7q6rk1/qNq7eAo5Z4KhC" +
                                          "i3ZOUGirlZo25FE3Nv/29Z/0n30ngeLjqM2wsDaO+dgLwwuUFnFK0JEr9ufv" +
                                          "leWz0AJLt4gqWhfndRs8K3dtnO9jZZuJDF364cD3Dz+z+r5oaXYFMqSmj3MW" +
                                          "W9ddDeQ4q76w2tUysHrq1wJWqiNnOwBxwTWMEGqFEazJpqSgC1+2S4/a4t8Z" +
                                          "hgbq1AH0WPkgLDwt6THc2qL0DDWK/2E6SLy2gA5YyYcwSZGhBJDwxxL4IFY7" +
                                          "i/CXab5skc+n6gYjNL7sq8k9cQXze4IrL2E59cXV45MXbn7maTnNwOVtaUmM" +
                                          "7HADkUBb7St76nLzeTUdG7rV+VLrfr8MeqTCAbpuD4HBLHRum0d2WwSynGQV" +
                                          "ud5bO/zazy82vQtZPIti4Oy+2dAFSE77gHsuDACzmWAECF3hBZYOD31r8cih" +
                                          "wt9+J/LLGxl21KfPqdeeOf3LK1vXAHM3pVEjVDipZOE259y3aE4TdZ5mUYfu" +
                                          "jFVAReAC18s0anFN/bxL0nBx7ORJiPnlTPjFc2dHdZf3Rob2rgei9QMG1OIC" +
                                          "oSOWa2qi0wI6BDs1d0O/Nbu2HTkQ7FRDuXm97Tn1vq93vXK5NzEOhVRjTph9" +
                                          "s+Pmq20/fF2Uc0AIN+VYmchlJmzbHzMT172ZUnbSCt9nKHbQ2+WoEZMjHX+9" +
                                          "IKhENl7gy/J/AUlVuM0JEgAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028784000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5aczkZnneb+/NsZsNORpIQpINIpnwecb2HNZSYOzxzHjG" +
                                          "M57Lnhm3ZeNz7Bnfx9hjGhQiUaIiUdQuLZUgv4LaonCoKmqliipV1QICVaJC" +
                                          "vaQSVFXqkUYiP3qotKWvPd+9WSJ+dCR7Xr9+3uc+3vfxK29AZwMfKriOuVmY" +
                                          "TrirJuHu0izvhhtXDXY7THkg+oGqkKYYBBMwd0N+/KuX//1Hn9av7EDnBOhe" +
                                          "0badUAwNxw5GauCYa1VhoMuHs5SpWkEIXWGW4lqEo9AwYcYIwusMdMeRpSF0" +
                                          "jdlnAQYswIAFOGcBrh9CgUV3qXZkkdkK0Q4DD/oodIqBzrlyxl4IPXYciSv6" +
                                          "orWHZpBLADBcyJ55IFS+OPGhdx/IvpX5FoE/U4Bv/saHr/zuaeiyAF027HHG" +
                                          "jgyYCAERAbrTUi1J9YO6oqiKAN1jq6oyVn1DNI0051uArgbGwhbDyFcPlJRN" +
                                          "Rq7q5zQPNXennMnmR3Lo+AfiaYZqKvtPZzVTXABZ7z+UdSthM5sHAl4yAGO+" +
                                          "Jsrq/pIzK8NWQujRkysOZLzWBQBg6XlLDXXngNQZWwQT0NWt7UzRXsDj0Dfs" +
                                          "BQA960SASgg9dFukma5dUV6JC/VGCD14Em6wfQWgLuaKyJaE0H0nwXJMwEoP" +
                                          "nbDSEfu80X//pz5it+2dnGdFlc2M/wtg0SMnFo1UTfVVW1a3C+98mvl18f6v" +
                                          "v7gDQQD4vhPAW5jf/8U3P/TMI69+cwvzzreAYaWlKoc35Jelu7/7LvIp/HTG" +
                                          "xgXXCYzM+Mckz91/sPfmeuKCyLv/AGP2cnf/5aujP5s//0X19R3oEg2dkx0z" +
                                          "soAf3SM7lmuYqt9SbdUXQ1WhoYuqrZD5exo6D8aMYavbWVbTAjWkoTNmPnXO" +
                                          "yZ+BijSAIlPReTA2bM3ZH7tiqOfjxIUg6Dy4oFPgegra/h7NbiE0g3XHUmFR" +
                                          "Fm3DduCB72TyB7BqhxLQrQ5LwOtXcOBEPnBB2PEXsAj8QFf3Xki+oSxUOBfB" +
                                          "kIn8aTfzMPf/EXeSyXUlPnUKqPxdJwPeBLHSdkxF9W/INyOCevPLN769cxAA" +
                                          "exoJoScBud0tud2c3O6W3O4xctCpUzmVd2Rkt0YFJlmB4AZp786nxr/QefbF" +
                                          "x08Db3LjM5lCkzzaHswfToN1T90+FTezPEDnuU8Grvngf7Gm9MLf/2fO6tFs" +
                                          "miHceQv3P7FegF/53EPkB17P118EiScUgaOAmH7kZBAei5ssGk+qEOTTQ7zI" +
                                          "F61/23n83J/uQOcF6Iq8l6x50YzUsQoS5iUj2M/gIKEfe3882Wwj6/peUIfQ" +
                                          "u07ydYTs9f3MmAl/9qjpwDiDzsaXcje4O4e558fgdwpc/5tdmSWyia2LXyX3" +
                                          "4uzdB4HmusmpUyF0Ftmt7haz9Y9lNj6p4IyBnx27n//rP/9ndAfaOczWl4/U" +
                                          "P6CE60cyRIbscp4L7jl0mYmvZsr6u88Ofu0zb3zi53J/ARBPvBXBa9k94xiU" +
                                          "O1A2Pv5N729e+/7L39s58LHTISiRkWQaMhgEefUCkmiGLZq5Qh4PoQeWpnxt" +
                                          "X2oeVDPA2LWlWc1VdR+o3zlrmVV2tyUgjyfA0bXbuOuRsn1D/vT3fngX/8M/" +
                                          "evMWTz2umJ7oXt9aKOcqAegfOBlFbTHQARz2av/nr5iv/ghgFABGGWSDgPVB" +
                                          "BCfH1LgHffb83/7xn9z/7HdPQztN6JLpiEpTzCosyJOhDoqyDoI/cT/4oW2e" +
                                          "iy+A25U8NqFc/ndu2cnD+u5DRTAOqISf/IdPf+dXnngN8NGBzq4zHwYcHNFW" +
                                          "P8o2B7/0ymcevuPmDz6Z2wRkVf75J19/PsNaywk8md/fm90KW4tlw2ey2/uy" +
                                          "2+6+mR7KzDTOsx8jBmHPUQywOVByS/3E1DHwDQt423qv8sHPXX1t9bl/+tK2" +
                                          "qp3MEyeA1Rdv/vKPdz91c+fIXuKJW8r50TXb/UTO9F0HpnzsJ1HJVzT/8SvP" +
                                          "/eFvP/eJLVdXj1dGCmz8vvSX//Od3c/+4FtvkZzPmM6+U2Z3ZI9s9ld+e8OG" +
                                          "d8zaWEDX938MPxORWOaTaSEqhCjcFgw93ciljegVq+TSM0pjeWj0Z9JaUNjS" +
                                          "XDEZwrJGqVKQomowTnvlXlUpbEqLUsvVCR+juBmhjdverFIWuSZO8jTheKUR" +
                                          "HTY5whtzJLnymKQOd+kKPaLWMc31KriCCLYSxeG6ShZLaR9Nl+i6Vi6ldjUi" +
                                          "WjrSJRy7w1npqLMqe2lrNLEaLtVKpzFW3lBrIa2odQaG5U17BWsUx/emiiDG" +
                                          "vUrT0LHUT/qkzPQ914qrDXflyWOOLmpWt0s52lCVk+KmtjEYyZswYdTyIzeI" +
                                          "Q5ruoIthMU69eJ6MBmpts1rP5z1mmNbLjjPUQQ0dTFK5Lpa8soi3OsS6IbQG" +
                                          "ul+ONza92CAth0V7bIoMmoLk6UJ73G7wMthCIsiyNzXmEsV5UoNj1X6UxrN2" +
                                          "D1XXcq2tmlW/IKvhxuMjzKkXJDeYUqqMFeVxsrSthVAiZsFSt1bVTtKeFVud" +
                                          "Rt/haGvuWFqr2TUIri62CuGQ4sU+TkwYuSYuzNTqFdwNL5aHizT0prwxx3ym" +
                                          "7QauM+nHYqulVlU6njJRVfSQouwinSVeifxGUnDXYZVUxvyIRyqsPOA5juoQ" +
                                          "q+4GaxLjVB947T5XdCx+tIxtwjaaXIKJhTI1rZTwFtOx5pHex1ESx4sS122m" +
                                          "PWJGUWq8lBwvQJb8mu7QXbYQBtPGgg6XYhtfeMwotQsIsbDiSrc47LbWA5bt" +
                                          "91LXDaShHxkdz0E7BFavL5fijByHAs9T/Y4z75fIcJL0CIsTLKLUYJlh33WG" +
                                          "w85Y9yVekF1cmvZLDV3pLC1lpbfKXW3RBeqlaM0Z6wxPbeIhiEqyOHZ5oiat" +
                                          "YnVtT4hBS2pxw6RYcnRPHhTRWGwTm27T5QySGxIovSgU2z0M1mFTXic6RWJG" +
                                          "cTRf2eliA2vrgTbE+hzakVGkMdXZcq82MtUZF85Sm03Dll4od+QGL0q9Ndhm" +
                                          "ED5DKHw/4vGWWJ0vGg2cn1dr85oPq+1ZxS3htQqzXjFomzNXQt+zppggG8t2" +
                                          "yHlI1SUqAxQYZZg6Hj/qpq0Sp1H4UvB1VmSlEVtRu8RQjsOuE48IaSIIGJHI" +
                                          "/KLOo9woqFUQiai5eJhSvhFN6aXe8XUdYeJWkdlIiaK1Bh7J+Ux31KO8vj2b" +
                                          "cJ7oJGoJbVKkPBgYiMsO9UpB5hKUdt0uYRTFLkkP8W4yiIZu1Z12aCce8ko7" +
                                          "aUZdobzEtcJIwWZSiZFHBjagleKcRp2myE7nQkukyorMaS3JrwzVUmBRm1o9" +
                                          "3fR61aGSdMerqCOPTZfRueVkwRnxyrWq5rzFD+nNKOb6FcIv4I1eRe3bTKHc" +
                                          "HzYkgYxR2RnxI0lZ4810Mec4mMNVxap2lUINC2B0ZLZrwzoZrZj5gBvMZXIZ" +
                                          "sj1cXU3r+GKE2d1xs67ASMeb1gpqxI6mIkVxbCqNW+TYr7BDySH1BcVrKjyo" +
                                          "qUmhtkbn4czkajFwDnSyKTKYIMpEuU5WIlCy5l5htWz07VpPS9sYPNfgiC7V" +
                                          "hogwrlaMWepHfmGaSvRMo5JBf6ovJF/lKxW7HYZCWqpRfQPB142uZ0tGZRKu" +
                                          "mpo2LYXxPOxMbA2ere3KVC0MSlILG+MmbyNuXNxMsFgsccQqndVjWmxMpOqw" +
                                          "jM9825zAtW5zJRsi22qwThOtLudYCy10yRJZL7XtAZ2EaW1AUY1JhIrtVjqW" +
                                          "WdEzqUW1PPKxZnXW9AKVA9V1xUrDJK0Fc7pR6bUrkwniFfRgAKO2tBmzZrBh" +
                                          "hNhCxDESUY2gP5is29bUQoxow0TLKlNLg1Eq4SV4yBTHTRRpzuFhCxaXSLFd" +
                                          "xyiS5CjLWHSWaruKjutFBh0NnXKlW5FVlC5pqY9UbGI0EumZtVmSdVobh7G4" +
                                          "jK0Qi6uELDRxjpwY+jyk4z4cmKg6CnxuGugIQdHFTT9t6x3KHPSVGrPuD4tw" +
                                          "YqNwGMKrCk00O8V6oasMcW1ldKvYOkkGpRpLMoxE9wOWaHM9uVWrM4Mu3aEK" +
                                          "AtUWcYdla8PJkoS7oQ8nxTUM8+OwmKzqqFSjCLSCxhsS5gp9h9bUwXowGMqU" +
                                          "5a47CV0jxQWVIgFTqddKzW5tzMwcmOEVVC4UhkKB9B1dIYn2bNM1QLUytVlZ" +
                                          "L2E8N1WW6pLlJzja9vTJmjdbIs+hG06nYnCSXPFNSqPYgMGrXcrVinBalno9" +
                                          "RRjH3sim2FgQGyhKmtS61Asazroh291ehLdrCV6oDezOzKV0zKF7koXVHGTA" +
                                          "lZWpUG+sygy/RrX6ZGCwNlNpBiG2QJJqD7c3o6ZNLGEMWzMDtIwUhBYmIEbX" +
                                          "mQvlMa4tZKbLimJTYD1FXa+FUYL1tPVMmHSbTnVJy9ImHiPuFMM1wraiRYma" +
                                          "4kFS7YzrVa/ir0qw1/eqat0pC1hXJw1UYLmW4ZuCg5SbFNpfwwguwEUbLdoL" +
                                          "lVl6PSQOGiJbUBZMHEdc0252ix3KxyNtbarTtFjvMIBvb6prtgJyXxdVQpsF" +
                                          "qVKIOo0mWsHkBtpIC2nBLzvibN7seWNrifamU1xRGuoQ86qVGAm5TdD2vVLc" +
                                          "mXpG32ZjIokn0x7V8pqUmHZcb7wgSwVkjMEiFtYEEMdeqd4uTgerBdOIw8qk" +
                                          "LSMeU2w0pl0YoSpjZoMs6uX5Zi7HY6GlE51GnCQMRjfnVQMmZ6JUDlZywa4s" +
                                          "5ss+Aw4mtRUuD2epitE+g1BlXJ7xWLk3k+yqJU7sfszyochZvWobGI0jpOo4" +
                                          "rFZsJlUnnNKq+nyBZ3zNr/VUb0LWJTdqYG2CaY8iq6gg03i8sVtDPlLKEgun" +
                                          "YrqpIethKAzo0MDYTQFR6s0xVa0u2kHUqJOpNa1TZBPVCWHONtCSX5MNPQ7x" +
                                          "QgdmmFZiIqWuNgBmV1kNZbql9awOdjguTy35huEKLIWU8Q0qUthEEcoWN9ei" +
                                          "ZZOvj9Q6WaoFRdFu9mEpYYo2kVTZUccYgLQ1WDZlRGkrgoaOHAnxF6qBD3ut" +
                                          "EkuTzpidiohnFGO6QjSCklJk4b4UIe3JalhtjhrRzMKrE7u09nB0PeuW+ynF" +
                                          "6mDbMnF1PCgMLLDtgbUmwsnFOt0v8HNL1s2OlUrttDcpVRGBs6UxGeJ2ty0N" +
                                          "kcLUoYTesj0r4HRXp/pmFZT8DlznTD7qAY9b1OvZFpv+6U459+SH0YPmJDjc" +
                                          "ZC+KP8XuPvlJBEPogigFoQ+OgCF08aBbuqV+pBtzav/w+8jtGj/bjk92uHn4" +
                                          "du3J/GDz8gs3X1LYL5Syg02GswHoho77PlNdq+Yxij709O0Pcb28O3vYaPnG" +
                                          "C//y0OQD+rN5p+GWBhADXcpWDrIm+EGz+9ETfJ5E+Tu9V77Veo/8qzvQ6YO2" +
                                          "yy194+OLrh9vtlzy1TDy7clBy8WHHr/l5OfIqhL56iHdp98tfu3G15+7tgOd" +
                                          "OdqLyjA8fKKzc4fm+JZoZgT2G9WXwCneiQ9njrZ5gFrzPhsGrvfudTLz/+zt" +
                                          "vW52f0dy6Fq3+MzOgZOO9jzEh95z2GEgHdNU5Vzr1zjbyg/komSqWbfvvy8/" +
                                          "Wfrav37qyva4aoKZfTM88/YIDud/hoCe//aH/+ORHM0pOWv9H/ZMDsG2/eR7" +
                                          "DzHXfV/cZHwkH/uLh3/zG+LnT0OnaOhMYKRq3uDd2cq37+W3bW9uvXzve8c+" +
                                          "9L0ZNNhW7iqOtZt95FHtMNePnkPI+X2Rx+W2zZk9572uGyF0ly7aiqnuLctB" +
                                          "P3gkpElwnF87hnIY68++3Un+KKUEEDjWks308uAtX3m2XybkL790+cIDL3F/" +
                                          "lXvewdeDiwx0QYtM82gX8cj4nOurmpHLdHHrbG7+B0g/cBs1htC57SDnN97C" +
                                          "fySErpyED6Gz+f9RuI+G0KVDOIBqOzgK8rEQOg1AsuELWbPySFrZS4e5Jq++" +
                                          "nSYPlhztNmapKP+atp82ou33tBvyV17q9D/yZuUL226nbIppmn99YaDz2zg9" +
                                          "SD2P3RbbPq5z7ad+dPdXLz65nybv3jJ8GJxHeHv0rSMI7CfD3OfTP3jg997/" +
                                          "Wy99P++4/R9FOoSq5hwAAA==");
}
