package org.apache.batik.bridge;
public interface MarkerBridge extends org.apache.batik.bridge.Bridge {
    org.apache.batik.gvt.Marker createMarker(org.apache.batik.bridge.BridgeContext ctx,
                                             org.w3c.dom.Element markerElement,
                                             org.w3c.dom.Element paintedElement);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471028784000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVXfWwcRxWfu/N3/J3EDvlwPuoE4oY7VaVI5UJo7NrNhbNz" +
                                          "itNAnTaXud25u433djezs/bZBVQqIdJ/qiiktCDVf7mqQKVUiAqQaBWERFsV" +
                                          "kFoioKAWJP7hK6IREvwRvt6b2b3dW/vgLyzdeHbmzZt5b977/d68cJO0u5yM" +
                                          "MUukxYrD3PS0JQqUu0yfMqnrnoGxovZ0iv71/O/n7k2SjgXSX6XurEZdNmMw" +
                                          "U3cXyB7DcgW1NObOMabjigJnLuNLVBi2tUC2G26u5piGZohZW2cocJbyPBmi" +
                                          "QnCj5AmW8xUIsicPJ8nIk2SOx6ezedKr2c5KKL4jIj4VmUHJWriXK8hg/iJd" +
                                          "ohlPGGYmb7giW+fkTsc2VyqmLdKsLtIXzXt8F5zM37PBBQdeGvjb7SvVQemC" +
                                          "rdSybCHNc08z1zaXmJ4nA+HotMlq7iXyOZLKky0RYUHG88GmGdg0A5sG1oZS" +
                                          "cPo+Znm1KVuaIwJNHY6GBxJkf7MSh3Ja89UU5JlBQ5fwbZeLwdp9DWuVlRtM" +
                                          "fOrOzLWnzw9+K0UGFsiAYc3jcTQ4hIBNFsChrFZi3D2u60xfIEMWXPY84wY1" +
                                          "jVX/poddo2JR4cH1B27BQc9hXO4Z+gruEWzjniZs3jCvLAPK/2ovm7QCto6E" +
                                          "tioLZ3AcDOwx4GC8TCHu/CVti4alC7I3vqJh4/gnQQCWdtaYqNqNrdosCgNk" +
                                          "WIWISa1KZh5Cz6qAaLsNAcgF2dlSKfraodoirbAiRmRMrqCmQKpbOgKXCLI9" +
                                          "LiY1wS3tjN1S5H5uzh198lHrhJUkCTizzjQTz78FFo3FFp1mZcYZ5IFa2DuR" +
                                          "/zIdeeVykhAQ3h4TVjLf+cyt+46MXX9dyezaROZU6SLTRFFbL/W/tXvq8L0p" +
                                          "PEaXY7sGXn6T5TLLCv5Mtu4Awow0NOJkOpi8fvpHDz32dfanJOnJkQ7NNr0a" +
                                          "xNGQZtccw2T8AWYxTgXTc6SbWfqUnM+RTujnDYup0VPlsstEjrSZcqjDlt/g" +
                                          "ojKoQBf1QN+wynbQd6ioyn7dIYR0wo8k4DdB1N8YNoJ8KlO1ayxDNWoZlp0p" +
                                          "cBvtdzOAOCXwbTVTgqhfzLi2xyEEMzavZCjEQZX5EyVu6BWWmaV8kfFJ+ZHG" +
                                          "AHP+f6rraNXW5UQCHL47nu4mZMoJ29QZL2rXvMnpWy8W31ShhOHv+wMACnZL" +
                                          "q93Scre02i0d3Y0kEnKTbbirulG4j0XIbIDW3sPzj5y8cPlACkLJWW5Db9Zl" +
                                          "qu0KPmBh7HQyqT8+7zz7y5/+4e4kSYb5PxAB7nkmspGYQ53DMrqGwnOc4YyB" +
                                          "3LvPFL701M0vnpOHAIk7NttwHNspiDUAUACiL7x+6Z3fvLd+I9k4eEoA6Hol" +
                                          "4C5BumgJEItqQpDuBvQow7b9G/4S8PsX/tBGHFBhNDzlx/K+RjA7TsQdCdnf" +
                                          "IchYK8crl6PX9rQCBwls649fW9NPPXeXSuHh5oSbBj75xs//+eP0M799Y5Nb" +
                                          "7xa282GTLTGz6WiwZVNlMCtxM2DZovZu/9XffW+8MpkkbXkyDL7xqIkcf5xX" +
                                          "gD20RR9ge0tQLoSsvS/C2lhucFtjOpBGK/b2tXTZS4zjuCDbIhqCmgLRc6I1" +
                                          "o8eP/trjf9x55lj1ggy2KEfjbu1AL7iygMzaYNC9MffHVX5t9oU3HjikXU1K" +
                                          "UkGA3oSMmhdloxcBm3IG7GmhOTjSB5seiOdx3FtFbWIffbn4ymfH5S10A7MK" +
                                          "CkgIpDUW37yJGLJBkuFWXeCEss1r1MSpwOU9osrt5XBEAsyQinkIkC0Y4qPw" +
                                          "+6APnfI/zo442I4qQJLyY7Ldj824jK4kdg9ic0iKfQii7VCYx4D1JoAi3sj4" +
                                          "gxZcu1E2aMlkiDD/GDh418t/fnJQBbIJI8EVHfnfCsLxD0ySx948//cxqSah" +
                                          "Ya0RYk0opghsa6j5OOd0Bc9R//zbe77yGn0WqBDoxzVWmWSUlMKOILEP/vfE" +
                                          "9gusQHorSi/fraV1u5bGOhIiHadmpJOmpNgx2U6is31Ixe8cNh8TUFtxBjCj" +
                                          "8DpQu2vDISpLwsd0sG68ReJEqtKiduXG+31n33/1lvRXc1kbRelZ6mRVoGCT" +
                                          "ReAajfPECepWQe4j1+ceHjSv3waNC6BRA7ZzT3GgqHoTpvvS7Z2/+sEPRy68" +
                                          "lSLJGdJj2lSfoVhAQhkAccrcKrBb3fnEfSoWl7ugGZTeIRv8tWEAr3jv5sEz" +
                                          "XXOEvO7V745+++jza+9JfnDq4OkoJ6KGHRtqbFUXai+uDXSNrj34C5mijdqt" +
                                          "F0Ct7JlmBAGiaNDhcFY2pCt7lUMd+e8hQUZbxBTwlepIAz+t5B+G509cXpB2" +
                                          "+T8qB+VrTygHqlQnKlISJAUi2NXABYlmXsePWWy2q36h5V1ESoE7mkJPvmUC" +
                                          "fPXUa6aofXPt5Nyjtz76nKoM4BW0uiprXyjlFWg1MHp/S22Bro4Th2/3v9R9" +
                                          "MOmnzZA6cIhUuyI5dRZY0MGb3RlLf3e8gQLvrB999SeXO96GID5HEhRS+Fzk" +
                                          "JaHKZsAQD8j0XD6k08hbWOJS9vBXV44dKf/l1zK8fPrd3Vq+qN14/pGfXd2x" +
                                          "Dvi1JUfaoQJg9QV4Frn3r1inmbbEF0if4U7X4YigBd5pOdLlWcYlj+XgBdaP" +
                                          "QUjxlSP94ruzrzGKPCPIgQ3PmU3IGlJxGbLA9ixdshaAQzjS9MgKaM5znNiC" +
                                          "cKRxlds22l7U7n9i4PtXhlMzkEhN5kTVd7peqUGh0XeX4lRsByXj1FWJlirm" +
                                          "Zx0nKNnaB/36zFUyOC5IYsIfRdBIqPIIP5ekOk92san/BzATEO5SEQAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471028784000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5eczk1l3eb+9Nmt0kbRLSJs2xKSTTfp4Z2+MZbSm1PZc9" +
                                          "nhnPeA6PgW58ju3xNT5mPC5BaaTSikohgg0Uqc1fqYAqPYSoQEJFQQjaqhVS" +
                                          "UcUl0VYIiaNEav7gEAHKs+c7Zr/NJuofjGTP8/Pvvt57P7/yGnQ2DKCC79mb" +
                                          "ue1F+1oS7Vs2th9tfC3cZ1iMk4JQUylbCsMRmLuuPPbly//+xgvGlT3onAjd" +
                                          "K7muF0mR6bnhUAs9e6WpLHT5eLZha04YQVdYS1pJcByZNsyaYXSNhe7YQY2g" +
                                          "q+yhCDAQAQYiwLkIMHEMBZDeobmxQ2UYkhuFS+gXoVMsdM5XMvEi6NGbifhS" +
                                          "IDkHZLhcA0DhQvY8AUrlyEkAPXKk+1bnWxR+sQDf+I2PXPnd09BlEbpsunwm" +
                                          "jgKEiAATEbrT0RxZC0JCVTVVhO52NU3ltcCUbDPN5Rahe0Jz7kpRHGhHRsom" +
                                          "Y18Lcp7HlrtTyXQLYiXygiP1dFOz1cOns7otzYGu9x3rutWwmc0DBS+ZQLBA" +
                                          "lxTtEOXMwnTVCHrvSYwjHa92AABAPe9okeEdsTrjSmACumfrO1ty5zAfBaY7" +
                                          "B6BnvRhwiaAHb0s0s7UvKQtprl2PoAdOwnHbVwDqYm6IDCWC3nUSLKcEvPTg" +
                                          "CS/t+Oe13gef/6jbdvdymVVNsTP5LwCkh08gDTVdCzRX0baIdz7F/rp031c/" +
                                          "uQdBAPhdJ4C3ML//C69/+P0Pv/r1Lcy73wSmL1uaEl1XXpbv+vZ7qCdrpzMx" +
                                          "LvheaGbOv0nzPPy5gzfXEh9k3n1HFLOX+4cvXx3+2ezZz2s/2IMu0dA5xbNj" +
                                          "B8TR3Yrn+KatBS3N1QIp0lQauqi5KpW/p6HzYMyarrad7et6qEU0dMbOp855" +
                                          "+TMwkQ5IZCY6D8amq3uHY1+KjHyc+BAEnQcXdApcT0Hb38PZLYKmsOE5Giwp" +
                                          "kmu6HswFXqZ/CGtuJAPbGrAMon4Bh14cgBCEvWAOSyAODO3ghRyY6lyDu1Kw" +
                                          "0AIyf9jPAsz//yOdZFpdWZ86BQz+npPpboNMaXu2qgXXlRsx2Xj9i9e/uXcU" +
                                          "/gf2AAUKcNvfctvPue1vue3vcoNOncqZvDPjuvUo8McCZDaoeXc+yf888/Qn" +
                                          "HzsNQslfn8msmeSp9kD+cBrgPXn7OtzMigCdFz4FxOUD/9W35ef+/j9zSXdL" +
                                          "aUZw701i/wS+CL/ymQepD/0gx78Iqk4kgSgBCf3wyQy8KWmyVDxpQVBMj+mW" +
                                          "P+/8295j5/50DzovQleUg0o9kexY4zVQLS+Z4WH5BtX8pvc3V5ptWl07yOgI" +
                                          "es9JuXbYXjssi5nyZ3c9B8YZdDa+lEfBXTnM3T8Cv1Pg+t/syjyRTWzj+x7q" +
                                          "IMkeOcoy309OnYqgs+V9fL+Y4T+a+fikgTMBfpr3P/vXf/7PyB60d1yqL+8s" +
                                          "fsAI13bKQ0bscl4I7j4OmVGgZcb6u09zv/bia5/42TxeAMTjb8bwanbPJAZr" +
                                          "HVgzPv715d9877svf2fvKMZOR2B9jGXbVMAgzJcuoIluupKdG+SxCLrfspWr" +
                                          "h1pPwFIGBLtq2XhuqneBxTsXLfPK/rb+5+kEJLp6m3DdWbOvKy9854fvmPzw" +
                                          "j16/JVJvNkxX8q9tPZRLlQDy95/MorYUGgAOfbX3c1fsV98AFEVAUQG1IOwH" +
                                          "IIGTm8x4AH32/N/+8Z/c9/S3T0N7TeiS7UlqU8qWV1AkIwOsyAbI/cT/mQ9v" +
                                          "i9z6ArhdyXMTyvV/91acPK3vOjYE64Fl8FP/8MK3fuXx7wE5GOjsKothIMGO" +
                                          "tXpxtjP4pVdefOiOG9//VO4TUFInzz7xg2czqtWcwRP5/aeyW2HrsWz4/uz2" +
                                          "gey2f+imBzM38XntY6Uw6nqqCXYGau6ptywdXGA6INpWB8se/Mw931t85p++" +
                                          "sF3STtaJE8DaJ2/88o/2n7+xt7ORePyWtXwXZ7uZyIV+x5ErH30rLjlG8x+/" +
                                          "9Mwf/vYzn9hKdc/Ny2ID7Pq+8Jf/8639T3//G29Sm8/Y3mFQZvfyAdvsD3t7" +
                                          "x0Z3QG00pInDHzsR9OlaGSZTPYZ7CMwgjfrKXnOx10C9GT6RJjQ2Zjy8F/QM" +
                                          "uZeaUY9wR5IQq2UsRhFEtbQ0hGWRnAyWtMrAS9NcRFR9ouPOctCZjE1iOZDI" +
                                          "aWPYDCeLpmd6HWLKcLjRqdDDxmo9XEUVuSwj6hRezdlNqmpt2UnFCJNrOA6r" +
                                          "larC9Isxtul2x/EimQV1hOOLzGA5josbvbt0A9drJd5KLJorvAT3YRdflHlr" +
                                          "LvBCRYiDhqj2nO56jCjChsTrynxa6vXlfleSLXPOuGzcYyekWY7GVLlVrsSY" +
                                          "b7ZEzxCnZcVTGHnDkY45cCkLI5xpNRnToalwTNWlAYt+UtFSTe0EZQXrdFjU" +
                                          "oi104ozbzDQwhU7VmMMmo3qGzbVaM0fG5+a0oC9GoVKebJYOq3ZCNqKFVIiq" +
                                          "TSztIjhHkgNVa60sGedXk4HmUIHKb2Sq3VOK1bSUSoLDoC5RaHtR117iprDp" +
                                          "i2xnsSkOZ+N2q1ptOS11XiSwsFXyRF7hvILoOqXOJJboNdNrzyotMmEWOt7l" +
                                          "DYSRqrXxGGNscoDpa1nU2LXq1+rTeGIPo67eD/opO3XTda3QKY5bzdAkZgpi" +
                                          "KaMBatBkrxlSRtAUTaRejivFRKcb3anAzaroelayJgLse6rqlZkhqrRLZBkn" +
                                          "B0rNEPqoWJgHcWOaWq4phohFrViC68Blb+XgAyryKg1QI1kRIZR6f52gLao6" +
                                          "otoxTE0iE5VsCqeR1ZIxUHjuDgbUVI2k2bK37AWqF1Lz3mJKT2leKnVEA6PS" +
                                          "ypKQ2LBHKPNmWbX5jh5InuqZgUyYQ2fYDZaUM+j4cn/eESiWrrHmrLTmkcjq" +
                                          "lXisjcWpUapV7XZgMOMFNTLT1BqMUrzabHpIs+mXHFGZiRjdlMr1eAintKpp" +
                                          "k83CIAaIgY4mFqsXlE1UQCtdQaipGy2Vhn1xXOHZ0bDZlFl4CkfCallliz7X" +
                                          "kIQZHrYEtzLCRixLrbBuFKPE2lsXe31m0ffNqr7y2/UUKau65DJ9l1kM8F4v" +
                                          "KEpJrzUQI0VZl0dVYjpLRnNhpFR4eaovx263MBzFllufxX5xwtngoNiwAl5U" +
                                          "llbdjuC5Z3W8AamXBr3CeuPKA7ViehsXV+nZsLj2qgu0rpKlXnXW85hqx+6X" +
                                          "pE1S70090faLvkKuIjXtE31KWMujyWi+NPSUNcvJptHoptJKpKzGQBSwxmYS" +
                                          "V8jp1JEm1YXeZApiu0W0uYJeCQKpJ0yx8YBqsyjuxqgjdj2mXBuIbDkQVl3X" +
                                          "n26qU6TEG0a/vSqsuwTliuyyhvBKoBXLZlFFZsVFw+2MZNkMYruFWkWBlun6" +
                                          "FAm51MI2VYWzCWrBMtMpVpdror2Mix3OIQ28PdgsR9UCnqb4BoMLqIYu+JmM" +
                                          "cQlB4u7CCf3WbIAhdRAgrbXbV9DZhkTYFddk8WKpW1y5fr9N0Au8F0Xrdi/0" +
                                          "zfqYGBOUyeJJoSIi+opVC3RtgWoNj6iADTZKYWTszJkGHS0Hfj0mVwNvjcu1" +
                                          "FozyVS4U4IhstZuk0aundgJ3CkOLwEfhQKVUV6cVY9apKoFd4YRaMKDItR1W" +
                                          "0Jo+rfU4TtAEPm4bmMfLpIVjSQjDBY0rdvFabYb1ZDyRytVya8SOWmllaq7F" +
                                          "Sc/uUlHSLddFUCdjuCbo+rRQ7fqLhSwsNnWgwJJeKDqWCPN6uTgc1uZaMRqw" +
                                          "Hh+ueJgq20asNCOr75OtDiyXI2Ek8mhqxVRdpg2QTHN2qFToklfVODgKLL2W" +
                                          "YJhtlebzTbnT0C05LhEsbm7mIEBmParW1fX2RMCimjdG2pa5EMalznjRIhCP" +
                                          "7zqGanuJQjoI3cJbjtEfWTyJhZrZVxOkGTXlKa3rsotuHL2N8aUigXc71GJO" +
                                          "+/XxFME3TItlyEXcnAoa1QjDUlDq8v66P655YRBhAtkgws0A7KzoBVWcoUtu" +
                                          "XagQHLA2nHooWqbR5YBhNzOcVa1qGbU66EKd10ylaHb0gWniE2qWoPUS4xEm" +
                                          "ElroPBGVuNQoS117YdbrcKtuoKVqBOsuMyBlmqGrjUlbd3UqZJN6ccMnNbQK" +
                                          "w0qy5CVjJoG6vSh6/twIpYqF9ftqkVRqQxhOZQ3HNy23OF2SdS9JJ1Nnyo/t" +
                                          "bqdPsw0OXumN2jwOB20v4E0YVLZJKcbkVt+gzbakOj7Td/zePCmPK2aIlOhE" +
                                          "qyo9ozoaN6OEtCirWvcHcXlVp3mfXYdqMWxVqkONaSyjjqnGQquAlFwEgUv2" +
                                          "aigopYU81Gyx4gwnXosaDTVCsnSuQWn+dKChVqkAzpEWv0LWUo+qkEMCF9MR" +
                                          "0pov297IX614XCzDhbDBDTeVqs2zTEtlrLLN694EFEtjQShKoHQCUkZ0t6Hz" +
                                          "3tTG43lLHGn0cFWNpg0iQKwVFjZSQeg3Vn18gqNYoVCwUqlQY3S3vkT7C4+p" +
                                          "dFrtYbSUm2NBMgtxXeB7gYWA1HNMS11GzSIV4YztkETLlHp1Q2nOyj6Yssdd" +
                                          "taBVjcFYlBNytLY1nybSQoSRhRZWrCmCT5YLo+qSLEyC0WbeXtoDt2PTPEOM" +
                                          "zXJPIMiZ7Qihxk2nm/ISqRjYpNTgvQbuLBhu5YwpnRPGUkXydIGLsN7GilK8" +
                                          "4na8LkpOi7HpB8LGspvTeanb9mG+XCYDDx0ZZRhZ1Ya1bt9xU5GoKLQxjjc0" +
                                          "pg7FWbHbkpGhzeqIVp0P2FVA1mo1XhP6tUqLrmPthjHkC810wUjtjhgSg3oV" +
                                          "VMV6ZVGsGvK0z/C1FSlMUFTt6LBdSjtVnQtUZLIsLHslFPZbuqCWk/rKLDFj" +
                                          "XfIGzLw2mKDNwEWCkuk6stxoFk0dHeMCOjPnpIr5fZW1p8rMtgoCeJa4wdhK" +
                                          "bJ6roUGcBmmrw1EcPR8gnDMGiWwzSUtmiZqZqKEhEYPU4mvdeUfqYqnbMyml" +
                                          "M0xsNSyXbXyMuzUT5SLBsLvpomH0sMVoouLgPDtuGUVQ91B7GJIbwSo1p4xt" +
                                          "Bo6YFN1Oz5VIGKmkzfGmT2H0LKT1oUrSS46mOUxb9Be1cii5MJkSo0Yf4xsD" +
                                          "gsi2wvSPdxq5Oz80HnUQwSEke1H8MXbhyVsxjKALkhxGATiqRdDFo5bmlvtO" +
                                          "1+TU4SH14dv1Z7admewQ8tDteoj5AeTl5268pPY/V8oOIBnNOuAbef4HbG2l" +
                                          "2TdxDKCnbn/Y6uYt1OOGyNee+5cHRx8yns47Arc0aljoUobJZZ3qo470e0/I" +
                                          "eZLk73Rf+Ubrfcqv7kGnj9ojtzR3b0a6dnNT5FKgRXHgjo5aIwH02C0nNE/R" +
                                          "1DjQjvk+9Yj0letffebqHnRmt2eUUXjoRAfmDt0LHMnOGBx2ky+B07a3Pp7Z" +
                                          "bccAs96RBcX94PrJg3Zj/p+9vdfP7u9MjkPrlpjZOwrS4UGEBND7jjsBlGfb" +
                                          "mpJb/erYdfKDsyTbWtaV++/LT5S+8q/PX9keK20wc+iG9789geP5nyChZ7/5" +
                                          "kf94OCdzSsn688e9jWOwbdP33mPKBNgAbjI5ko/9xUO/+TXps6ehUzR0JjRT" +
                                          "Le/Cnj7oDR5E+RNvHeUHHyUOoe/NoNeIsq96zn72JUZzc+0WuZGMHEzJ7/M8" +
                                          "Obc9yew5b0xdj6A7wS5TirRtj/OQ7LtvEWK+ivZ3YPLUf/rtDuC7PBPAareR" +
                                          "mlnpgVs+zGw/JihffOnyhftfGv9VHodHDf+LLHRBj217t/e3Mz7nB5pu5spd" +
                                          "3Iaen/+tI+j+2xg1gs5tB7m4qy18GkFXTsJH0Nn8fxfumQi6dAwHSG0HuyDP" +
                                          "RtBpAJINP5a1GHeKzEFxzA15z9sZ8ghlt0eYFab8A9hhEYm3n8CuK196iel9" +
                                          "9PXK57Y9SsWW0jT/YMJC57dZe1SIHr0ttUNa59pPvnHXly8+cVg079oKfJyq" +
                                          "O7K9983zqeH4UZ4B6R/c/3sf/K2Xvpv3yf4PFEDghpkcAAA=");
}
