package org.apache.batik.parser;
public interface LengthListHandler extends org.apache.batik.parser.LengthHandler {
    void startLengthList() throws org.apache.batik.parser.ParseException;
    void endLengthList() throws org.apache.batik.parser.ParseException;
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471109864000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVYa2wcVxW+u+t3/E5iG6dxXpsIJ2FXBYpUHEIT164d1o5l" +
                                          "p5WybrO5O3N3d+LZmcmdu/baJagUlbr8iKLg0oKof7kqoL6EqABBqyAk2qqA" +
                                          "1BIBBbVF4gflEdEICX4EKOfcO7szO7ZTCYSlvTt75tzzuud851w/fY3Uu5wM" +
                                          "MEskxKLD3MSIJaYod5k+bFLXPQW0jPZYjP7tzLuTt0dJQ5q0F6g7oVGXjRrM" +
                                          "1N002WlYrqCWxtxJxnTcMcWZy/g8FYZtpcl2wx0vOqahGWLC1hky3EN5inRR" +
                                          "IbiRLQk27gkQZGcKLElKS5LHwq+HUqRVs51Fn70vwD4ceIOcRV+XK0hn6hyd" +
                                          "p8mSMMxkynDFUJmTQ45tLuZNWyRYWSTOmbd5ITiRum1dCPY+3/H3G5cKnTIE" +
                                          "W6ll2UK6504z1zbnmZ4iHT51xGRF9zz5HImlyJYAsyDxVEVpEpQmQWnFW58L" +
                                          "rG9jVqk4bEt3REVSg6OhQYLsqRXiUE6LnpgpaTNIaBKe73IzeLu76q3ycp2L" +
                                          "jx5Krjx2pvPbMdKRJh2GNYPmaGCEACVpCCgrZhl3j+k609Oky4LDnmHcoKax" +
                                          "5J10t2vkLSpKcPyVsCCx5DAudfqxgnME33hJEzavupeTCeX9qs+ZNA++9vi+" +
                                          "Kg9HkQ4OthhgGM9RyDtvS92cYemC7ArvqPoY/wwwwNbGIhMFu6qqzqJAIN0q" +
                                          "RUxq5ZMzkHpWHljrbUhALkj/pkIx1g7V5mieZTAjQ3xT6hVwNctA4BZBtofZ" +
                                          "pCQ4pf7QKQXO59rkkYv3W2NWlETAZp1pJtq/BTYNhDZNsxzjDOpAbWw9mPoK" +
                                          "7XlxOUoIMG8PMSue7372+h2HB668onh2bMBzMnuOaSKjrWXbX79lePD2GJrR" +
                                          "5NiugYdf47mssinvzVDZAYTpqUrEl4nKyyvTPzn9wLfYn6OkZZw0aLZZKkIe" +
                                          "dWl20TFMxu9iFuNUMH2cNDNLH5bvx0kjPKcMiynqyVzOZWKc1JmS1GDL3xCi" +
                                          "HIjAELXAs2Hl7MqzQ0VBPpcdQkgjfEgEPoeJ+hvARZB7kwW7yJJUo5Zh2ckp" +
                                          "bqP/bhIQJwuxLSSzkPVzSdcucUjBpM3zSQp5UGDeCwfriycBofKigJAzRi0d" +
                                          "fEpgljn/Z/ll9G/rQiQCob8lXPgm1MyYbeqMZ7SV0vGR689mXlNJhYXgRUaQ" +
                                          "QVCZUCoTUmVCqUysU0kiEalpG6pWBwzHMweFDjytgzP3nTi7vDcGmeUs1GFw" +
                                          "y7LydlR+wMaQibLGPzXjPPHrn//xY1ES9eGgI4DjM0wMBVIQZXbLZOvy7TjF" +
                                          "GQO+tx6f+vKj1x6elUYAx76NFMZxHYbUAzwFXHrolfNvvvP22tVo1fCYAAwu" +
                                          "ZaGVCdJEswBgVBOCNFeRSDm27X34i8Dn3/hBH5Ggsqp72Evt3dXcdpxAOCLy" +
                                          "uU+Q/TePvhd5DN7OzSBDwt3agyur+sknb1WF3V1bhiPQZZ755b9+mnj8d69u" +
                                          "kAHNwnY+YrJ5ZgYsjKLKmnlhQqJppfdmtLfaL//++/H88SipS5FuCFGJmtj5" +
                                          "j/E89BRtzoPd1iwMEX4v3x3o5TiEcFtjOrSSzXq6J6XJnmcc6YJsC0ioTBqI" +
                                          "qQc37/Nh019+8E/9p44WzsqcC3Zu1FYPTQd3TmG/rfbVXaHwh0V+c+LpV+86" +
                                          "oF2OylaDsL1Bi6rdNBQ8CFDKGfRUC91BShso3Ruu6XC0MtrB3fSFzIsX4vIU" +
                                          "mqHfCgr4CK1sIKy8pl0MVWoNVTVBEHI2L1ITX1VC3iIK3F7wKRJsulTqQ4LI" +
                                          "qu6HT9wDVPmNb3scXHsVOEn+AbnuwSWusgsf9+NyQLJ9GLLtgF/O0AFMQEk8" +
                                          "kfjdFhy7kTNo1mQINP/s2H/rC3+52KkS2QRK5YgOf7AAn/6h4+SB1878Y0CK" +
                                          "iWg4gfiQ47OptrbVl3yMc7qIdpQ//8bOr75Mn4AGCU3JNZaY7DPEgzs0ali6" +
                                          "fVSux7Hqa2v/wGa1L2e2kbLGHDRBihrB5ZMAjHDuXPjQDMYN3mS+5UYRQHPe" +
                                          "mxCSF7rfmfv6u88okAiPEyFmtrzypfcTF1dUnNXMtW/d2BPco+YuaW6nPFSE" +
                                          "rT030yJ3jP7huQs/+MaFh6Ne1BKC1M3bhg6b45u4FpiiM9qlq++13fPeS9el" +
                                          "obVjeLCNTFBH2daFyxDa1htuZGPULQDfx69M3ttpXrkBEtMgUYPG7J7k0EjL" +
                                          "NU3H465v/M2Pftxz9vUYiY6SFtOm+ijFgRfGFqgg5hagB5edT9+hqmShCZZO" +
                                          "mSKkmhgk2DCDBEy+XRun9UjRETIRl77X+50jT62+LRuYajIfra3SPvgc8qr0" +
                                          "0P9UpbX5HMz1zMa5jj9HJQPFJS3wzqP7+YvElNw0hcusCsHMfxktJJx2yoJ0" +
                                          "rRteMJJ96+5Gap7Xnl3taOpdvftXEkSrM3crtJ1cyTQDGB3E6waHs5whfWtV" +
                                          "ieXIL0OQ3k0qGwcL+SBNLyh+aBSdYX5B6uV3kM8WpMXnA1HqIcgCCmLAgo+u" +
                                          "45QjtQNYNcrbPyjKgZltX00JyjtopQOW1C00oz23emLy/uufeFKNcHB7XVqS" +
                                          "dxa4gqm2Uu2iezaVVpHVMDZ4o/355v0VNOhSBvtZuiOQdKchwxw82f4QQLvx" +
                                          "Kk6/uXbkpZ8tN7wBxTxLIlSQrbOBG6C67gDKl2DcmU35A0/gfxiycwwNfm3x" +
                                          "6OHcX38ry0zCOMzcm/NntKtP3feLy31r0GG2jJN6ADpWTsN11r1z0Zpm2jxP" +
                                          "kzbDHSmDiSAF7tfjpKlkGedLbBxuzu2YhBRvpzIuXjjbqlScBATZux6P149T" +
                                          "AEkLjB+3S5Yu5woASZ9SczmuDCIlxwlt8CnVo9y23veMducjHT+81B0bhUKq" +
                                          "cScovtEtZatDTvC+rKaeQPtQs3Qsk5pwnMpsXT/tYdwXFA/SBYkc9Kgh6Pmi" +
                                          "FPeQfMRl+T93siS6ChMAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471109864000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5eezk1lne396bYzdpm4RtkzTJpiJ1+vPMeDye0fYaezyn" +
                                          "PWOP53RLNx7f9z3jmRLURpRGBJUKtlCkNn+lAqr0EKICCRUFIWirVkhFFZdE" +
                                          "UyEkjhKp+YNDBCjPnt+92UQVYiS/eX7+3ncffp9ffAU6G4UQ7Hv2WrO9eFdJ" +
                                          "413Txnbjta9Eu10aY8UwUmTSFqNoBNZuSI9+9fK/vfZp/coOdE6A3iK6rheL" +
                                          "seG50VCJPHupyDR0+XCVshUniqErtCkuRSSJDRuhjSi+TkN3HNkaQ9fofRYQ" +
                                          "wAICWEByFpD6IRTYdJfiJg6Z7RDdOAqgn4NO0dA5X8rYi6FHjiPxxVB09tCw" +
                                          "uQQAw4XsfgKEyjenIfTOA9m3Mt8i8Gdg5Oavf+TK75yGLgvQZcPlM3YkwEQM" +
                                          "iAjQnY7iLJQwqsuyIgvQPa6iyLwSGqJtbHK+BejeyNBcMU5C5UBJ2WLiK2FO" +
                                          "81Bzd0qZbGEixV54IJ5qKLa8f3dWtUUNyHrfoaxbCZvZOhDwkgEYC1VRUva3" +
                                          "nLEMV46hh0/uOJDxWg8AgK3nHSXWvQNSZ1wRLED3bm1ni66G8HFouBoAPesl" +
                                          "gEoMXb0t0kzXvihZoqbciKEHTsKx20cA6mKuiGxLDL3tJFiOCVjp6gkrHbHP" +
                                          "K/33fuqjbtvdyXmWFcnO+L8ANj10YtNQUZVQcSVlu/HOd9O/Jt739Wd3IAgA" +
                                          "v+0E8Bbm93721Q8++dBL39zCvP11YAYLU5HiG9ILi7u/+w7yidrpjI0LvhcZ" +
                                          "mfGPSZ67P7v35Hrqg8i77wBj9nB3/+FLwz+df+yLyg93oEsd6Jzk2YkD/Oge" +
                                          "yXN8w1bCluIqoRgrcge6qLgymT/vQOfBnDZcZbs6UNVIiTvQGTtfOufl90BF" +
                                          "KkCRqeg8mBuu6u3PfTHW83nqQxB0HlzQKXA9CW1/D2VDDH0Y0T1HQURJdA3X" +
                                          "Q9jQy+SPEMWNF0C3OrIAXm8hkZeEwAURL9QQEfiBruw98LP4ChFacbVYz3JB" +
                                          "W3RlINNu5mX+/zP+NJPvyurUKaD6d5wMfBvETNuzZSW8Id1MCOrVL9/49s5B" +
                                          "IOxpJoaeACR3tyR3c5K7W5K7t5CETp3KKb01I701MDCPBQIdwNz5BP8z3aee" +
                                          "ffQ08Cx/dSZTbppH3gP5zWmw74nbp+VmlhM6eR6UgJs+8J8De/HM3/1Hzu7R" +
                                          "zJoh3HmdUDixX0Be/NxV8v0/zPdfBEkoFoHTgPh+6GRAHouhLDJPqhHk1kO8" +
                                          "pS86/7rz6Lk/2YHOC9AVaS9xT0Q7UXgFJM9LRrSfzUFyP/b8eOLZRtn1vQCP" +
                                          "oXec5OsI2ev7WTIT/uxR84F5Bp3NL+WucHcOc8+Pwe8UuP4nuzJLZAtbd7+X" +
                                          "3Iu5dx4Ene+np07F0NnSLr5byPY/ktn4pIIzBt7H+5//qz/7J3QH2jnM3JeP" +
                                          "1EKghOtHskWG7HKeF+45dJlRqGTK+tvPsr/6mVc++aHcXwDEY69H8Fo2ZhyD" +
                                          "0gdKyCe+Gfz1y99/4Xs7Bz52OgblMlnYhgQmUV7JgCSq4Yp2rpBHY+h+05au" +
                                          "7Us9AZUNMHbNtPFcVW8DtTxnLbPK7rYc5DEFOLp2G3c9UsJvSJ/+3o/umvzo" +
                                          "D1+9xVOPK4YR/etbC+VcpQD9/SejqC1GOoArv9T/8BX7pdcARgFglEBWiAYh" +
                                          "iOL0mBr3oM+e/5s/+uP7nvruaWinCV2yPVFuilm1BTkz1kGB1kECSP0PfHCb" +
                                          "81YXwHAlj00ol//tW3bysL77UBG0B6ric3//6e/88mMvAz660Nll5sOAgyPa" +
                                          "6ifZi8IvvPiZB++4+YPncpuADDv5+deufjDDWs0JPJ6PP50N8NZi2fTJbHhP" +
                                          "Nuzum+lqZiY+z4K0GMWMJxvgRUHOLfWGqYMNDQd423KvCiJP3/uy9bl//NK2" +
                                          "wp3MEyeAlWdv/uKPdz91c+fIe8Vjt5T2o3u27xY503cdmPKRN6KS72j+w1ee" +
                                          "/oPfevqTW67uPV4lKfAS+KW/+O/v7H72B996nQR9xvb2nTIbS3tksz/szQ0b" +
                                          "33GzXY469f0fPZmLpZU0SadwAscoQmFGqyKnMz/qdEvNGTH3x22qMypWynLR" +
                                          "w2wfm64X4QAboH1UhmnBkRw5AaWpK2pjexFWjR6tFbyep+JW4NEVKqgTRLCu" +
                                          "W6UgqBeJDkEsJs2yptqUTHXIWZnqDVRpgEebAS6MyDlvL0cxjsWbTZLIVay4" +
                                          "QtQ5Ok6wFcNQkZX26AbK8J2uOPdkzIIXTXrGctOCyQpzk8XjDZ2M4oLc5bCg" +
                                          "0KxouDdpzcxhyBT7hUJpas/DgJymcdpN3ZHESFNhjWjV5lyIwft1aZUWloNA" +
                                          "1FtTmizq1hql+pjhDoedhTGkOauEaxYntKQeTdk9HqPbqwBuj4PhJMKKTRcv" +
                                          "LFeNsqR0BtJwAs96Bd2t6GvZrzo8w6TW2m00x11nxJWxmE6E/nQ9nE/50cBZ" +
                                          "yFhnZAwTpyiT7BxGkTbawqSeO+pQ04ptl8a9ClYob4qbhesIZaM9woppa9is" +
                                          "bTZYu+PY6+68Hq0b6YSa+JTPOdzUbU6xKh22auYksMoLKkaH1ITXKgOdm9NR" +
                                          "MJwZY6pCu77mi6N+RyR6Co52Ngqd4JUAXUt+iTZTrBeaaclfsgtG7g27eqnV" +
                                          "n7OO2CKpOjnxSVILBd1GTdiqFGoDa12mG67TlryemGLdYiEuLS2a93sSu55E" +
                                          "JJlijXoiq0GquQyFonqX2ohL8D48IpVZLYhgoV+H4drSgHtarW1x5UGs61qL" +
                                          "qQ3XjXjJ10rSXHFIvB4uA9abIyvw6y9aHZ1pJpUg2ATdeqdfCIbjNMAEZmO1" +
                                          "/WnbNsPFWK/Tlon4VictavgEcwxFGNVNDk1HFX2y6ktxvUwIROypgk9yZV/F" +
                                          "uR43G2C10LLmS3Ra6k9talQX/KLfjQOEGM37ekPoR+nGbAz8+mK6qjms18Nn" +
                                          "djoYex2mVWUZPgG6xEuwXmoTlUrVc/XSgiE2jJsMRL5nhtPZYobXbIVtlFrd" +
                                          "cIj1jUSby2oZd6LIcJebSUOoz0d+MA4pu+z21uvliN24tRWtzt3KwBKEVUGk" +
                                          "BaFndRR5apcKoyaTJjWjmfTHTLsk9Rt9uo0tlmnBMtmexBhrN1hPNgNh2pOK" +
                                          "XYcvtho0mpJGu2PWKXpWj0ptG2eCDVeYEKwvyZylmSqlUayndGF9WR8KBG6t" +
                                          "pvi62x17mKCXJMtfBCyy0Dtcd5WkNM9vLHay4WUpkcYm4TPohud8bNxqKORK" +
                                          "DY21RHhqz9C69c3QKMgq5Wu26SICYtu1FhJyBkd6i6o9YzWnyKznCyVgBJyf" +
                                          "FJatYaVac2Z2v6vPZ9pwLHLchBTGpDcaOxMyGK+jccEyKNH2WxV/Sqw2bWal" +
                                          "NBvmOtY2LOqODHzZkFqOMo6KreZqjdNr2R7CK0bkjAXdYjczk2XboYsg6bxI" +
                                          "8TWlpXXKDZMprBhi0uGE2YIWBss1PjKbLW4Ax2lFhZc9s5hWFHs8r6d4pd9k" +
                                          "hLQ9X4zrm1Vz1g49W+0vl0u2VIonXlEl5/X6KhHE1oSUu1S0IrQJMSD7TWXI" +
                                          "N5wSPkPLRrXhoohOtLEWeInz8RK1jFF5Jsl+Wh+Q9DoZwxwyUtilLmONPj7Y" +
                                          "8ERjFaOitk5COLLcRXHaRCfFhW6wnCDgGLaowY5rVuVKLbHq7f7KncPzsIsJ" +
                                          "2jwye3TPcW2dC7q+r8pOTKsijSAwjLSrVd7weayZkM1W14lNzESoao0YxhuP" +
                                          "lYvGiqFm5SWaoh42MiipGZuDEBh9FlS6lVnXdSSpMu9GZMHwRkTQCTgJxZG+" +
                                          "XijW4CqF1PxyebqJAolEhaTYnLMjTkZHDjC8upjMxPZKL0xgCab9CVyteM3S" +
                                          "YG2LjYguEkYllPsEVyWbjV5LHY7JWpHg9chDh0lSmZEFJg4JVOWbm04EuOuM" +
                                          "naCtgpRUJnvFqNNbV327wEymXn8ymhBUu1Oii53RrDghUaPTQ5v4CmS0KLFH" +
                                          "AVemO0FSaY9qq8aEdfoLNJJm7WgyoFy4vnCTFT9NIi1Sa3B/zdHdWoumY62J" +
                                          "DAr1JsNRVtVSTbmpr3Fr1PeKDtfpswgIKSQkURgr9Sy+xA172FwbqHi97iIV" +
                                          "vQzzRLGKV+cFsmdMNVACDa6MD/w4XExsdM1IeNCRfQ5BqotBiGOMW663yDHa" +
                                          "7QviHG+wlLaJCqJtVNQJn6R4OxBLS2TVEot0SSlZwK/bjSFh6CEB8mDdbDeS" +
                                          "GWtyDWbeRx0exsbzIddmFScl+SYeqo66rCTVqmfVDZZaN5043Kx9VRo1i/LY" +
                                          "7c+YeIrIJYKVPHieiNOKyzZ5KhwV0MK6i4I6qydchMCM2NQrfaVI9Mgigy50" +
                                          "rbIoY0m56RsGUwvsAIaLqMoqIMBsbzExFZrsj5pEuySLzXXaEIt6nAgtdkxz" +
                                          "DTWt1Bg0jv1ZaBFUzGjjOdvCu7hVoEy6P0bb5Qq2RJgSq8bpprYcz415hW/G" +
                                          "Awc2zKY2VFvNQNMwXdQITJFHNVgPHF4nBWHg8D3L0TWr1CAbBLWGZ8PErY3N" +
                                          "ITXqDG0cn8FYwRxVSjA9TOai2VFDEeXZpSZVg7BQYGtjfzHD2gwov4yImWat" +
                                          "3eXYZpdHV5uAxeH5krL7q4IuJREZtRk1teJuNy2tvW4hHMYK0+3WKjDWEn18" +
                                          "5tpoLA58eanGM8riQwaVwrhblNYjrtEiUKqyEtsRttLVaTwxlFmHLgw41CoE" +
                                          "rZVEA7fp02sdFglens8wopJMUIupTn1m5taL7aAjaSTp0HXNg5Myxpkx15/3" +
                                          "pXDBrs2eJtjxrFDors3Y87nBtEgWCt6mhCoOvUaSRFWavb7UJvDZJODlVCxr" +
                                          "gVMaJyVD2YiTid+eMA2h7CEohi0Lk/5A54llLCTGgJN7kr5KV9WSWuY4epn2" +
                                          "rAqSzBaWL1TjPr4i0lFKd2yeCxcDolUhK7jW6NmlhuSMUaxeQDQ1BdUBVHLV" +
                                          "QdPKoC3N0Gq4LmzIAbORHKTvxr2YRVWFXqPFsNBqlcxuv1Jv+NNR1C8Ww+Km" +
                                          "IPhOyUxZa7NotHmnYfD1Jh6rpt+zrZYi0wsiTTZJaa4Tw6W/6SQz01wENi8R" +
                                          "9ZGQpBW2WK6N6pRFmwSM8tgcvF56dV6o8dLGSRpkx05Xdlwl3YlXW5fQpcLI" +
                                          "iWS2R3C1SBQW+rgXSLzkLWMqFsS4MVqScNgTFY6NuQjlIgvzVy7jR7MREs/l" +
                                          "1axZR3hibkm1nqZXWMdosgqnMkMbHtXQyOArpM6Al/D3vS97Pe/8ZCeke/KD" +
                                          "7EGTExyMsgeFn+BkkL4RwRi6IC6iOATHxxi6eNB13VI/0sk5tX9wfvyNG0d7" +
                                          "TaPsfPTg7bqd+dnohWduPi8PvlDMzkYZ6gYgDxz4PbayVOwjhHcApnff/hzI" +
                                          "5M3ew17NN57556uj9+tP5c2KW3pINHQp28lmPfWD3vnDJ/g8ifK3mRe/1XqX" +
                                          "9Cs70OmDzs0tbejjm64f79dcCpU4Cd3RQdcmhB695fDoSYqchMoh3Xe/U/za" +
                                          "ja8/fW0HOnO0nZVhePBEc+gO1Qsd0c4I7Pe9L8V66K0OV452ioBa81bdVXBd" +
                                          "22uM5v/Z07f42fjW9NDDbnGdnQNfHe45Sgi967BJQXq2rUi51q+NXSc/04sL" +
                                          "W8kahv91+fHi1/7lU1e2J14brOyb4ck3R3C4/lME9LFvf+TfH8rRnJKyLwmH" +
                                          "bZdDsG17+i2HmOthKK4zPtKP//mDv/EN8fOnoVMd6ExkbJS8Xwzt9TAzpvRc" +
                                          "bCkftSwEjgfCu24XCPm3FyqVFD9jIUdlZsONGLoMbBvGhy3WHNcHjgQwCQ7+" +
                                          "S8+QDyP7qTc782tH2M4XPnTcyA+AC94zMvx/MvJxdRxV1fr1VZXdWjnAR7MB" +
                                          "ZJi7sub+gfjZonsoavKTiJqC1HhLrzqz9gO3fArbfr6Rvvz85Qv3Pz/+yzye" +
                                          "Dj6xXKShC2pi20fbq0fm5/xQUY1chovbEPLzv2di6P7bOEDWnMwnOc8f38J/" +
                                          "IoaunISPobP5/1G4Z2Po0iEcQLWdHAV5LoZOA5Bs+ktZF/dIstzzgFyb976Z" +
                                          "Ng+2HG3DZgk2/+S4nwyT7UfHG9JXnu/2P/pq5QvbNrBki5tNhuUCDZ3fZp+D" +
                                          "hPrIbbHt4zrXfuK1u7968fH95H/3luFDbzzC28Ovnxcox4/zSN78/v2/+97f" +
                                          "fP77eSvyfwEpkEVpCx4AAA==");
}
